# Emulator harness environment. Source this from the repo root before running scripts/emu/*.mjs:
#
#   source scripts/emu/env.sh
#
# Full run, from a clean checkout:
#   1. Terminal A — emulators (needs a JDK on PATH for Firestore/Storage):
#        PATH="/opt/homebrew/opt/openjdk/bin:$PATH" \
#        npx firebase-tools emulators:start --only auth,firestore,functions,storage --project demo-test
#   2. Terminal B — the app, pointed at the emulators:
#        source scripts/emu/env.sh && npx vite --mode emulator --port 5199
#   3. Terminal C — seed then test:
#        source scripts/emu/env.sh
#        node scripts/emu/seed.mjs
#        node scripts/emu/test-flows.mjs   # callables + Firestore/Storage state
#        node scripts/emu/test-rules.mjs   # security rules + comments, via the client SDK
#        node scripts/emu/test-ui.mjs      # the UI in headless Chrome over CDP
#
# Everything is pinned to the demo-test project: the Firebase SDKs refuse to contact real
# Google backends for a "demo-" project, so this harness cannot reach production.
export GCLOUD_PROJECT=demo-test
export GOOGLE_CLOUD_PROJECT=demo-test
export FIRESTORE_EMULATOR_HOST=127.0.0.1:8080
export FIREBASE_AUTH_EMULATOR_HOST=127.0.0.1:9099
export FIREBASE_STORAGE_EMULATOR_HOST=127.0.0.1:9199

# The Vite dev server needs its own env file (Vite only reads VITE_* from .env files, not the
# shell). Written here so the harness is self-contained; all values are fake demo values.
_emu_env_file="$(dirname "${BASH_SOURCE[0]:-${(%):-%x}}")/../../.env.emulator"
if [ ! -f "$_emu_env_file" ]; then
  cat > "$_emu_env_file" <<'ENV'
# Generated by scripts/emu/env.sh — local emulator suite only, all values are fake.
# Loaded by `vite --mode emulator`. The demo- project id means the Firebase SDKs will not
# talk to real Google backends even if the emulator connection code were removed.
VITE_FIREBASE_API_KEY=fake-api-key
VITE_FIREBASE_AUTH_DOMAIN=demo-test.firebaseapp.com
VITE_FIREBASE_PROJECT_ID=demo-test
VITE_FIREBASE_STORAGE_BUCKET=demo-test.appspot.com
VITE_FIREBASE_MESSAGING_SENDER_ID=000000000000
VITE_FIREBASE_APP_ID=1:000000000000:web:demotest
VITE_USE_EMULATORS=true
ENV
  echo "wrote $_emu_env_file"
fi
unset _emu_env_file
