import type { ArtistBio } from './types'

export const batch2Bios: ArtistBio[] = [
  {
    artistId: 'twice',
    agency: 'JYP Entertainment',
    debutDate: '2015-10-20',
    fandomName: 'ONCE',
    fandomColorName: 'Apricot & Neon Magenta',
    fandomColorHex: '#FCC89B',
    members: [
      {
        memberId: 'nayeon',
        birthdate: '1995-09-22',
        zodiacSign: 'Virgo',
        heightCm: 163,
        weightKg: 47,
        interests: ['badminton'],
        favoriteFoods: ['sweet foods and jellies', 'salmon sushi', 'spicy foods', 'marinated soy sauce crabs'],
        position: 'Lead Vocalist, Lead Dancer, Center',
      },
      {
        memberId: 'jeongyeon',
        birthdate: '1996-11-01',
        zodiacSign: 'Scorpio',
        heightCm: 169,
        weightKg: 50,
        interests: ['collecting Nanoblocks and Legos', 'cleaning', 'playing saxophone and guitar'],
        favoriteFoods: ['Ddeokbokki', 'meat', 'golbangee muchim'],
        position: 'Lead Vocalist',
      },
      {
        memberId: 'momo',
        birthdate: '1996-11-09',
        zodiacSign: 'Scorpio',
        heightCm: 167,
        weightKg: 48.5,
        interests: ['watching dramas', 'collecting dolls and stuffed toys', 'urban/hip-hop dancing'],
        favoriteFoods: ['jokbal', 'budae jjigae'],
        position: 'Main Dancer, Sub-Vocalist, Sub-Rapper',
      },
      {
        memberId: 'sana',
        birthdate: '1996-12-29',
        zodiacSign: 'Capricorn',
        heightCm: 168,
        weightKg: 47,
        interests: ['collecting perfumes and body mists', 'shopping', 'watching horror films', 'calligraphy'],
        favoriteFoods: ['yogurt smoothies', 'spicy foods'],
        position: 'Sub-Vocalist',
      },
      {
        memberId: 'jihyo',
        birthdate: '1997-02-01',
        zodiacSign: 'Aquarius',
        heightCm: 162,
        weightKg: 56,
        interests: ['reading webtoons', 'karaoke', 'classical/R&B music'],
        favoriteFoods: ['yogurt smoothies', 'chicken', 'meat'],
        position: 'Leader, Main Vocalist',
      },
      {
        memberId: 'mina',
        birthdate: '1997-03-24',
        zodiacSign: 'Aries',
        heightCm: 163,
        weightKg: 46,
        interests: ['ballet', 'looking up restaurants online', 'shopping'],
        favoriteFoods: ['egg with ketchup', 'Heinz ketchup', 'Americano'],
        favoriteAnimal: 'Great white shark',
        position: 'Main Dancer, Sub-Vocalist',
      },
      {
        memberId: 'dahyun',
        birthdate: '1998-05-28',
        zodiacSign: 'Gemini',
        heightCm: 165,
        weightKg: 48.9,
        interests: ['watching TV', 'playing piano', 'dancing'],
        favoriteFoods: ['chocolate milk', 'chocolate'],
        position: 'Lead Rapper, Sub-Vocalist',
      },
      {
        memberId: 'chaeyoung',
        birthdate: '1999-04-23',
        zodiacSign: 'Taurus',
        heightCm: 163,
        weightKg: 46,
        interests: ['drawing', 'basketball', 'songwriting', 'singing'],
        favoriteFoods: ['vegetables/healthy foods'],
        position: 'Main Rapper, Sub-Vocalist',
      },
      {
        memberId: 'tzuyu',
        birthdate: '1999-06-14',
        zodiacSign: 'Gemini',
        heightCm: 170,
        weightKg: 48,
        interests: ['watching performances', 'skateboarding', 'singing Disney songs'],
        favoriteFoods: ['tonkatsu', 'kimbap', 'choco-ae-mong', 'cookies and cream ice cream'],
        favoriteAnimal: 'Puppies',
        position: 'Lead Dancer, Sub-Vocalist, Visual, Maknae',
      },
    ],
  },
  {
    artistId: 'blackpink',
    agency: 'YG Entertainment',
    debutDate: '2016-08-08',
    fandomName: 'BLINK',
    members: [
      {
        memberId: 'jisoo',
        birthdate: '1995-01-03',
        zodiacSign: 'Capricorn',
        heightCm: 162,
        weightKg: 44,
        interests: ['the color purple', 'Pikachu merchandise', 'playing drums and piano'],
        favoriteFoods: ['rice'],
        favoriteAnimal: 'Bunny',
        position: 'Lead Vocalist, Visual',
      },
      {
        memberId: 'jennie',
        birthdate: '1996-01-16',
        zodiacSign: 'Capricorn',
        heightCm: 163,
        weightKg: 45,
        interests: ['photography', 'fashion and styling', 'playing guitar, piano and flute'],
        favoriteFoods: ['Korean cuisine', 'soybean paste stew', 'milk-flavored ice cream'],
        favoriteAnimal: 'Chinchilla',
        position: 'Main Rapper, Lead Vocalist',
      },
      {
        memberId: 'rose',
        birthdate: '1997-02-11',
        zodiacSign: 'Aquarius',
        heightCm: 168.7,
        weightKg: 44,
        interests: ['playing guitar', 'drawing', 'riding bicycle'],
        favoriteFoods: ['kimchi stew'],
        favoriteAnimal: 'Squirrel',
        position: 'Main Vocalist, Lead Dancer',
      },
      {
        memberId: 'lisa',
        birthdate: '1997-03-27',
        zodiacSign: 'Aries',
        heightCm: 166.5,
        weightKg: 44.7,
        interests: ['dancing', 'playing guitar, piano and ukulele'],
        favoriteFoods: ['gamjatang'],
        favoriteAnimal: 'Chick',
        position: 'Main Dancer, Lead Rapper, Sub-Vocalist, Maknae',
      },
    ],
  },
  {
    artistId: 'red-velvet',
    agency: 'SM Entertainment',
    debutDate: '2014-08-01',
    fandomName: 'ReVeluv',
    fandomColorName: 'Pastel Coral',
    members: [
      {
        memberId: 'irene',
        birthdate: '1991-03-29',
        zodiacSign: 'Aries',
        heightCm: 160,
        weightKg: 44,
        interests: ['dancing', "cooking (seaweed soup for members' birthdays)"],
        favoriteAnimal: 'Rabbit',
        position: 'Leader, Main Rapper, Lead Dancer, Sub-Vocalist, Visual, Center',
      },
      {
        memberId: 'seulgi',
        birthdate: '1994-02-10',
        zodiacSign: 'Aquarius',
        heightCm: 164,
        weightKg: 44,
        interests: ['drawing', 'playing guitar'],
        favoriteAnimal: 'Brown Bear',
        position: 'Main Dancer, Lead Vocalist',
      },
      {
        memberId: 'wendy',
        birthdate: '1994-02-21',
        zodiacSign: 'Pisces',
        heightCm: 160,
        weightKg: 47,
        interests: ['finding rare songs', 'cooking', 'singing', 'playing piano, guitar, flute and saxophone'],
        favoriteAnimal: 'Squirrel',
        position: 'Main Vocalist',
      },
      {
        memberId: 'joy',
        birthdate: '1996-09-03',
        zodiacSign: 'Virgo',
        heightCm: 168,
        weightKg: 49,
        interests: ['watching movies', 'singing'],
        favoriteAnimal: 'Chick',
        position: 'Lead Rapper, Sub-Vocalist',
      },
      {
        memberId: 'yeri',
        birthdate: '1999-03-05',
        zodiacSign: 'Pisces',
        heightCm: 160,
        weightKg: 49,
        favoriteFoods: ['tuna kimchi fried rice'],
        favoriteAnimal: 'Turtle',
        position: 'Sub-Vocalist, Sub-Rapper, Maknae',
      },
    ],
  },
  {
    artistId: 'seventeen',
    agency: 'Pledis Entertainment',
    debutDate: '2015-05-26',
    fandomName: 'CARAT',
    fandomColorName: 'Rose Quartz & Serenity',
    fandomColorHex: '#F7CAC9',
    members: [
      {
        memberId: 's-coups',
        birthdate: '1995-08-08',
        zodiacSign: 'Leo',
        heightCm: 178,
        weightKg: 65,
        interests: ['acting (dream career)', 'taekwondo (black belt, 7 years)'],
        position: 'Leader, Hip-Hop Team Leader, Rapper, Sub-Vocalist',
      },
      {
        memberId: 'jeonghan',
        birthdate: '1995-10-04',
        zodiacSign: 'Libra',
        heightCm: 178,
        weightKg: 62,
        interests: ['playing bass guitar'],
        favoriteFoods: ['pasta', 'Korean stews', 'chicken'],
        position: 'Lead Vocalist, Visual',
      },
      {
        memberId: 'joshua',
        birthdate: '1995-12-30',
        zodiacSign: 'Capricorn',
        heightCm: 177,
        weightKg: 60,
        interests: ['reading', 'sleeping', 'singing', 'playing guitar', 'watching movies', 'anime (One Piece, Naruto, Bleach)'],
        position: 'Lead Vocalist, Visual',
      },
      {
        memberId: 'jun',
        birthdate: '1996-06-10',
        zodiacSign: 'Gemini',
        heightCm: 182,
        weightKg: 66,
        interests: ['reading fantasy novels', 'playing games', 'playing piano', 'martial arts'],
        favoriteFoods: ['spicy foods'],
        position: 'Lead Dancer, Sub-Vocalist',
      },
      {
        memberId: 'hoshi',
        birthdate: '1996-06-15',
        zodiacSign: 'Gemini',
        heightCm: 177,
        weightKg: 61,
        interests: ['choreography'],
        favoriteFoods: ['Japanese food'],
        position: 'Performance Team Leader, Main Dancer, Lead Vocalist, Sub-Rapper',
      },
      {
        memberId: 'wonwoo',
        birthdate: '1996-07-17',
        zodiacSign: 'Cancer',
        heightCm: 182,
        weightKg: 63,
        position: 'Rapper, Sub-Vocalist',
      },
      {
        memberId: 'woozi',
        birthdate: '1996-11-22',
        zodiacSign: 'Sagittarius',
        heightCm: 166,
        weightKg: 60,
        interests: ['classical music', 'playing clarinet', 'music production'],
        favoriteFoods: ['jjajangmyeon mixed with spicy ramen'],
        position: 'Vocal Team Leader, Lead Vocalist, Producer',
      },
      {
        memberId: 'the8',
        birthdate: '1997-11-07',
        zodiacSign: 'Scorpio',
        heightCm: 180,
        weightKg: 58,
        interests: ['Chinese Wushu (martial arts, since age 5)', 'nunchucks', 'reading', 'fashion'],
        position: 'Lead Dancer, Sub-Vocalist, Sub-Rapper',
      },
      {
        memberId: 'mingyu',
        birthdate: '1997-04-06',
        zodiacSign: 'Aries',
        heightCm: 187,
        weightKg: 76,
        interests: ['hairstyling'],
        position: 'Rapper, Sub-Vocalist, Visual, Face of the Group',
      },
      {
        memberId: 'dk',
        birthdate: '1997-02-18',
        zodiacSign: 'Aquarius',
        heightCm: 179,
        weightKg: 66,
        favoriteFoods: ['doenjang jjigae', 'pizza'],
        position: 'Main Vocalist',
      },
      {
        memberId: 'seungkwan',
        birthdate: '1998-01-16',
        zodiacSign: 'Capricorn',
        heightCm: 174,
        weightKg: 58,
        interests: ['volleyball', 'calligraphy', 'basketball', 'singing'],
        favoriteFoods: ['hamburgers'],
        position: 'Main Vocalist, Face of the Group',
      },
      {
        memberId: 'vernon',
        birthdate: '1998-02-18',
        zodiacSign: 'Aquarius',
        heightCm: 178,
        weightKg: 62,
        interests: ['Harry Potter'],
        favoriteFoods: ['chocolate'],
        position: 'Rapper, Sub-Vocalist, Visual, Face of the Group',
      },
      {
        memberId: 'dino',
        birthdate: '1999-02-11',
        zodiacSign: 'Aquarius',
        heightCm: 174,
        weightKg: 56,
        interests: ["choreography (made 'Jam Jam' and 'Flower')"],
        favoriteFoods: ['apples', 'grapes', 'fried squid with spicy sauce'],
        position: 'Main Dancer, Sub-Vocalist, Sub-Rapper, Maknae',
      },
    ],
  },
  {
    artistId: 'mamamoo',
    agency: 'RBW',
    debutDate: '2014-06-18',
    fandomName: 'MOOMOO',
    fandomColorName: 'Green',
    members: [
      {
        memberId: 'solar',
        birthdate: '1991-02-21',
        zodiacSign: 'Pisces',
        heightCm: 163,
        weightKg: 45,
        interests: ['swimming', 'playing piano'],
        favoriteAnimal: 'Dog (owns two dogs, Yongkeey and Yongdoong)',
        position: 'Leader, Vocalist',
      },
      {
        memberId: 'moonbyul',
        birthdate: '1992-12-22',
        zodiacSign: 'Capricorn',
        heightCm: 165,
        weightKg: 45,
        interests: ['songwriting/rap lyrics'],
        favoriteAnimal: 'Dog (owns four corgis)',
        position: 'Rapper, Performer',
      },
      {
        memberId: 'wheein',
        birthdate: '1995-04-17',
        zodiacSign: 'Aries',
        heightCm: 162,
        weightKg: 42,
        interests: ['watching mukbang', 'drawing'],
        favoriteAnimal: 'Cat (owns a Scottish Fold named Ggomo)',
        position: 'Vocalist, Performer',
      },
      {
        memberId: 'hwasa',
        birthdate: '1995-07-23',
        zodiacSign: 'Leo',
        heightCm: 162,
        weightKg: 44,
        interests: ['cooking', 'listening to old jazz music'],
        favoriteAnimal: 'Lion',
        position: 'Vocalist, Rapper, Maknae',
      },
    ],
  },
  {
    artistId: 'got7',
    agency: 'Kakao Entertainment',
    debutDate: '2014-01-16',
    fandomName: 'I GOT7 (Ahgase)',
    fandomColorName: 'Green & White',
    members: [
      {
        memberId: 'jb',
        birthdate: '1994-01-06',
        zodiacSign: 'Capricorn',
        heightCm: 179,
        weightKg: 70,
        interests: ['watching movies', 'taking pictures', 'traveling', 'eating out'],
        favoriteFoods: ['soondubu jjigae'],
        favoriteAnimal: 'Cat',
        position: 'Leader, Main Vocalist, Lead Dancer, Center',
      },
      {
        memberId: 'mark',
        birthdate: '1993-09-04',
        zodiacSign: 'Virgo',
        heightCm: 175,
        weightKg: 60,
        interests: ['skateboarding', 'snowboarding'],
        favoriteFoods: ['hamburger', 'meat'],
        position: 'Lead Rapper, Visual',
      },
      {
        memberId: 'jackson',
        birthdate: '1994-03-28',
        zodiacSign: 'Aries',
        heightCm: 174,
        weightKg: 67,
        interests: ['fencing'],
        favoriteFoods: ['chocolate', 'dim sum', 'spaghetti carbonara', 'chicken', 'hamburgers'],
        position: 'Main Rapper, Lead Dancer, Face of the Group',
      },
      {
        memberId: 'jinyoung',
        birthdate: '1994-09-22',
        zodiacSign: 'Virgo',
        heightCm: 178,
        weightKg: 63,
        interests: ['dancing', 'choreography'],
        favoriteFoods: ['hamburger', 'pizza', 'meat'],
        position: 'Sub-Vocalist, Visual, Center, Face of the Group',
      },
      {
        memberId: 'youngjae',
        birthdate: '1996-09-17',
        zodiacSign: 'Virgo',
        heightCm: 177,
        weightKg: 65,
        interests: ['playing piano'],
        position: 'Main Vocalist',
      },
      {
        memberId: 'bambam',
        birthdate: '1997-05-02',
        zodiacSign: 'Taurus',
        heightCm: 178,
        weightKg: 60,
        interests: ['listening to music'],
        favoriteFoods: ['cheeseburger', 'tom yum kung'],
        favoriteAnimal: 'Cat (owns four cats)',
        position: 'Sub-Rapper',
      },
      {
        memberId: 'yugyeom',
        birthdate: '1997-11-17',
        zodiacSign: 'Scorpio',
        heightCm: 183,
        weightKg: 68,
        interests: ['playing piano', 'street dancing (krumping, house, popping)'],
        favoriteFoods: ['samgyupsal', 'bulgogi', 'chicken', 'kimbap'],
        position: 'Main Dancer, Sub-Vocalist, Maknae',
      },
    ],
  },
  {
    artistId: 'stray-kids',
    agency: 'JYP Entertainment',
    debutDate: '2018-03-25',
    fandomName: 'STAY',
    members: [
      {
        memberId: 'bang-chan',
        birthdate: '1997-10-03',
        zodiacSign: 'Libra',
        heightCm: 171,
        interests: ['working out', 'playing sports', 'composing/producing music', 'gaming'],
        favoriteFoods: ['chicken'],
        favoriteAnimal: 'Wolf',
        position: 'Leader, Producer, Vocalist, Dancer, Rapper',
      },
      {
        memberId: 'lee-know',
        birthdate: '1998-10-25',
        zodiacSign: 'Scorpio',
        heightCm: 172,
        interests: ['dancing', 'reading books', 'painting', 'sports', 'hiking', 'choreographing', 'watching movies', 'watching anime'],
        favoriteFoods: ['mint chocolate ice cream', 'strawberry ice cream', 'ramen'],
        favoriteAnimal: 'Rabbit',
        position: 'Dance Leader, Vocalist, Rapper',
      },
      {
        memberId: 'changbin',
        birthdate: '1999-08-11',
        zodiacSign: 'Leo',
        heightCm: 167,
        interests: ['writing lyrics', 'rap/producing', 'listening to music', 'shopping'],
        favoriteFoods: ['french fries', 'chicken breast'],
        position: 'Rapper, Vocalist, Producer',
      },
      {
        memberId: 'hyunjin',
        birthdate: '2000-03-20',
        zodiacSign: 'Pisces',
        heightCm: 179,
        interests: ['dancing', 'reading books', 'playing sports', 'drawing/visual art'],
        favoriteFoods: ['sushi', 'watermelon'],
        favoriteAnimal: 'Ferret',
        position: 'Dancer, Rapper, Vocalist, Visual',
      },
      {
        memberId: 'han',
        birthdate: '2000-09-14',
        zodiacSign: 'Virgo',
        heightCm: 169,
        interests: ['playing guitar', 'drawing characters', 'watching movies'],
        favoriteFoods: ['cheesecake', 'chocolate cake'],
        favoriteAnimal: 'Quokka',
        position: 'Rapper, Vocalist, Producer',
      },
      {
        memberId: 'felix',
        birthdate: '2000-09-15',
        zodiacSign: 'Virgo',
        heightCm: 171,
        interests: ['listening to music', 'dancing', 'shopping', 'traveling', 'beatboxing'],
        favoriteFoods: ['rice cakes', 'spicy food'],
        favoriteAnimal: 'Chick',
        position: 'Dancer, Rapper, Vocalist',
      },
      {
        memberId: 'seungmin',
        birthdate: '2000-09-22',
        zodiacSign: 'Virgo',
        heightCm: 178,
        weightKg: 56,
        interests: ['writing in diary', 'listening to music', 'baseball', 'basketball'],
        favoriteFoods: ['eggs', 'oranges', 'strawberries'],
        favoriteAnimal: 'Puppy',
        position: 'Main Vocalist',
      },
      {
        memberId: 'i-n',
        birthdate: '2001-02-08',
        zodiacSign: 'Aquarius',
        heightCm: 172,
        interests: ['listening to rock/pop music', 'watching mukbang'],
        favoriteFoods: ['fried chicken', 'kalguksu with geotjeori'],
        favoriteAnimal: 'Fennec Fox',
        position: 'Lead Vocalist, Maknae',
      },
    ],
  },
  {
    artistId: 'itzy',
    agency: 'JYP Entertainment',
    debutDate: '2019-02-11',
    fandomName: 'MIDZY',
    fandomColorName: 'Magenta',
    members: [
      {
        memberId: 'yeji',
        birthdate: '2000-05-26',
        zodiacSign: 'Gemini',
        heightCm: 167,
        weightKg: 46,
        interests: ['rap', 'dance', 'singing'],
        favoriteFoods: ['snacks', 'chocolate'],
        favoriteAnimal: 'Cat',
        position: 'Leader, Main Dancer, Lead Vocalist, Sub-Rapper',
      },
      {
        memberId: 'lia',
        birthdate: '2000-07-21',
        zodiacSign: 'Cancer',
        heightCm: 162.3,
        weightKg: 43,
        interests: ['shopping', 'listening to music', 'watching dramas'],
        favoriteFoods: ['fruits', 'pasta', 'Korean and Western food'],
        favoriteAnimal: 'Sloth',
        position: 'Main Vocalist, Sub-Rapper',
      },
      {
        memberId: 'ryujin',
        birthdate: '2001-04-17',
        zodiacSign: 'Aries',
        heightCm: 164,
        weightKg: 49,
        interests: ['cooking (galbijjim)', 'watching movies', 'taking pictures'],
        favoriteFoods: ['mocha bread', 'spicy/savory food'],
        favoriteAnimal: 'Monkey',
        position: 'Main Rapper, Lead Dancer, Sub-Vocalist, Center',
      },
      {
        memberId: 'chaeryeong',
        birthdate: '2001-06-05',
        zodiacSign: 'Gemini',
        heightCm: 166,
        weightKg: 46,
        interests: ['watching movies/dramas', 'sleeping', 'eating'],
        favoriteFoods: ['chocolate'],
        favoriteAnimal: 'Fox',
        position: 'Main Dancer, Sub-Vocalist, Sub-Rapper',
      },
      {
        memberId: 'yuna',
        birthdate: '2003-12-09',
        zodiacSign: 'Sagittarius',
        heightCm: 170,
        weightKg: 46.8,
        interests: ['walking', 'shopping', 'going to restaurants', 'floorball'],
        favoriteFoods: ['pizza'],
        favoriteAnimal: 'Rabbit',
        position: 'Lead Rapper, Lead Dancer, Sub-Vocalist, Visual, Maknae',
      },
    ],
  },
  {
    artistId: 'ateez',
    agency: 'KQ Entertainment',
    debutDate: '2018-10-24',
    fandomName: 'ATINY',
    members: [
      {
        memberId: 'hongjoong',
        birthdate: '1998-11-07',
        zodiacSign: 'Scorpio',
        heightCm: 172,
        interests: ['listening to music', 'composing'],
        favoriteAnimal: 'Squirrel',
        position: 'Leader, Main Rapper, Vocalist, Composer, Center',
      },
      {
        memberId: 'seonghwa',
        birthdate: '1998-04-03',
        zodiacSign: 'Aries',
        heightCm: 178,
        weightKg: 61,
        interests: ['cleaning', 'cooking', 'watching ASMR videos', 'dramas', 'building action figures', 'playing games'],
        favoriteFoods: ['jalapeno-flavor potato chips'],
        favoriteAnimal: 'Rabbit',
        position: 'Vocalist, Rapper, Performer, Visual',
      },
      {
        memberId: 'yunho',
        birthdate: '1999-03-23',
        zodiacSign: 'Aries',
        heightCm: 186,
        interests: ['playing with members', 'gaming', 'sports', 'Harry Potter fan'],
        favoriteFoods: ['potato chips'],
        favoriteAnimal: 'Dog',
        position: 'Main Dancer, Vocalist',
      },
      {
        memberId: 'yeosang',
        birthdate: '1999-06-15',
        zodiacSign: 'Gemini',
        heightCm: 174,
        interests: ['playing video games', 'drones', 'skateboarding'],
        favoriteFoods: ['home run ball snacks'],
        position: 'Vocalist, Performer, Rapper, Visual',
      },
      {
        memberId: 'san',
        birthdate: '1999-07-10',
        zodiacSign: 'Cancer',
        heightCm: 178,
        interests: ['watching TV', 'playing games', 'reading thriller/mystery novels', 'writing poetry', 'watching mukbang'],
        favoriteFoods: ['chocolate', 'meat'],
        position: 'Main Dancer, Lead Vocalist',
      },
      {
        memberId: 'mingi',
        birthdate: '1999-08-09',
        zodiacSign: 'Leo',
        heightCm: 184,
        interests: ['sleeping', 'staying home'],
        favoriteAnimal: 'Wolf',
        position: 'Main Dancer, Main Rapper, Vocalist',
      },
      {
        memberId: 'wooyoung',
        birthdate: '1999-11-26',
        zodiacSign: 'Sagittarius',
        heightCm: 173,
        interests: ['dancing', 'listening to music', 'collecting clothes', 'gaming'],
        favoriteFoods: ['meat', 'honey butter chips'],
        favoriteAnimal: 'Fox',
        position: 'Main Dancer, Vocalist',
      },
      {
        memberId: 'jongho',
        birthdate: '2000-10-12',
        zodiacSign: 'Libra',
        heightCm: 176,
        interests: ['soccer/football', 'working out', 'listening to ballads'],
        favoriteFoods: ['ramen', 'pizza', 'steak'],
        favoriteAnimal: 'Bear',
        position: 'Main Vocalist, Maknae',
      },
    ],
  },
  {
    artistId: 'txt',
    agency: 'BIGHIT MUSIC',
    debutDate: '2019-03-04',
    fandomName: 'MOA',
    members: [
      {
        memberId: 'soobin',
        birthdate: '2000-12-05',
        zodiacSign: 'Sagittarius',
        heightCm: 186,
        weightKg: 73,
        interests: ['reading', 'listening to music'],
        favoriteFoods: ['tteokbokki', 'ice cream', 'bingsu'],
        favoriteAnimal: 'Raccoon',
        position: 'Leader',
      },
      {
        memberId: 'yeonjun',
        birthdate: '1999-09-13',
        zodiacSign: 'Virgo',
        heightCm: 181.5,
        weightKg: 65,
        interests: ['dancing', 'skating', 'eating'],
        favoriteFoods: ['apples', 'bananas', 'Americano'],
        favoriteAnimal: 'Welsh Corgi',
      },
      {
        memberId: 'beomgyu',
        birthdate: '2001-03-13',
        zodiacSign: 'Pisces',
        heightCm: 180,
        weightKg: 55,
        interests: ['playing guitar'],
        favoriteFoods: ['strawberries', 'garlic bread'],
        favoriteAnimal: 'Bear',
        position: 'Visual',
      },
      {
        memberId: 'taehyun',
        birthdate: '2002-02-05',
        zodiacSign: 'Aquarius',
        heightCm: 177,
        weightKg: 63,
        interests: ['swimming', 'football', 'photography'],
        favoriteFoods: ['sweet items', 'caramel Frappuccino'],
      },
      {
        memberId: 'hueningkai',
        birthdate: '2002-08-14',
        zodiacSign: 'Leo',
        heightCm: 183,
        weightKg: 74,
        interests: ['playing instruments (drums, guitar, piano, flute)'],
        favoriteFoods: ['seafood', 'pizza', 'pasta'],
        favoriteAnimal: 'Penguin',
        position: 'Maknae',
      },
    ],
  },
  {
    artistId: 'aespa',
    agency: 'SM Entertainment',
    debutDate: '2020-11-17',
    fandomName: 'MY',
    fandomColorName: 'Aurora',
    members: [
      {
        memberId: 'karina',
        birthdate: '2000-04-11',
        zodiacSign: 'Aries',
        heightCm: 167.8,
        weightKg: 45,
        interests: ['taekwondo (black belt)'],
        favoriteFoods: ['green tea', 'barley tea'],
        favoriteAnimal: 'Whale',
        position: 'Leader, Main Dancer, Lead Rapper, Sub-Vocalist, Visual, Center',
      },
      {
        memberId: 'giselle',
        birthdate: '2000-10-30',
        zodiacSign: 'Scorpio',
        heightCm: 163.5,
        interests: ['guitar', 'singing/choir', 'photography', 'shopping'],
        favoriteFoods: ['sweet and salty foods', 'mint chocolate + pineapple pizza', 'seaweed soup', 'caramel latte'],
        favoriteAnimal: 'Dog',
        position: 'Main Rapper, Sub-Vocalist',
      },
      {
        memberId: 'winter',
        birthdate: '2001-01-01',
        zodiacSign: 'Capricorn',
        heightCm: 164.5,
        interests: ['watching movies (action/war films)', 'roller coasters'],
        favoriteFoods: ['chocolate', 'taro smoothie', 'bean noodles', 'lasagna', 'cake', 'bread', 'cookies'],
        favoriteAnimal: 'Siberian Husky',
        position: 'Main Vocalist, Lead Dancer, Visual',
      },
      {
        memberId: 'ningning',
        birthdate: '2002-10-23',
        zodiacSign: 'Libra',
        heightCm: 161,
        weightKg: 43,
        interests: ['cooking', 'piano', 'listening to hip-hop', 'buying vintage clothing'],
        favoriteFoods: ['watermelon', 'strawberries', 'pork back-bone stew', 'sundae soup', 'hot pot', 'mint chocolate pineapple pizza'],
        favoriteAnimal: 'Tiger',
        position: 'Main Vocalist, Maknae',
      },
    ],
  },
  {
    artistId: 'enhypen',
    agency: 'BELIFT LAB',
    debutDate: '2020-11-30',
    fandomName: 'ENGENE',
    members: [
      {
        memberId: 'jungwon',
        birthdate: '2004-02-09',
        zodiacSign: 'Aquarius',
        heightCm: 174,
        interests: ['watching movies', 'walking in the rain', 'swimming', 'taekwondo'],
        favoriteFoods: ['curry'],
        favoriteAnimal: 'Dog',
        position: 'Leader',
      },
      {
        memberId: 'heeseung',
        birthdate: '2001-10-15',
        zodiacSign: 'Libra',
        heightCm: 181.5,
        weightKg: 64,
        interests: ['songwriting', 'composing'],
        favoriteAnimal: 'Hamster',
        position: 'Main Vocalist',
      },
      {
        memberId: 'jay',
        birthdate: '2002-04-20',
        zodiacSign: 'Taurus',
        heightCm: 180,
        interests: ['playing games', 'clothes shopping', 'cooking', 'fashion/clothing design', 'watching anime'],
        favoriteFoods: ['pistachio ice cream'],
      },
      {
        memberId: 'jake',
        birthdate: '2002-11-15',
        zodiacSign: 'Scorpio',
        heightCm: 176,
        interests: ['dogs/puppies', 'working out', 'hip hop', 'soccer', 'violin'],
        favoriteFoods: ['grape soda', 'chocolate ice cream'],
        favoriteAnimal: 'Dog',
      },
      {
        memberId: 'sunghoon',
        birthdate: '2002-12-08',
        zodiacSign: 'Sagittarius',
        heightCm: 181,
        interests: ['figure skating', 'fashion', 'shoes', 'coffee', 'contemporary dance'],
        favoriteFoods: ['coffee ice cream', 'samgyeopsal'],
        favoriteAnimal: 'Penguin',
        position: 'Visual',
      },
      {
        memberId: 'sunoo',
        birthdate: '2003-06-24',
        zodiacSign: 'Cancer',
        heightCm: 175,
        interests: ['taking selfies', 'listening to music', 'playing games', 'watching movies', 'photography'],
        favoriteFoods: ['tteokbokki', 'mint chocolate chip ice cream', 'spicy food'],
        favoriteAnimal: 'Desert Fox',
      },
      {
        memberId: 'ni-ki',
        birthdate: '2005-12-09',
        zodiacSign: 'Sagittarius',
        heightCm: 183,
        weightKg: 63,
        interests: ['soccer', 'dancing', 'watching movies/sports'],
        favoriteFoods: ['mint chocolate ice cream', 'dumplings', 'sushi'],
        favoriteAnimal: 'Dog',
        position: 'Main Dancer, Maknae',
      },
    ],
  },
  {
    artistId: 'ive',
    agency: 'Starship Entertainment',
    debutDate: '2021-12-01',
    fandomName: 'DIVE',
    members: [
      {
        memberId: 'yujin',
        birthdate: '2003-09-01',
        zodiacSign: 'Virgo',
        heightCm: 173,
        weightKg: 48,
        interests: ['sports', 'shopping in Gangnam', 'piano', 'hip-hop dance'],
        favoriteFoods: ['green tea ice cream'],
        position: 'Leader, Main Vocalist, Main Dancer',
      },
      {
        memberId: 'gaeul',
        birthdate: '2002-09-24',
        zodiacSign: 'Libra',
        heightCm: 164,
        weightKg: 46,
        interests: ['reading mystery novels', 'watching horror movies', 'writing rap lyrics'],
        position: 'Main Dancer, Lead Rapper, Sub-Vocalist',
      },
      {
        memberId: 'rei',
        birthdate: '2004-02-03',
        zodiacSign: 'Aquarius',
        heightCm: 170,
        interests: ['drawing', 'making jewelry', 'collecting pretty items'],
        position: 'Main Rapper, Sub-Vocalist',
      },
      {
        memberId: 'wonyoung',
        birthdate: '2004-08-31',
        zodiacSign: 'Virgo',
        heightCm: 173,
        weightKg: 47,
        interests: ['piano', 'flute', 'violin'],
        position: 'Vocalist, Dancer, Visual',
      },
      {
        memberId: 'liz',
        birthdate: '2004-11-21',
        zodiacSign: 'Scorpio',
        heightCm: 170,
        interests: ['playing sports', 'cuddling with animals', 'singing', 'playing piano'],
        favoriteAnimal: 'Cat',
        position: 'Main Vocalist',
      },
      {
        memberId: 'leeseo',
        birthdate: '2007-02-21',
        zodiacSign: 'Pisces',
        heightCm: 166,
        interests: ['swimming', 'playing piano', 'watching anime and K-dramas', 'ballet'],
        favoriteFoods: ['scones', 'cheesecake', 'chocolate cake', 'strawberry/grape candies'],
        position: 'Lead Dancer, Sub-Vocalist, Visual, Maknae',
      },
    ],
  },
  {
    artistId: 'le-sserafim',
    agency: 'Source Music',
    debutDate: '2022-05-02',
    fandomName: 'FEARNOT',
    fandomColorName: 'Fearless Blue',
    fandomColorHex: '#81A5F9',
    members: [
      {
        memberId: 'sakura',
        birthdate: '1998-03-19',
        zodiacSign: 'Pisces',
        heightCm: 163,
        weightKg: 46,
        interests: ['drawing', 'gaming', 'writing'],
        favoriteFoods: ['sushi'],
        position: 'Vocalist, Rapper, Dancer',
      },
      {
        memberId: 'kim-chaewon',
        birthdate: '2000-08-01',
        zodiacSign: 'Leo',
        heightCm: 164,
        weightKg: 42,
        interests: ['watching dramas and movies', 'studying choreography videos', 'listening to ballads'],
        favoriteFoods: ['mandarins', 'blueberries', 'mint chocolate ice cream', 'bubble tea'],
        position: 'Leader, Vocalist, Dancer',
      },
      {
        memberId: 'huh-yunjin',
        birthdate: '2001-10-08',
        zodiacSign: 'Libra',
        heightCm: 172.3,
        weightKg: 53,
        interests: ['guitar', 'piano', 'ukulele', 'watching anime', 'composing music'],
        favoriteFoods: ['roasted sweet potatoes', 'yogurt', 'seaweed', 'cheese', 'pizza'],
        position: 'Vocalist, Rapper',
      },
      {
        memberId: 'kazuha',
        birthdate: '2003-08-09',
        zodiacSign: 'Leo',
        heightCm: 169.9,
        interests: ['watching YouTube videos', 'internet shopping', 'ballet'],
        favoriteFoods: ['Hawaiian pizza'],
        position: 'Sub-Vocalist, Rapper, Dancer',
      },
      {
        memberId: 'hong-eunchae',
        birthdate: '2006-11-10',
        zodiacSign: 'Scorpio',
        heightCm: 169,
        interests: ['watching performance/stage videos', 'watching mukbang videos'],
        favoriteAnimal: 'Black cat',
        position: 'Vocalist, Lead Dancer, Maknae',
      },
    ],
  },
]
