import type { ArtistBio } from './types'

export const batch3Bios: ArtistBio[] = [
  // --- K-pop ---
  {
    artistId: 'newjeans',
    agency: 'ADOR (HYBE)',
    debutDate: '2022-07-22',
    fandomName: 'Bunnies',
    members: [
      {
        memberId: 'minji',
        birthdate: '2004-05-07',
        zodiacSign: 'Taurus',
        heightCm: 169,
        interests: ['reading mystery novels', 'going for walks', 'watching movies', 'decorating her diary'],
        favoriteFoods: ['home-cooked meals', 'rice', 'ice cream'],
        favoriteAnimal: 'Rabbit',
        position: 'Rapper',
      },
      {
        memberId: 'hanni',
        birthdate: '2004-10-06',
        zodiacSign: 'Libra',
        heightCm: 162,
        interests: ['watching movies and vlogs', 'playing ukulele, guitar and piano', 'photographing clouds', 'night walks'],
        favoriteFoods: ['bread', 'meat', 'Hawaiian pizza', 'mint chocolate', 'avocados'],
        favoriteAnimal: 'Rabbit',
        position: 'Vocalist',
      },
      {
        memberId: 'danielle',
        birthdate: '2005-04-11',
        zodiacSign: 'Aries',
        heightCm: 165,
        interests: ['drawing', 'painting', 'swimming', 'listening to music', 'camping', 'paragliding'],
        favoriteFoods: ['home-cooked meals', 'Korean food', 'vegetables', 'fruits'],
        favoriteAnimal: 'Puppy',
      },
      {
        memberId: 'haerin',
        birthdate: '2006-05-15',
        zodiacSign: 'Taurus',
        heightCm: 164.5,
        interests: ['listening to music while walking', 'collecting gifs and photos', 'reading', 'studying Japanese'],
        favoriteFoods: ['Korean food', 'raw fish', 'avocados', 'peaches', 'nuts', 'Hawaiian pizza'],
        favoriteAnimal: 'Cat',
      },
      {
        memberId: 'hyein',
        birthdate: '2008-04-21',
        zodiacSign: 'Taurus',
        heightCm: 170,
        interests: ['walking', 'sky photography', 'watching movies', 'writing in her diary'],
        favoriteFoods: ['rice soup', 'strawberries', 'strawberry cream cake', 'shaved ice'],
        favoriteAnimal: 'Puppy',
        position: 'Maknae',
      },
    ],
  },
  {
    artistId: 'gidle',
    agency: 'Cube Entertainment',
    debutDate: '2018-05-02',
    fandomName: 'Neverland',
    fandomColorName: 'Neon Red & Chic Violet',
    members: [
      {
        memberId: 'miyeon',
        birthdate: '1997-01-31',
        zodiacSign: 'Aquarius',
        heightCm: 161,
        weightKg: 45,
        interests: ['nail art', 'composing songs and writing lyrics', 'playing piano and violin'],
        favoriteFoods: ['milk tea', 'Thai food'],
        position: 'Main Vocalist',
      },
      {
        memberId: 'minnie',
        birthdate: '1997-10-23',
        zodiacSign: 'Scorpio',
        heightCm: 167,
        weightKg: 45,
        interests: ['shopping', 'photography', 'making songs on piano'],
        favoriteFoods: ['Japanese food', 'green tea'],
        position: 'Main Vocalist',
      },
      {
        memberId: 'soyeon',
        birthdate: '1998-08-26',
        zodiacSign: 'Virgo',
        heightCm: 157,
        weightKg: 44,
        interests: ['watching anime, especially One Piece'],
        favoriteFoods: ['mint chocolate', 'tangerines', 'corn'],
        position: 'Leader, Main Rapper, Sub-Vocalist, Center',
      },
      {
        memberId: 'yuqi',
        birthdate: '1999-09-23',
        zodiacSign: 'Libra',
        heightCm: 163,
        weightKg: 47,
        interests: ['rapping', 'dancing', 'playing guzheng'],
        favoriteFoods: ['pickled radish', 'hot pot', 'jokbal (pig’s feet)'],
        favoriteAnimal: 'Giraffe',
        position: 'Main Dancer, Sub-Vocalist, Sub-Rapper, Face of the Group',
      },
      {
        memberId: 'shuhua',
        birthdate: '2000-01-06',
        zodiacSign: 'Capricorn',
        heightCm: 161,
        weightKg: 45,
        interests: ['acting', 'watching dramas', 'traveling'],
        favoriteFoods: ['chocolate', 'ramen'],
        position: 'Sub-Vocalist, Visual, Maknae',
      },
    ],
  },
  {
    artistId: 'riize',
    agency: 'SM Entertainment',
    debutDate: '2023-09-04',
    fandomName: 'BRIIZE',
    members: [
      {
        memberId: 'shotaro',
        birthdate: '2000-11-25',
        zodiacSign: 'Sagittarius',
        heightCm: 178,
        weightKg: 62,
        interests: ['watching mukbangs', 'dancing', 'playing basketball'],
        favoriteFoods: ['sushi', 'cake', 'sweet foods'],
        favoriteAnimal: 'Dog',
        position: 'Dancer',
      },
      {
        memberId: 'eunseok',
        birthdate: '2001-03-19',
        zodiacSign: 'Pisces',
        heightCm: 180,
        weightKg: 57,
        interests: ['watching anime', 'reading manga', 'cooking'],
        favoriteFoods: ['creamy pasta'],
        position: 'Visual',
      },
      {
        memberId: 'sungchan',
        birthdate: '2001-09-13',
        zodiacSign: 'Virgo',
        heightCm: 185.6,
        weightKg: 75,
        interests: ['exercising', 'gaming', 'raising pets', 'soccer', 'making rap'],
        favoriteFoods: ['raw fish', 'sushi'],
        favoriteAnimal: 'Dog',
        position: 'Rapper',
      },
      {
        memberId: 'wonbin',
        birthdate: '2002-03-02',
        zodiacSign: 'Pisces',
        heightCm: 176,
        weightKg: 57,
        interests: ['shopping', 'playing guitar'],
        favoriteFoods: ['yangnyeom chicken'],
        favoriteAnimal: 'Dog',
        position: 'Vocalist, Dancer, Visual, Center',
      },
      {
        // Note: this memberId is labeled "Soobin" in the seed roster, but the
        // real RIIZE member holding this position is Sohee (Lee So-hee).
        memberId: 'soobin-riize',
        birthdate: '2003-11-21',
        zodiacSign: 'Scorpio',
        heightCm: 176,
        weightKg: 54,
        favoriteFoods: ['chocolate milk', 'strawberry milk'],
        favoriteAnimal: 'Hippo',
        position: 'Main Vocalist',
      },
      {
        memberId: 'anton',
        birthdate: '2004-03-21',
        zodiacSign: 'Aries',
        heightCm: 184,
        weightKg: 65,
        interests: ['swimming', 'playing cello', 'producing music'],
        position: 'Visual, Maknae',
      },
    ],
  },
  {
    artistId: 'babymonster',
    agency: 'YG Entertainment',
    influences: ['2NE1', 'BLACKPINK'],
    debutDate: '2023-11-27',
    fandomName: 'MONSTIEZ',
    members: [
      {
        memberId: 'ruka',
        birthdate: '2002-03-20',
        zodiacSign: 'Pisces',
        heightCm: 158,
        interests: ['hip-hop dancing', 'Pilates'],
        favoriteFoods: ['mala soup', 'ice cream'],
        position: 'Main Dancer, Main Rapper',
      },
      {
        memberId: 'asa',
        birthdate: '2006-04-17',
        zodiacSign: 'Aries',
        heightCm: 161,
        interests: ['dancing', 'cooking', 'jump rope', 'watching movies and dramas', 'drawing', 'photography'],
        favoriteFoods: ['peach', 'hamburger steak', 'vanilla ice cream', 'omurice'],
        position: 'Main Rapper, Vocalist, Dancer',
      },
      {
        memberId: 'pharita',
        birthdate: '2005-08-26',
        zodiacSign: 'Virgo',
        heightCm: 167,
        interests: ['anime', 'visiting the zoo', 'making presentations'],
        favoriteFoods: ['chocolate chip cookies'],
        favoriteAnimal: 'Giraffe',
        position: 'Vocalist',
      },
      {
        memberId: 'ahyeon',
        birthdate: '2007-04-11',
        zodiacSign: 'Aries',
        heightCm: 163,
        interests: ['drawing', 'video editing'],
        favoriteFoods: ['Korean rice porridge', 'tteokbokki', 'chocolate smoothie bubble tea'],
        position: 'Main Vocalist, Rapper, Dancer, Visual, Center',
      },
      {
        memberId: 'rora',
        birthdate: '2008-08-14',
        zodiacSign: 'Leo',
        heightCm: 167,
        interests: ['playing piano', 'cooking', 'Harry Potter fandom'],
        favoriteFoods: ['chocolate', 'chocolate ice cream'],
        favoriteAnimal: 'Cat',
        position: 'Lead Vocalist, Visual',
      },
      {
        memberId: 'rami',
        birthdate: '2007-10-17',
        zodiacSign: 'Libra',
        interests: ['climbing', 'skiing', 'badminton', 'skating'],
        position: 'Main Vocalist',
      },
      {
        memberId: 'chiquita',
        birthdate: '2009-02-17',
        zodiacSign: 'Aquarius',
        heightCm: 165,
        interests: ['playing flugelhorn', 'collecting plushies', 'taekwondo'],
        favoriteFoods: ['smoked quail eggs', 'ramen', 'pork belly'],
        position: 'Vocalist, Dancer, Rapper, Maknae',
      },
    ],
  },
  {
    artistId: 'illit',
    agency: 'Belift Lab (HYBE)',
    debutDate: '2024-03-25',
    fandomName: 'GLLIT',
    members: [
      {
        memberId: 'yunah',
        birthdate: '2004-01-15',
        zodiacSign: 'Capricorn',
        heightCm: 168,
        interests: ['riding a bicycle', 'ironing clothes', 'playing PC games'],
        favoriteFoods: ['galbi with rice', 'chocolate ice cream'],
        favoriteAnimal: 'Dog',
      },
      {
        memberId: 'minju',
        birthdate: '2004-05-11',
        zodiacSign: 'Taurus',
        heightCm: 163,
        interests: ['listening to music', 'playing games', 'playing violin'],
        favoriteFoods: ['kimchi fried rice', 'chocolate cake', 'chocolate chip cookies'],
        favoriteAnimal: 'Dog',
      },
      {
        memberId: 'moka',
        birthdate: '2004-10-08',
        zodiacSign: 'Libra',
        heightCm: 162,
        interests: ['eating', 'watching horror movies', 'dancing'],
        favoriteFoods: ['bread', 'ice cream', 'gyeranmari', 'tomatoes'],
        favoriteAnimal: 'Cat',
      },
      {
        memberId: 'wonhee',
        birthdate: '2007-06-26',
        zodiacSign: 'Cancer',
        heightCm: 162,
        interests: ['singing', 'making keychains', 'collecting Polly Pockets', 'badminton'],
        favoriteFoods: ['garlic bread', 'blueberry ice cream', 'bibimbap'],
        favoriteAnimal: 'Cat',
      },
      {
        memberId: 'iroha',
        birthdate: '2008-02-04',
        zodiacSign: 'Aquarius',
        heightCm: 158,
        interests: ['listening to music', 'dancing'],
        favoriteFoods: ['tiramisu', 'mint chocolate ice cream'],
        favoriteAnimal: 'Cat',
        position: 'Maknae',
      },
    ],
  },

  // --- J-pop ---
  {
    artistId: 'arashi',
    agency: 'STARTO ENTERTAINMENT',
    debutDate: '1999-11-03',
    members: [
      {
        memberId: 'satoshi-ohno',
        birthdate: '1980-11-26',
        zodiacSign: 'Sagittarius',
        heightCm: 166,
        weightKg: 51,
        interests: ['drawing', 'clay sculpture', 'woodcarving', 'choreography'],
        position: 'Leader',
      },
      {
        memberId: 'sho-sakurai',
        birthdate: '1982-01-25',
        zodiacSign: 'Aquarius',
        heightCm: 171,
        weightKg: 58,
        interests: ['reading newspapers', 'football', 'architecture'],
      },
      {
        memberId: 'masaki-aiba',
        birthdate: '1982-12-24',
        zodiacSign: 'Capricorn',
        heightCm: 176,
        weightKg: 58,
        interests: ['golf', 'baseball', 'basketball', 'cooking'],
        favoriteFoods: ['ramen', 'fried chicken'],
      },
      {
        memberId: 'kazunari-ninomiya',
        birthdate: '1983-06-17',
        zodiacSign: 'Gemini',
        heightCm: 168,
        weightKg: 53,
      },
      {
        memberId: 'jun-matsumoto',
        birthdate: '1983-08-30',
        zodiacSign: 'Virgo',
        heightCm: 173,
        weightKg: 58,
        interests: ['acting', 'music', 'dance', 'theater', 'photography'],
      },
    ],
  },
  {
    artistId: 'akb48',
    agency: 'DH Co., Ltd. (formerly AKS)',
    debutDate: '2005-12-08',
    members: [{ memberId: 'rotating-lineup' }],
  },
  {
    artistId: 'perfume',
    agency: 'Amuse Inc.',
    influences: ['1980s synthpop'],
    debutDate: '2005-09-21',
    fandomName: 'P.T.A.',
    members: [
      {
        memberId: 'a-chan',
        birthdate: '1989-02-15',
        zodiacSign: 'Aquarius',
        heightCm: 160,
        interests: ['make-up', 'Korean dramas', 'skating', 'short-distance running'],
        favoriteFoods: ['fruits', 'ice cream'],
      },
      {
        memberId: 'kashiyuka',
        birthdate: '1988-12-23',
        zodiacSign: 'Capricorn',
        heightCm: 160,
        interests: ['music', 'books', 'walking', 'sleeping'],
        favoriteFoods: ['Salisbury steak', 'matcha milk', 'strawberry milk', 'ice cream'],
      },
      {
        memberId: 'nocchi',
        birthdate: '1988-09-20',
        zodiacSign: 'Virgo',
        heightCm: 161,
        interests: ['music', 'manga', 'concert DVDs', 'soccer', 'badminton'],
        favoriteFoods: ['curry', 'green tea', 'milk tea'],
      },
    ],
  },
  {
    artistId: 'babymetal',
    agency: 'Amuse Inc.',
    debutDate: '2010-11-28',
    fandomName: 'THE ONE',
    members: [
      {
        memberId: 'su-metal',
        birthdate: '1997-12-20',
        zodiacSign: 'Sagittarius',
        interests: ['collecting books and stationery'],
        position: 'Lead Vocalist, Center',
      },
      {
        memberId: 'moametal',
        birthdate: '1999-07-04',
        zodiacSign: 'Cancer',
        interests: ['playing guitar', 'sports'],
        favoriteFoods: ['umeboshi', 'fried nankotsu (chicken cartilage)'],
        position: 'Vocals, Dance',
      },
    ],
  },
  {
    artistId: 'yoasobi',
    agency: 'Sony Music Japan (Echoes)',
    debutDate: '2019-11-16',
    fandomName: "Yoa's",
    members: [
      {
        memberId: 'ayase',
        birthdate: '1994-04-04',
        zodiacSign: 'Aries',
        position: 'Composer, Producer',
      },
      {
        memberId: 'ikura',
        birthdate: '2000-09-25',
        zodiacSign: 'Libra',
        position: 'Vocalist',
      },
    ],
  },

  // --- C-pop ---
  {
    artistId: 'jay-chou',
    agency: 'JVR Music',
    influences: ['Frédéric Chopin', 'Michael Jackson'],
    debutDate: '2000-11-07',
    fandomName: 'Jiemi (杰迷)',
    members: [
      {
        memberId: 'jay-chou',
        birthdate: '1979-01-18',
        zodiacSign: 'Capricorn',
        interests: ['basketball', 'magic', 'collecting antiques and cars', 'video games', 'martial arts'],
        favoriteFoods: ['fried chicken'],
      },
    ],
  },
  {
    artistId: 'faye-wong',
    agency: 'EMI / Sony Music (historical labels; no current active label)',
    influences: ['Cocteau Twins', 'The Cranberries', 'Tori Amos', 'Miyuki Nakajima'],
    debutDate: '1989-11-02',
    fandomName: 'Feimi (菲迷)',
    members: [
      {
        memberId: 'faye-wong',
        birthdate: '1969-08-08',
        zodiacSign: 'Leo',
        interests: ['Buddhism', 'fashion', 'museums and cafes', 'charity work'],
      },
    ],
  },
  {
    artistId: 'gem',
    agency: 'G-Nation Ltd. (self-founded; distributed via Warner Music China)',
    influences: ['Whitney Houston', 'Beyoncé', 'Christina Aguilera', 'Mariah Carey'],
    debutDate: '2008-10-15',
    fandomName: 'Qishi (棋士)',
    members: [
      {
        memberId: 'gem',
        birthdate: '1991-08-16',
        zodiacSign: 'Leo',
        interests: ['playing piano', 'playing guitar', 'playing drums'],
        favoriteFoods: ['fried chicken', 'bubble tea'],
      },
    ],
  },
]
