import type { ArtistBio } from './types'

export const batch7Bios: ArtistBio[] = [
  {
    artistId: 'staych',
    agency: 'High Up Entertainment',
    debutDate: '2020-11-12',
    fandomName: 'SWITH',
    members: [
      { memberId: 'sumin', birthdate: '2001-03-13', zodiacSign: 'Pisces', heightCm: 159, interests: ['polaroid photography', 'eating corn', 'watching webtoons', 'listening to music', 'reading', 'playing video games'], favoriteAnimal: 'bunny', position: 'Vocalist' },
      { memberId: 'sieun', birthdate: '2001-08-01', zodiacSign: 'Leo', heightCm: 159, weightKg: 44, interests: ['playing piano'], position: 'Main Vocalist' },
      { memberId: 'isa', birthdate: '2002-01-23', zodiacSign: 'Aquarius', heightCm: 165, interests: ['searching for good restaurants', 'shopping', 'finding new places', 'interested in clothes and decorating'], favoriteAnimal: 'squirrel', position: 'Lead Vocalist' },
      { memberId: 'seeun', birthdate: '2003-06-14', zodiacSign: 'Gemini', heightCm: 167, weightKg: 48, interests: ['listening to music', 'making miniature houses', 'collecting stickers', 'playing flute', 'running'], favoriteFoods: ['mint-choco ice cream'], favoriteAnimal: 'desert fox', position: 'Vocalist' },
      { memberId: 'yoon', birthdate: '2004-04-14', zodiacSign: 'Aries', heightCm: 172.6, weightKg: 49, interests: ['exploring places'], favoriteFoods: ['steamed eggs'], position: 'Lead Vocalist' },
      { memberId: 'j-staych', birthdate: '2004-12-09', zodiacSign: 'Sagittarius', heightCm: 169, interests: ['drawing', 'exercising', 'sports'], favoriteAnimal: 'Formosan deer', position: 'Vocalist, Maknae' },
    ],
  },
  {
    artistId: 'treasure',
    agency: 'YG Entertainment',
    debutDate: '2020-08-07',
    fandomName: 'TREASURE MAKER',
    fandomColorName: 'Sky Blue',
    members: [
      { memberId: 'choi-hyunsuk', birthdate: '1999-04-21', zodiacSign: 'Taurus', heightCm: 171, weightKg: 58, interests: ['music composing and production', 'collecting lip balms and football jerseys', 'watching soccer highlights'], favoriteFoods: ['burgers', 'iced Americano'], position: 'Main Dancer, Main Rapper, Vocalist' },
      { memberId: 'jihoon', birthdate: '2000-03-14', zodiacSign: 'Pisces', heightCm: 178, weightKg: 69, interests: ['observing objects and scenery', 'surfing'], favoriteFoods: ['mint chocolate'], position: 'Main Dancer, Lead Vocalist' },
      { memberId: 'yoshi', birthdate: '2000-05-15', zodiacSign: 'Taurus', heightCm: 179, weightKg: 59, interests: ['skateboarding', 'graffiti', 'watching anime', 'beatboxing', 'songwriting'], favoriteFoods: ['steak', 'seasoned fried chicken'], position: 'Main Rapper' },
      { memberId: 'junkyu', birthdate: '2000-09-09', zodiacSign: 'Virgo', heightCm: 178, weightKg: 65, interests: ['listening to music', 'gaming', 'anime'], favoriteFoods: ['dakgangjeong'], favoriteAnimal: 'koala', position: 'Vocalist, Visual' },
      { memberId: 'mashiho', birthdate: '2001-03-25', zodiacSign: 'Aries', heightCm: 169, weightKg: 59, interests: ['golf', 'drumming', 'photography'], position: 'Main Dancer, Vocalist' },
      { memberId: 'jaehyuk', birthdate: '2001-07-23', zodiacSign: 'Leo', heightCm: 178, weightKg: 63, interests: ['reading webtoons', 'watching cooking videos', 'playing games', 'listening to music'], favoriteFoods: ['gummy bear jellies'], position: 'Vocalist' },
      { memberId: 'yedam', birthdate: '2002-05-07', zodiacSign: 'Taurus', heightCm: 172, weightKg: 61, interests: ['soccer', 'photographing flowers', 'reading', 'watching movies', 'composing'], favoriteFoods: ['chocolate cornet bread'], position: 'Main Vocalist' },
      { memberId: 'doyoung-treasure', birthdate: '2003-12-04', zodiacSign: 'Sagittarius', heightCm: 177, weightKg: 58, interests: ['skateboarding', 'swimming', 'basketball', 'playing piano', 'songwriting', 'fashion'], favoriteFoods: ['burgers', 'egg tart', 'mint chocolate'], position: 'Main Dancer, Vocalist' },
      { memberId: 'haruto', birthdate: '2004-04-05', zodiacSign: 'Aries', heightCm: 183.2, weightKg: 68, interests: ['playing games', 'working on music', 'freestyle dancing', 'beatboxing'], favoriteFoods: ['chocolate ice cream'], position: 'Leader, Main Rapper, Visual' },
      { memberId: 'asahi', birthdate: '2001-08-20', zodiacSign: 'Leo', heightCm: 172, weightKg: 53, interests: ['drawing', 'composing', 'playing soccer'], favoriteFoods: ['ramen', 'sushi'], position: 'Vocalist, Visual' },
    ],
  },
  {
    artistId: 'momoiro-clover-z',
    agency: 'Stardust Promotion',
    debutDate: '2009-08-05',
    fandomName: 'Mononofu',
    members: [
      { memberId: 'kanako', birthdate: '1994-07-12', zodiacSign: 'Cancer', heightCm: 156, weightKg: 36, interests: ['watching DVDs', 'dancing', 'basketball', 'gymnastics'], position: 'Leader, Vocalist, Dancer' },
      { memberId: 'shiori', birthdate: '1995-06-04', zodiacSign: 'Gemini', heightCm: 160, weightKg: 33, interests: ['playing Nintendo DS'] },
      { memberId: 'ayaka', birthdate: '1996-06-11', zodiacSign: 'Gemini', heightCm: 160, weightKg: 41.1, interests: ['skiing', 'cooking', 'music', 'fashion', 'making dumplings', 'hair braiding'] },
      { memberId: 'momoka', birthdate: '1995-03-15', zodiacSign: 'Pisces', heightCm: 148, interests: ['singing in the bathtub', 'dance'] },
    ],
  },
  {
    artistId: 'sixtones',
    agency: 'STARTO ENTERTAINMENT',
    debutDate: '2020-01-22',
    members: [
      { memberId: 'jesse', birthdate: '1996-06-11', zodiacSign: 'Gemini', heightCm: 181, weightKg: 60.5 },
      { memberId: 'shintaro', birthdate: '1997-07-15', zodiacSign: 'Cancer', heightCm: 173, interests: ['soccer', 'reading manga', 'video games'], favoriteFoods: ['salmon sushi'] },
      { memberId: 'juri', birthdate: '1995-06-15', zodiacSign: 'Gemini', heightCm: 175, interests: ['dance', 'reading'], favoriteFoods: ['natto', 'rice', 'fried shrimp', 'beef tongue'] },
      { memberId: 'taiga', birthdate: '1994-12-03', zodiacSign: 'Sagittarius', heightCm: 174, interests: ['dance'], favoriteFoods: ['miso ramen', 'tomatoes'] },
      { memberId: 'koki', birthdate: '1994-03-08', zodiacSign: 'Pisces', heightCm: 173, interests: ['basketball', 'tennis', 'running around outside', 'shopping for clothes'], favoriteFoods: ['omurice', 'strawberries'] },
      { memberId: 'hokuto', birthdate: '1995-06-18', zodiacSign: 'Gemini', heightCm: 176, interests: ['reading manga'], favoriteFoods: ['pasta', 'rice', 'ice cream'] },
    ],
  },
  {
    artistId: 'snowman',
    agency: 'STARTO ENTERTAINMENT',
    debutDate: '2020-01-22',
    members: [
      { memberId: 'iwamoto', birthdate: '1993-05-17', zodiacSign: 'Taurus', heightCm: 182, interests: ['acrobatics'], favoriteFoods: ['chocolate', 'mandarin oranges'], favoriteAnimal: 'cheetah', position: 'Leader, Vocalist, Rapper' },
      { memberId: 'fukazawa', birthdate: '1992-05-05', zodiacSign: 'Taurus', heightCm: 175, interests: ['observing people', 'taking care of children'], favoriteFoods: ['sushi', 'natto'], position: 'Vice Leader, Vocalist' },
      { memberId: 'abe', birthdate: '1993-11-27', zodiacSign: 'Sagittarius', heightCm: 178, interests: ['tap dance', 'playing guitar', 'soccer'], favoriteFoods: ['katsudon', 'ice cream', 'cheesecake'] },
      { memberId: 'sakuma', birthdate: '1992-07-05', zodiacSign: 'Cancer', heightCm: 168, interests: ['making accessories', 'dance'], favoriteFoods: ['dried tofu', 'sea grapes', 'tomato dishes'] },
      { memberId: 'watanabe', birthdate: '1992-11-05', zodiacSign: 'Scorpio', heightCm: 172, favoriteFoods: ['omelette', 'goumi', 'yakiniku'], favoriteAnimal: 'dog' },
      { memberId: 'muto', birthdate: '1994-06-21', zodiacSign: 'Cancer', interests: ['music', 'Thai boxing'], favoriteFoods: ['Chinese fried noodles'] },
      { memberId: 'raul', birthdate: '2003-06-27', zodiacSign: 'Cancer', heightCm: 192, position: 'Center, Vocalist' },
      { memberId: 'meguro', birthdate: '1997-02-16', zodiacSign: 'Aquarius', heightCm: 185 },
      { memberId: 'ozeki', birthdate: '1993-03-25', zodiacSign: 'Aries', heightCm: 174, interests: ['reading manga', 'dance', 'acrobatics'], favoriteFoods: ['strawberries', 'meat', 'pineapple'], favoriteAnimal: 'dog' },
    ],
  },
  {
    artistId: 'kanjani8',
    agency: 'STARTO ENTERTAINMENT',
    debutDate: '2004-09-22',
    fandomName: 'Eighter',
    members: [
      { memberId: 'murakami', birthdate: '1982-01-26', zodiacSign: 'Aquarius', heightCm: 170, weightKg: 58, favoriteFoods: ['rice', 'noodles'] },
      { memberId: 'maruyama', birthdate: '1983-11-26', zodiacSign: 'Sagittarius', heightCm: 175, weightKg: 65, favoriteFoods: ['sweets'] },
      { memberId: 'yokoyama', birthdate: '1981-05-09', zodiacSign: 'Taurus', heightCm: 176, weightKg: 63, interests: ['collecting manga', 'reading manga', 'video games'] },
      { memberId: 'shibutani', birthdate: '1981-09-22', zodiacSign: 'Virgo', heightCm: 170, interests: ['collecting hats'] },
      { memberId: 'yasuda', birthdate: '1984-09-11', zodiacSign: 'Virgo', heightCm: 164.5, weightKg: 56, favoriteFoods: ['curry'] },
    ],
  },
  {
    artistId: 'nogizaka46',
    agency: 'Nogizaka46 LLC',
    debutDate: '2012-02-22',
    members: [],
  },
  {
    artistId: 'sakurazaka46',
    agency: 'Seed & Flower LLC',
    debutDate: '2020-10-14',
    fandomName: 'Buddies',
    members: [],
  },
  {
    artistId: 'nmixx',
    agency: 'JYP Entertainment',
    debutDate: '2022-02-22',
    fandomName: 'NSWER',
    members: [
      { memberId: 'lily', birthdate: '2002-10-17', zodiacSign: 'Libra', heightCm: 163, interests: ['reading', 'listening to music', 'watching YouTube videos'], favoriteFoods: ['potato chips', 'mint chocolate chip ice cream'], position: 'Main Vocalist' },
      { memberId: 'haewon', birthdate: '2003-02-25', zodiacSign: 'Pisces', heightCm: 163, position: 'Leader, Main Vocalist' },
      { memberId: 'sullyoon', birthdate: '2004-01-26', zodiacSign: 'Aquarius', heightCm: 167, interests: ['dancing', 'baking', 'listening to music', 'drawing'], favoriteFoods: ['peaches', 'ice cream', 'chocolate'], position: 'Lead Vocalist, Dancer' },
      { memberId: 'bae', birthdate: '2004-12-28', zodiacSign: 'Capricorn', heightCm: 170, interests: ['collecting berets', 'taekwondo'], favoriteFoods: ['pistachio ice cream', 'persimmons'], position: 'Lead Vocalist, Dancer' },
      { memberId: 'jiwoo-nmixx', birthdate: '2005-04-13', zodiacSign: 'Aries', heightCm: 161, interests: ['listening to music', 'nail art', 'making perfumes'], favoriteFoods: ['ham kimchi stew'], position: 'Main Rapper, Vocalist, Dancer' },
      { memberId: 'kyujin', birthdate: '2006-05-26', zodiacSign: 'Gemini', heightCm: 164, interests: ['calligraphy'], favoriteFoods: ['mackerel', 'salmon'], position: 'Dance Leader, Main Dancer, Rapper, Vocalist, Maknae' },
    ],
  },
  {
    artistId: 'oneus',
    agency: 'B-Wave Entertainment (formerly RBW)',
    debutDate: '2019-01-09',
    fandomName: 'TO MOON',
    members: [
      { memberId: 'seoho', birthdate: '1996-06-07', zodiacSign: 'Gemini', heightCm: 176, weightKg: 63, interests: ['football', 'basketball', 'working out'], favoriteFoods: ['fruit cake'], position: 'Main Vocalist' },
      { memberId: 'leedo', birthdate: '1997-07-26', zodiacSign: 'Leo', heightCm: 178, weightKg: 67, interests: ['exercise', 'cooking', 'boxing', 'aikido', 'kendo'], favoriteFoods: ['pork belly', 'rainbow sherbet ice cream'], favoriteAnimal: 'dog', position: 'Main Rapper, Sub-Vocalist' },
      { memberId: 'keonhee', birthdate: '1998-06-27', zodiacSign: 'Cancer', heightCm: 181, weightKg: 64, interests: ['viewing art', 'playing piano'], position: 'Main Vocalist' },
      { memberId: 'hwanwoong', birthdate: '1998-08-26', zodiacSign: 'Virgo', heightCm: 168, weightKg: 57, favoriteFoods: ['bubble tea', 'samgyeopsal'], position: 'Main Dancer, Sub-Vocalist' },
      { memberId: 'xion', birthdate: '2000-01-10', zodiacSign: 'Capricorn', heightCm: 173, weightKg: 56, interests: ['watching dramas and movies', 'cooking'], favoriteFoods: ['pork belly', 'chicken'], favoriteAnimal: 'dog', position: 'Sub-Vocalist, Visual, Maknae' },
    ],
  },
  {
    artistId: 'p1harmony',
    agency: 'FNC Entertainment',
    debutDate: '2020-10-28',
    fandomName: 'P1ece',
    members: [
      { memberId: 'keeho', birthdate: '2001-09-27', zodiacSign: 'Libra', heightCm: 179, interests: ['photography', 'sketching'], favoriteFoods: ['steak'], position: 'Leader, Vocalist' },
      { memberId: 'theo', birthdate: '2001-07-01', zodiacSign: 'Cancer', heightCm: 181, interests: ['fishing', 'volleyball', 'baseball'], favoriteFoods: ['hamburgers'], position: 'Vocalist' },
      { memberId: 'jiung', birthdate: '2001-10-07', zodiacSign: 'Libra', heightCm: 178, interests: ['fashion', 'camping', 'travel', 'home design'], favoriteFoods: ['rosé pasta', 'garlic bread', 'potatoes'], position: 'Rapper, Vocalist, Dancer' },
      { memberId: 'intak', birthdate: '2003-08-31', zodiacSign: 'Virgo', heightCm: 182, weightKg: 69, interests: ['football', 'fashion', 'lyric writing'], favoriteFoods: ['bread', 'meat', 'desserts'], position: 'Rapper, Dancer' },
      { memberId: 'soul', birthdate: '2005-02-01', zodiacSign: 'Aquarius', heightCm: 177, interests: ['playing games', 'collecting sneakers', 'choreography'], favoriteFoods: ['kimchi stew', 'sushi'], position: 'Rapper, Dancer' },
      { memberId: 'jongseob', birthdate: '2005-11-19', zodiacSign: 'Scorpio', heightCm: 177, interests: ['playing games', 'biking', 'skateboarding', 'songwriting'], favoriteFoods: ['yogurt ice cream'], favoriteAnimal: 'cat', position: 'Rapper, Dancer, Maknae' },
    ],
  },
  {
    artistId: 'kissoflife',
    agency: 'S2 Entertainment',
    debutDate: '2023-07-05',
    fandomName: 'KISSY',
    members: [
      { memberId: 'julie', birthdate: '2000-03-29', zodiacSign: 'Aries', heightCm: 163, interests: ['reading', 'movies', 'shopping', 'dancing', 'ballet'], position: 'Leader, Main Rapper, Lead Dancer' },
      { memberId: 'natty', birthdate: '2002-05-30', zodiacSign: 'Gemini', heightCm: 167, weightKg: 46, interests: ['dance'], position: 'Main Dancer, Lead Rapper, Sub-Vocalist' },
      { memberId: 'belle', birthdate: '2004-03-20', zodiacSign: 'Pisces', heightCm: 168, interests: ['shopping', 'cross-stitching jewelry', 'making bracelets', 'songwriting'], favoriteFoods: ['mint chocolate'], position: 'Main Vocalist' },
      { memberId: 'haneul', birthdate: '2005-05-25', zodiacSign: 'Gemini', heightCm: 169, interests: ['watching movies and dramas', 'traveling', 'driving', 'guitar', 'table tennis', 'badminton'], favoriteFoods: ['sweet and spicy foods', 'meat'], position: 'Lead Vocalist, Maknae' },
    ],
  },
  {
    artistId: 'hearts2hearts',
    agency: 'SM Entertainment',
    debutDate: '2025-02-24',
    fandomName: 'S2U',
    fandomColorName: 'Sky Blue',
    members: [
      { memberId: 'jiwoo-h2h', birthdate: '2006-09-07', zodiacSign: 'Virgo', heightCm: 169, interests: ['watching cartoons', 'traveling', 'juggling', 'ballet'], favoriteFoods: ['kimchi stew', 'strawberry gelato', 'strawberries'], position: 'Leader, Dancer, Rapper, Vocalist, Visual' },
      { memberId: 'carmen', birthdate: '2006-03-28', zodiacSign: 'Aries', heightCm: 168, interests: ['piano', 'guitar', 'drums', 'violin'], favoriteFoods: ['ice cream'], position: 'Vocalist' },
      { memberId: 'yuha', birthdate: '2007-04-12', zodiacSign: 'Aries', heightCm: 164, position: 'Vocalist, Dancer' },
      { memberId: 'stella', birthdate: '2007-06-18', zodiacSign: 'Gemini', heightCm: 167, interests: ['taekwondo', 'desserts'], position: 'Vocalist' },
      { memberId: 'juun', birthdate: '2008-12-03', zodiacSign: 'Sagittarius', heightCm: 166, favoriteFoods: ['ice cream', 'watermelon'], position: 'Main Dancer, Rapper, Vocalist' },
      { memberId: 'a-na', birthdate: '2008-12-20', zodiacSign: 'Sagittarius', heightCm: 171, interests: ['shopping for clothes', 'anime'], position: 'Rapper, Vocalist, Visual' },
      { memberId: 'ian', birthdate: '2009-10-09', zodiacSign: 'Libra', heightCm: 164, interests: ['collecting perfumes'], favoriteAnimal: 'cat', position: 'Dancer, Vocalist, Visual, Center' },
      { memberId: 'ye-on', birthdate: '2010-04-19', zodiacSign: 'Aries', heightCm: 166, interests: ['singing', 'musicals'], favoriteAnimal: 'cat', position: 'Vocalist, Maknae' },
    ],
  },
]
