import type { ArtistBio } from './types'

export const batch4Bios: ArtistBio[] = [
  {
    artistId: 'mayday',
    agency: "B'in Music",
    influences: ['The Beatles', 'U2', 'Oasis', 'Mr. Children'],
    debutDate: '1999-07-07',
    fandomName: 'Wumi (五迷)',
    members: [
      { memberId: 'ashin', birthdate: '1975-12-06', zodiacSign: 'Sagittarius', heightCm: 180, weightKg: 74, position: 'Lead Vocalist' },
      { memberId: 'monster', birthdate: '1976-11-28', zodiacSign: 'Sagittarius', heightCm: 168, weightKg: 62, position: 'Leader, Lead Guitarist' },
      { memberId: 'stone', birthdate: '1975-12-11', zodiacSign: 'Sagittarius', heightCm: 172, weightKg: 67, position: 'Rhythm Guitarist' },
      { memberId: 'masa', birthdate: '1977-04-25', zodiacSign: 'Taurus', heightCm: 172, weightKg: 66, interests: ['collecting records and books', 'coffee'], position: 'Bassist' },
      { memberId: 'guanyou', birthdate: '1973-07-28', zodiacSign: 'Leo', heightCm: 178, weightKg: 60, interests: ['jazz piano', 'entrepreneurship'], position: 'Drummer' },
    ],
  },
  {
    artistId: 'tfboys',
    agency: 'Time Fengjun Entertainment',
    debutDate: '2013-08-06',
    fandomName: 'Four Leaf Clover (Clovers)',
    fandomColorName: 'Orange',
    members: [
      {
        memberId: 'wang-junkai',
        birthdate: '1999-09-21',
        zodiacSign: 'Virgo',
        heightCm: 182,
        weightKg: 51,
        interests: ['One Piece anime', 'travel'],
        favoriteFoods: ['Chongqing noodles', 'watermelon'],
        favoriteAnimal: 'panda',
        position: 'Leader, Vocalist, Rapper',
      },
      {
        memberId: 'wang-yuan',
        birthdate: '2000-11-08',
        zodiacSign: 'Scorpio',
        interests: ['singing', 'piano', 'cycling', 'fishing'],
        favoriteFoods: ['snacks', 'meat dishes', 'noodles'],
        position: 'Vocalist',
      },
      {
        memberId: 'jackson-yee',
        birthdate: '2000-11-28',
        zodiacSign: 'Sagittarius',
        interests: ['dance', 'taekwondo', 'magic', 'calligraphy', 'musical instruments'],
        position: 'Main Dancer, Vocalist',
      },
    ],
  },
  {
    artistId: 'finkl',
    agency: 'DSP Media',
    debutDate: '1998-05-20',
    fandomName: 'Pinky',
    fandomColorName: 'Red',
    members: [
      {
        memberId: 'lee-hyori',
        birthdate: '1979-05-10',
        zodiacSign: 'Taurus',
        heightCm: 167,
        weightKg: 49,
        interests: ['drawing', 'acting'],
        favoriteFoods: ['chocolate covered cookies'],
        position: 'Leader, Lead Vocalist, Face of the Group',
      },
      {
        memberId: 'ok-joohyun',
        birthdate: '1980-03-20',
        zodiacSign: 'Pisces',
        heightCm: 173,
        weightKg: 54,
        interests: ['listening to music', 'photography'],
        favoriteFoods: ['pizza', 'spaghetti'],
        position: 'Main Vocalist',
      },
      {
        memberId: 'sung-yuri',
        birthdate: '1981-03-03',
        zodiacSign: 'Pisces',
        heightCm: 168,
        weightKg: 45,
        interests: ['music', 'piano', 'sleeping'],
        favoriteFoods: ['pizza'],
        position: 'Vocalist, Visual, Maknae',
      },
      {
        memberId: 'lee-jiyeon',
        birthdate: '1980-03-21',
        zodiacSign: 'Pisces',
        heightCm: 167,
        weightKg: 46,
        interests: ['music', 'films'],
        favoriteFoods: ['jjajangmyeon'],
        position: 'Vocalist',
      },
    ],
  },
  {
    artistId: 'god',
    agency: 'SidusHQ',
    debutDate: '1999-01-13',
    fandomName: 'Fan God',
    fandomColorName: 'Sky Blue',
    members: [
      { memberId: 'park-joonhyung', birthdate: '1969-07-20', zodiacSign: 'Cancer', heightCm: 181, weightKg: 68, interests: ['surfing', 'skateboarding', 'snowboarding', 'martial arts'], position: 'Leader, Rapper' },
      { memberId: 'yoon-kyesang', birthdate: '1978-12-20', zodiacSign: 'Sagittarius', heightCm: 183, weightKg: 62, interests: ['computer games', 'music', 'movies', 'repairing items'], position: 'Vocalist' },
      { memberId: 'son-hoyoung', birthdate: '1980-03-26', zodiacSign: 'Aries', heightCm: 175, weightKg: 74, interests: ['skiing', 'basketball', 'movies'], position: 'Rapper, Vocalist' },
      { memberId: 'kim-taewoo', birthdate: '1981-05-12', zodiacSign: 'Taurus', heightCm: 190, weightKg: 85, interests: ['music', 'movies', 'dancing'], position: 'Vocalist, Maknae' },
      { memberId: 'danny-ahn', birthdate: '1978-12-22', zodiacSign: 'Capricorn', heightCm: 181, weightKg: 73, interests: ['music', 'skiing', 'car tuning', 'driving', 'reading comics'], position: 'Rapper' },
    ],
  },
  {
    artistId: 'babyvox',
    agency: 'DR Music',
    debutDate: '1997-07-10',
    fandomName: 'Baby Angels',
    fandomColorName: 'Pearl Baby Pink',
    members: [
      { memberId: 'yoon-eunhye', birthdate: '1984-10-03', zodiacSign: 'Libra', heightCm: 168, weightKg: 50, position: 'Sub-Vocalist, Maknae' },
      { memberId: 'kan-miyeon', birthdate: '1982-02-02', zodiacSign: 'Aquarius', heightCm: 169, weightKg: 47, position: 'Main Vocalist, Visual' },
      { memberId: 'sim-eunjin', birthdate: '1981-02-06', zodiacSign: 'Aquarius', heightCm: 168, weightKg: 48, interests: ['fashion', 'art'], position: 'Lead Vocalist, Lead Dancer' },
    ],
  },
  {
    artistId: '2pm',
    agency: 'JYP Entertainment',
    debutDate: '2008-09-04',
    fandomName: 'Hottest',
    fandomColorName: 'Metallic Grey',
    members: [
      { memberId: 'jang-wooyoung', birthdate: '1989-04-30', zodiacSign: 'Taurus', heightCm: 178, weightKg: 65, interests: ['appreciating music', 'browsing the web'], favoriteFoods: ['chicken'], position: 'Main Dancer, Lead Vocalist' },
      { memberId: 'lee-junho', birthdate: '1990-01-25', zodiacSign: 'Aquarius', heightCm: 178, weightKg: 67, interests: ['animal rights activism'], position: 'Main Vocalist, Lead Dancer' },
      { memberId: 'nichkhun', birthdate: '1988-06-24', zodiacSign: 'Cancer', heightCm: 181, weightKg: 64, interests: ['playing piano', 'playing guitar'], position: 'Vocalist, Rapper, Visual' },
      { memberId: 'ok-taecyeon', birthdate: '1988-12-27', zodiacSign: 'Capricorn', heightCm: 186, weightKg: 76, interests: ['sleeping'], position: 'Main Rapper, Sub-Vocalist' },
      { memberId: 'hwang-chansung', birthdate: '1990-02-11', zodiacSign: 'Aquarius', heightCm: 184, weightKg: 75, interests: ['listening to music', 'gaming', 'working out', 'reading books'], position: 'Lead Rapper, Vocalist, Maknae' },
    ],
  },
  {
    artistId: '4minute',
    agency: 'Cube Entertainment',
    debutDate: '2009-06-15',
    fandomName: '4NIA',
    fandomColorName: 'Pearl Purple',
    members: [
      { memberId: 'nam-jihyun', birthdate: '1990-01-09', zodiacSign: 'Capricorn', heightCm: 167, weightKg: 49, interests: ['perfumes', 'collecting Hello Kitty and Mickey Mouse items'], position: 'Leader, Lead Dancer, Vocalist, Visual' },
      { memberId: 'heo-gayoon', birthdate: '1990-05-18', zodiacSign: 'Taurus', heightCm: 165, weightKg: 47, interests: ['writing', 'watching movies', 'singing', 'shopping'], position: 'Main Vocalist' },
      { memberId: 'jeon-jiyoon', birthdate: '1990-10-15', zodiacSign: 'Libra', heightCm: 165, weightKg: 47, interests: ['singing', 'dancing', 'cooking', 'writing lyrics'], favoriteFoods: ['Pocky'], favoriteAnimal: 'harp seal', position: 'Lead Rapper, Lead Vocalist' },
      { memberId: 'kim-hyuna', birthdate: '1992-06-06', zodiacSign: 'Gemini', heightCm: 164, interests: ['cooking', 'watching movies', 'photography', 'taking selfies'], favoriteAnimal: 'harp seal', position: 'Main Dancer, Main Rapper, Vocalist' },
      { memberId: 'gwon-sohyun', birthdate: '1994-08-30', zodiacSign: 'Virgo', heightCm: 162, weightKg: 45, interests: ['swimming', 'shopping', 'interior design', 'piano'], position: 'Lead Dancer, Vocalist, Rapper, Maknae' },
    ],
  },
  {
    artistId: 'after-school',
    agency: 'Pledis Entertainment',
    influences: ['The Pussycat Dolls'],
    debutDate: '2009-01-15',
    fandomName: 'Play Girlz / Play Boyz',
    fandomColorName: 'Pearl Metal Periwinkle',
    members: [
      { memberId: 'kahi', birthdate: '1980-12-25', zodiacSign: 'Capricorn', heightCm: 168, weightKg: 50, position: 'Leader, Lead Vocalist, Main Rapper, Main Dancer, Center' },
      { memberId: 'kim-jungah', birthdate: '1983-08-02', zodiacSign: 'Leo', heightCm: 167, weightKg: 49, position: 'Leader, Main Vocalist, Lead Dancer' },
      { memberId: 'uee', birthdate: '1988-04-09', zodiacSign: 'Aries', heightCm: 173, weightKg: 50, position: 'Main Dancer, Rapper, Vocalist, Visual' },
      { memberId: 'lizzy', birthdate: '1992-07-31', zodiacSign: 'Leo', heightCm: 168, weightKg: 46, interests: ['listening to music', 'playing Nintendo DS games', 'arts and crafts'], position: 'Main Rapper, Lead Vocalist' },
      { memberId: 'nana', birthdate: '1991-09-14', zodiacSign: 'Virgo', heightCm: 171, weightKg: 48, interests: ['singing', 'dancing'], position: 'Main Dancer, Lead Rapper, Vocalist, Visual' },
    ],
  },
  {
    artistId: 'brown-eyed-girls',
    agency: 'Mystic Entertainment',
    debutDate: '2006-03-02',
    fandomName: 'Everlasting',
    fandomColorName: 'Yellow & Black',
    members: [
      { memberId: 'jea', birthdate: '1981-09-18', zodiacSign: 'Virgo', heightCm: 158.9, weightKg: 46, interests: ['watching movies', 'playing piano'], favoriteFoods: ['Mexican food'], position: 'Leader, Main Vocalist' },
      { memberId: 'miryo', birthdate: '1981-11-02', zodiacSign: 'Scorpio', heightCm: 163, weightKg: 45, interests: ['listening to music', 'playing guitar', 'video games'], position: 'Main Rapper, Vocalist' },
      { memberId: 'narsha', birthdate: '1981-12-28', zodiacSign: 'Capricorn', heightCm: 158, weightKg: 48, interests: ['collecting CDs', 'playing drums', 'playing piano'], position: 'Lead Vocalist, Lead Dancer' },
      { memberId: 'gain', birthdate: '1987-09-20', zodiacSign: 'Virgo', heightCm: 163, weightKg: 43, interests: ['interior design', 'watching movies and TV', 'playing games'], position: 'Main Dancer, Vocalist, Visual, Maknae' },
    ],
  },
  {
    artistId: 'fx',
    agency: 'SM Entertainment',
    debutDate: '2009-09-05',
    fandomName: 'MeU',
    fandomColorName: 'Pearl Light Periwinkle',
    members: [
      { memberId: 'victoria', birthdate: '1987-02-02', zodiacSign: 'Aquarius', heightCm: 168.5, weightKg: 45, interests: ['traditional dance', 'jazz dance', 'coffee', 'cooking'], position: 'Leader, Main Dancer, Lead Rapper, Sub Vocalist, Visual' },
      { memberId: 'amber', birthdate: '1992-09-18', zodiacSign: 'Virgo', heightCm: 167, interests: ['basketball', 'taekwondo', 'rapping'], favoriteFoods: ['tteokbokki'], position: 'Main Rapper, Sub Vocalist' },
      { memberId: 'luna', birthdate: '1993-08-12', zodiacSign: 'Leo', heightCm: 161, weightKg: 44, interests: ['musicals', 'dance'], favoriteFoods: ['pizza'], position: 'Main Vocalist, Lead Dancer' },
      { memberId: 'krystal', birthdate: '1994-10-24', zodiacSign: 'Scorpio', heightCm: 165, weightKg: 45, interests: ['photography'], position: 'Lead Vocalist, Visual, Maknae' },
      { memberId: 'sulli', birthdate: '1994-03-29', zodiacSign: 'Aries', heightCm: 172, weightKg: 41, interests: ['perfume collecting', 'drawing', 'journaling'], position: 'Sub Vocalist, Sub Rapper, Visual' },
    ],
  },
  {
    artistId: 'infinite',
    agency: 'Woollim Entertainment',
    influences: ['Epik High', 'Tablo'],
    debutDate: '2010-06-09',
    fandomName: 'Inspirit',
    fandomColorName: 'Pearl Metal Gold',
    members: [
      { memberId: 'kim-sunggyu', birthdate: '1989-04-28', zodiacSign: 'Taurus', heightCm: 176, weightKg: 60, interests: ['playing in a band'], position: 'Leader, Main Vocalist' },
      { memberId: 'jang-dongwoo', birthdate: '1990-11-22', zodiacSign: 'Sagittarius', heightCm: 172, interests: ['journaling'], position: 'Main Rapper, Main Dancer, Vocalist' },
      { memberId: 'lee-sungyeol', birthdate: '1991-08-27', zodiacSign: 'Virgo', heightCm: 183, weightKg: 70, interests: ['watching movies'], position: 'Vocalist, Lead Rapper' },
      { memberId: 'nam-woohyun', birthdate: '1991-02-08', zodiacSign: 'Aquarius', heightCm: 173, weightKg: 60, interests: ['doing impressions', 'cooking'], position: 'Main Vocalist, Lead Dancer' },
      { memberId: 'hoya', birthdate: '1991-03-28', zodiacSign: 'Aries', heightCm: 176, position: 'Main Dancer, Lead Rapper, Vocalist' },
      { memberId: 'lee-sungjong', birthdate: '1993-09-03', zodiacSign: 'Virgo', heightCm: 179, interests: ['dancing'], position: 'Vocalist, Maknae' },
      { memberId: 'dongwoo', birthdate: '1992-03-13', zodiacSign: 'Pisces', heightCm: 180, interests: ['photography', 'reading manga', 'playing guitar'], favoriteAnimal: 'cat', position: 'Vocalist, Visual, Face of the Group' },
    ],
  },
  {
    artistId: 'mblaq',
    agency: 'J. Tune Camp',
    influences: ['Rain'],
    debutDate: '2009-10-14',
    fandomName: 'A+',
    fandomColorName: 'Pearl Chocolate',
    members: [
      { memberId: 'seungho', birthdate: '1987-10-16', zodiacSign: 'Libra', heightCm: 176, weightKg: 63, interests: ['listening to music', 'playing soccer', 'knitting', 'cooking'], position: 'Leader, Main Dancer, Lead Vocalist' },
      { memberId: 'gseven', birthdate: '1987-11-06', zodiacSign: 'Scorpio', heightCm: 177, weightKg: 65, interests: ['cooking', 'playing piano', 'playing guitar'], position: 'Main Vocalist' },
      { memberId: 'lee-joon', birthdate: '1988-02-07', zodiacSign: 'Aquarius', heightCm: 180, weightKg: 65, interests: ['exercising'], position: 'Main Dancer, Vocalist, Face of the Group' },
      { memberId: 'thunder', birthdate: '1990-10-07', zodiacSign: 'Libra', heightCm: 181, weightKg: 65, interests: ['listening to music', 'composing'], position: 'Lead Rapper, Lead Dancer, Vocalist, Visual' },
      { memberId: 'mir', birthdate: '1991-03-10', zodiacSign: 'Pisces', heightCm: 178, weightKg: 63, interests: ['comedy'], position: 'Main Rapper, Vocalist, Maknae' },
    ],
  },
  {
    artistId: 'rainbow',
    agency: 'DSP Media',
    debutDate: '2009-11-12',
    fandomName: 'Rainnous',
    members: [
      { memberId: 'kim-jaekyung', birthdate: '1988-12-24', zodiacSign: 'Capricorn', heightCm: 168, weightKg: 51, interests: ['biking', 'horseback riding', 'playing flute', 'playing piano'], position: 'Leader, Main Dancer, Lead Vocalist, Visual, Face of the Group' },
      { memberId: 'go-woori', birthdate: '1988-02-22', zodiacSign: 'Pisces', heightCm: 165, weightKg: 55, interests: ['watching dramas and movies', 'modern dance', 'ballet'], position: 'Main Rapper, Lead Dancer' },
      { memberId: 'cho-hyunyoung', birthdate: '1991-08-11', zodiacSign: 'Leo', heightCm: 160, weightKg: 44, interests: ['voice impressions', 'speaking Chinese'], position: 'Main Vocalist, Maknae' },
      { memberId: 'jung-yoonhye', birthdate: '1990-04-14', zodiacSign: 'Aries', heightCm: 163, weightKg: 47, interests: ['taking selfies', 'making facial expressions'], position: 'Vocalist, Rapper' },
      { memberId: 'oh-seunga', birthdate: '1988-09-13', zodiacSign: 'Virgo', heightCm: 168, weightKg: 47, interests: ['reading', 'playing piano'], position: 'Lead Vocalist' },
      { memberId: 'noeul', birthdate: '1989-05-10', zodiacSign: 'Taurus', heightCm: 162, weightKg: 45, interests: ['watching anime', 'voice impressions'], position: 'Vocalist, Rapper' },
    ],
  },
]
