import type { ArtistBio } from './types'

export const batch8Bios: ArtistBio[] = [
  {
    artistId: 'kingandprince',
    agency: 'Starto Entertainment (formerly Johnny & Associates)',
    members: [
      {
        memberId: 'hirano',
        birthdate: '1997-01-29',
        zodiacSign: 'Aquarius',
        heightCm: 170,
        weightKg: 63,
        interests: ['dancing', 'acrobatics', 'badminton'],
      },
      {
        memberId: 'kishi',
        birthdate: '1995-09-29',
        zodiacSign: 'Libra',
        heightCm: 167,
        weightKg: 55,
        interests: ['working out', 'cooking', 'fishing'],
      },
      {
        memberId: 'nagase',
        birthdate: '1999-01-23',
        zodiacSign: 'Aquarius',
        heightCm: 174.5,
        weightKg: 51,
      },
      {
        memberId: 'takahashi',
        birthdate: '1999-04-03',
        zodiacSign: 'Aries',
        heightCm: 170,
        weightKg: 50,
        interests: ['drawing/manga', 'dancing', 'choreography'],
        favoriteFoods: ['ice cream'],
      },
    ],
  },
  {
    artistId: 'jo1',
    agency: 'LAPONE Entertainment',
    members: [
      {
        memberId: 'shion',
        birthdate: '2000-12-11',
        zodiacSign: 'Sagittarius',
        heightCm: 178,
      },
      {
        memberId: 'issei',
        birthdate: '2002-05-30',
        zodiacSign: 'Gemini',
        heightCm: 173,
        interests: ['dancing', 'singing', 'TikTok'],
        favoriteFoods: ["mother's pork soup"],
      },
      {
        memberId: 'ren',
        birthdate: '1997-03-02',
        zodiacSign: 'Pisces',
        heightCm: 173,
        interests: ['watching games', 'comedy', 'magic'],
      },
      {
        memberId: 'sho',
        birthdate: '1995-10-25',
        zodiacSign: 'Scorpio',
        heightCm: 180,
        interests: ['muscle training', 'movies'],
      },
      {
        memberId: 'syoya',
        birthdate: '2000-04-05',
        zodiacSign: 'Aries',
        heightCm: 171,
        interests: ['motorbikes', 'dancing', 'painting'],
        favoriteFoods: ['sushi', 'beefsteak', 'gummies'],
      },
      { memberId: 'keito' },
      {
        memberId: 'junki',
        birthdate: '1998-01-20',
        zodiacSign: 'Aquarius',
        heightCm: 174,
        interests: ['muscle training', 'travel', 'running'],
        favoriteFoods: ['pasta carbonara'],
      },
      {
        memberId: 'ruki',
        birthdate: '1997-11-19',
        zodiacSign: 'Scorpio',
        heightCm: 175,
        interests: ['songwriting'],
        favoriteFoods: ['barbecue', 'hamburger'],
      },
      { memberId: 'mame' },
      {
        memberId: 'takumi',
        birthdate: '1999-06-23',
        zodiacSign: 'Cancer',
        heightCm: 170,
        interests: ['watching movies'],
        favoriteFoods: ['hamburgers'],
      },
      { memberId: 'yu' },
    ],
  },
  {
    artistId: 'ado',
    agency: 'Virgin Music (Universal Music Japan)',
    influences: ['Hatsune Miku / Vocaloid culture', 'Shiina Ringo'],
    members: [
      {
        memberId: 'ado',
        birthdate: '2002-10-24',
        zodiacSign: 'Scorpio',
        interests: ['video games (Apex Legends)'],
        favoriteFoods: ['sushi'],
      },
    ],
  },
  {
    artistId: 'kenshi-yonezu',
    agency: 'Sony Music Japan (Sony Music Records)',
    influences: ['Bump of Chicken', 'Asian Kung-Fu Generation', 'Radwimps', 'Susumu Hirasawa'],
    members: [
      {
        memberId: 'kenshi-yonezu',
        birthdate: '1991-03-10',
        zodiacSign: 'Pisces',
        heightCm: 188,
        interests: ['illustration', 'music video direction', 'reading'],
        favoriteFoods: ['curry', 'Chinese food', 'sushi'],
        favoriteAnimal: 'cat',
      },
    ],
  },
  {
    artistId: 'lisa',
    agency: 'Sony Music Artists / Sacra Music',
    influences: ['Avril Lavigne', 'Oasis', 'Green Day', 'Paramore'],
    members: [
      {
        memberId: 'lisa',
        birthdate: '1987-06-24',
        zodiacSign: 'Cancer',
        heightCm: 165,
        interests: ['cleaning', 'watching movies', 'cooking'],
        favoriteFoods: ['cheesecake'],
        favoriteAnimal: 'dog',
      },
    ],
  },
  {
    artistId: 'she',
    agency: 'HIM International Music',
    members: [
      {
        memberId: 'selina',
        birthdate: '1981-10-31',
        zodiacSign: 'Scorpio',
        heightCm: 163,
        weightKg: 46,
        interests: ['guitar', 'acting'],
        favoriteFoods: ['seaweed', 'baby food'],
        favoriteAnimal: 'rabbit',
      },
      {
        memberId: 'hebe',
        birthdate: '1983-03-30',
        zodiacSign: 'Aries',
        heightCm: 160,
        weightKg: 42,
        interests: ['piano', 'ukulele'],
        favoriteFoods: ['fruit', 'bread'],
        favoriteAnimal: 'dog',
      },
      {
        memberId: 'ella',
        birthdate: '1981-06-18',
        zodiacSign: 'Gemini',
        heightCm: 163,
        weightKg: 50,
        interests: ['acting', 'TV hosting'],
        favoriteFoods: ['seafood macaroni gratin', 'corn chowder'],
        favoriteAnimal: 'cat',
      },
    ],
  },
  {
    artistId: 'fahrenheit',
    agency: 'HIM International Music',
    members: [
      {
        memberId: 'wu-chun',
        birthdate: '1979-10-10',
        zodiacSign: 'Libra',
        heightCm: 181,
        weightKg: 72,
        interests: ['basketball', 'fitness', 'reading', 'photography', 'architecture', 'traveling', 'cooking'],
      },
      {
        memberId: 'aaron-yan',
        birthdate: '1985-11-20',
        zodiacSign: 'Scorpio',
        heightCm: 177,
        weightKg: 62,
        interests: ['basketball', 'singing', 'dancing'],
        favoriteFoods: ['sweets', 'green tea'],
      },
      {
        memberId: 'calvin-chen',
        birthdate: '1980-11-10',
        zodiacSign: 'Scorpio',
        heightCm: 184,
        weightKg: 65,
        interests: ['tennis', 'singing', 'working out'],
      },
      {
        memberId: 'jiro-wang',
        birthdate: '1981-08-24',
        zodiacSign: 'Virgo',
        heightCm: 180,
        weightKg: 67,
      },
    ],
  },
  {
    artistId: 'jolin-tsai',
    agency: 'Warner Music Taiwan',
    influences: ['Madonna', 'Whitney Houston', 'Mariah Carey', "Destiny's Child"],
    members: [
      {
        memberId: 'jolin-tsai',
        birthdate: '1980-09-15',
        zodiacSign: 'Virgo',
        heightCm: 158,
        interests: ['fondant cake decorating', 'yoga', 'rhythmic gymnastics', 'pole dancing'],
        favoriteAnimal: 'dog',
      },
    ],
  },
  {
    artistId: 'jj-lin',
    agency: 'JFJ Productions',
    members: [
      {
        memberId: 'jj-lin',
        birthdate: '1981-03-27',
        zodiacSign: 'Aries',
        heightCm: 173,
        interests: ['esports', 'drawing', 'photography', 'coffee', 'fashion design', 'songwriting'],
        favoriteFoods: ['chili crab', 'Hainanese chicken rice', 'sashimi', 'durian'],
      },
    ],
  },
  {
    artistId: 'wang-leehom',
    agency: 'Homeboy Music',
    members: [
      {
        memberId: 'wang-leehom',
        birthdate: '1976-05-17',
        zodiacSign: 'Taurus',
        heightCm: 180,
        interests: ['piano', 'drums', 'guitar', 'violin', 'erhu', 'environmental activism'],
      },
    ],
  },
  {
    artistId: 'eric-chou',
    agency: 'Warner Music Taiwan',
    influences: ['Jay Chou'],
    members: [
      {
        memberId: 'eric-chou',
        birthdate: '1995-06-22',
        zodiacSign: 'Cancer',
        heightCm: 182,
        interests: ['chess', 'classical piano', 'basketball', 'hockey', 'songwriting'],
      },
    ],
  },
  {
    artistId: 'into1',
    agency: 'Wajijiwa Entertainment',
    members: [
      {
        memberId: 'liu-yu',
        birthdate: '2000-08-24',
        zodiacSign: 'Virgo',
        heightCm: 175,
        interests: ['dance', 'traveling'],
      },
      {
        memberId: 'zhou-keyu',
        birthdate: '2002-05-17',
        zodiacSign: 'Taurus',
        heightCm: 188,
        interests: ['music composition', 'studying'],
      },
      {
        memberId: 'mika',
        birthdate: '1998-12-21',
        zodiacSign: 'Sagittarius',
        heightCm: 176,
      },
      {
        memberId: 'zhang-jing',
        birthdate: '2003-01-08',
        zodiacSign: 'Capricorn',
        heightCm: 185,
        interests: ['guitar', 'bass', 'drums', 'erhu', 'wood carving', 'music composition'],
      },
      {
        memberId: 'liu-zhang',
        birthdate: '1999-12-18',
        zodiacSign: 'Sagittarius',
        heightCm: 180,
        interests: ['rapping', 'music production'],
      },
      { memberId: 'r1se' },
    ],
  },
  {
    artistId: 'snh48',
    agency: 'STAR48 (Shanghai Star48 Culture Media Group)',
    members: [{ memberId: 'rotating-lineup-snh48' }],
  },
  {
    artistId: 'zhou-shen',
    agency: 'Independent (personal studio, under Shanghai Jinyan Culture Media)',
    members: [
      {
        memberId: 'zhou-shen',
        birthdate: '1992-09-29',
        zodiacSign: 'Libra',
        heightCm: 161,
      },
    ],
  },
]
