import type { ArtistBio } from './types'

export const batch5Bios: ArtistBio[] = [
  {
    artistId: 'secret',
    agency: 'RBW (formerly TS Entertainment)',
    debutDate: '2009-10-13',
    fandomName: 'Secret Time',
    fandomColorName: 'White',
    members: [
      { memberId: 'song-jieun', birthdate: '1990-05-05', zodiacSign: 'Taurus', heightCm: 160, weightKg: 45, position: 'Main Vocalist, Maknae' },
      { memberId: 'jun-hyosung', birthdate: '1989-10-13', zodiacSign: 'Libra', heightCm: 160, weightKg: 50, favoriteAnimal: 'cat', position: 'Leader, Main Dancer, Lead Vocalist, Face of the Group' },
      { memberId: 'han-sunhwa', birthdate: '1990-10-06', zodiacSign: 'Libra', heightCm: 165, weightKg: 45, interests: ['reading', 'hiking', 'golf', 'walking'], position: 'Vocalist, Visual, Maknae' },
      { memberId: 'zinger', birthdate: '1990-02-02', zodiacSign: 'Aquarius', heightCm: 157, weightKg: 47, interests: ['writing lyrics', 'pilates'], position: 'Main Rapper, Lead Dancer, Vocalist' },
    ],
  },
  {
    artistId: 'sistar',
    agency: 'Starship Entertainment',
    debutDate: '2010-06-03',
    fandomName: 'Star1',
    fandomColorName: 'Fuchsia',
    members: [
      { memberId: 'hyorin', birthdate: '1990-12-11', zodiacSign: 'Sagittarius', heightCm: 164, weightKg: 45, favoriteAnimal: 'cat', position: 'Leader, Main Vocalist, Lead Dancer, Lead Rapper, Face of the Group' },
      { memberId: 'bora', birthdate: '1989-12-30', zodiacSign: 'Capricorn', heightCm: 165, weightKg: 46, position: 'Main Rapper, Main Dancer, Vocalist, Visual' },
      { memberId: 'soyou', birthdate: '1991-09-12', zodiacSign: 'Virgo', heightCm: 168, weightKg: 49, position: 'Lead Vocalist' },
      { memberId: 'dasom', birthdate: '1993-05-06', zodiacSign: 'Taurus', heightCm: 167, weightKg: 44, position: 'Vocalist, Visual, Maknae' },
    ],
  },
  {
    artistId: 'ttara',
    agency: 'MBK Entertainment',
    debutDate: '2009-07-29',
    fandomName: "Queen's",
    fandomColorName: 'Yellow',
    members: [
      { memberId: 'boram', birthdate: '1986-03-22', zodiacSign: 'Aries', heightCm: 155, weightKg: 45, interests: ['drawing manga'], position: 'Leader, Rapper, Vocalist' },
      { memberId: 'qri', birthdate: '1986-12-12', zodiacSign: 'Sagittarius', heightCm: 163, weightKg: 44, interests: ['golf'], favoriteAnimal: 'dog', position: 'Leader, Lead Dancer, Sub-Vocalist, Rapper, Visual, Face of the Group' },
      { memberId: 'soyeon-tara', birthdate: '1987-10-05', zodiacSign: 'Libra', heightCm: 163, interests: ['singing trot songs'], favoriteAnimal: 'dog', position: 'Leader, Main Vocalist' },
      { memberId: 'hyomin', birthdate: '1989-05-30', zodiacSign: 'Gemini', heightCm: 167, weightKg: 48.4, interests: ['photography', 'painting', 'cooking'], position: 'Main Rapper, Lead Vocalist, Lead Dancer' },
      { memberId: 'eunjung', birthdate: '1988-12-12', zodiacSign: 'Sagittarius', heightCm: 168, weightKg: 48, interests: ['watching movies', 'flower arranging', 'reading fashion magazines'], position: 'Main Rapper, Lead Vocalist, Lead Dancer' },
      { memberId: 'jiyeon', birthdate: '1993-06-07', zodiacSign: 'Gemini', heightCm: 165, weightKg: 45, position: 'Main Dancer, Sub-Vocalist, Visual, Center, Face of the Group, Maknae' },
    ],
  },
  {
    artistId: 'teen-top',
    agency: 'TOP Media',
    debutDate: '2010-07-10',
    fandomName: 'Angel',
    fandomColorName: 'Pearl Light Lavender',
    members: [
      { memberId: 'cap', birthdate: '1992-11-04', zodiacSign: 'Scorpio', heightCm: 178, weightKg: 71, interests: ['drawing', 'graffiti design', 'exercising'], position: 'Leader, Main Rapper' },
      { memberId: 'niel', birthdate: '1994-08-16', zodiacSign: 'Leo', heightCm: 178, weightKg: 64, interests: ['listening to music'], position: 'Main Vocalist, Face of the Group' },
      { memberId: 'changjo', birthdate: '1995-11-16', zodiacSign: 'Scorpio', heightCm: 179, weightKg: 70, interests: ['taekwondo', 'jeet kune do'], position: 'Main Dancer, Vocalist, Maknae' },
      { memberId: 'lhan', birthdate: '1993-11-23', zodiacSign: 'Sagittarius', heightCm: 171, weightKg: 55, interests: ['playing piano', 'music composition'], position: 'Lead Rapper, Vocalist, Visual' },
      { memberId: 'ricky', birthdate: '1995-02-27', zodiacSign: 'Pisces', heightCm: 172, weightKg: 66, interests: ['board games'], position: 'Lead Dancer, Vocalist' },
    ],
  },
  {
    artistId: 'ukiss',
    agency: 'Tango Music (formerly NH Media)',
    debutDate: '2008-08-28',
    fandomName: 'KISSme',
    fandomColorName: 'Pearl Fuchsia',
    members: [
      { memberId: 'soohyun', birthdate: '1989-03-11', zodiacSign: 'Pisces', heightCm: 181, weightKg: 69, interests: ['playing piano'], favoriteFoods: ['vegetables', 'healthy foods'], position: 'Leader, Lead Vocalist' },
      { memberId: 'eli', birthdate: '1991-03-13', zodiacSign: 'Pisces', heightCm: 180, weightKg: 68, interests: ['kung fu', 'taekwondo'], favoriteFoods: ['dragon fruit'], favoriteAnimal: 'cat', position: 'Main Rapper, Vocalist' },
      { memberId: 'kevin', birthdate: '1991-11-25', zodiacSign: 'Sagittarius', heightCm: 180, weightKg: 55, interests: ['guitar', 'piano'], favoriteFoods: ['tteokbokki'], position: 'Main Vocalist, Lead Dancer, Face of the Group' },
      { memberId: 'jun', birthdate: '1997-01-22', zodiacSign: 'Aquarius', heightCm: 185, weightKg: 61, interests: ['bowling', 'video games', 'listening to indie music'], favoriteAnimal: 'dog', position: 'Rapper, Vocalist, Maknae' },
      { memberId: 'hoon', birthdate: '1991-08-16', zodiacSign: 'Leo', heightCm: 181, weightKg: 67, interests: ['anime', 'taekwondo', 'piano'], position: 'Main Vocalist, Maknae' },
    ],
  },
  {
    artistId: 'aoa',
    agency: 'FNC Entertainment',
    debutDate: '2012-08-09',
    fandomName: 'Elvis',
    members: [
      { memberId: 'jimin-aoa', birthdate: '1991-01-08', zodiacSign: 'Capricorn', heightCm: 161, weightKg: 44, interests: ['guitar', 'harmonica', 'piano'], position: 'Leader, Main Rapper, Vocalist, Lead Guitarist' },
      { memberId: 'yuna-aoa', birthdate: '1992-12-30', zodiacSign: 'Capricorn', heightCm: 163, weightKg: 44, interests: ['playing piano'], position: 'Main Vocalist, Keyboardist' },
      { memberId: 'hyejeong', birthdate: '1993-08-10', zodiacSign: 'Leo', heightCm: 172, weightKg: 48, interests: ['yoga', 'cooking'], position: 'Lead Vocalist, Lead Dancer, Visual, Center' },
      { memberId: 'choa', birthdate: '1990-03-06', zodiacSign: 'Pisces', heightCm: 160, weightKg: 47.4, interests: ['playing guitar'], position: 'Main Vocalist, Rhythm Guitarist' },
      { memberId: 'mina-aoa', birthdate: '1993-09-21', zodiacSign: 'Virgo', heightCm: 158.5, weightKg: 50, interests: ['playing bass guitar'], favoriteFoods: ['chicken', 'pizza'], position: 'Lead Rapper, Vocalist, Bassist' },
      { memberId: 'seolhyun', birthdate: '1995-01-03', zodiacSign: 'Capricorn', heightCm: 167, weightKg: 47, interests: ['playing piano', 'swimming'], position: 'Lead Dancer, Vocalist, Center, Face of the Group' },
    ],
  },
  {
    artistId: 'apink',
    agency: 'IST Entertainment',
    debutDate: '2011-04-19',
    fandomName: 'Pink Panda',
    fandomColorName: 'Strawberry Pink',
    members: [
      { memberId: 'park-chorong', birthdate: '1991-03-03', zodiacSign: 'Pisces', heightCm: 162.8, weightKg: 46, interests: ['hapkido'], favoriteAnimal: 'cat', position: 'Leader, Lead Dancer, Vocalist, Rapper' },
      { memberId: 'yoon-bomi', birthdate: '1993-08-13', zodiacSign: 'Leo', heightCm: 163, weightKg: 51.4, interests: ['taekwondo', 'soccer'], favoriteAnimal: 'dog', position: 'Lead Vocalist, Main Rapper, Main Dancer, Center' },
      { memberId: 'son-naeun', birthdate: '1994-02-10', zodiacSign: 'Aquarius', heightCm: 168, weightKg: 45, position: 'Lead Dancer, Vocalist, Rapper, Center, Visual' },
      { memberId: 'jung-eunji', birthdate: '1993-08-18', zodiacSign: 'Leo', heightCm: 162.3, weightKg: 47, interests: ['playing piano'], position: 'Main Vocalist, Face of the Group' },
      { memberId: 'kim-namjoo', birthdate: '1995-04-15', zodiacSign: 'Aries', heightCm: 165, weightKg: 48, interests: ['impersonations'], position: 'Lead Vocalist, Lead Dancer, Rapper' },
      { memberId: 'oh-hayoung', birthdate: '1996-07-19', zodiacSign: 'Cancer', heightCm: 169, weightKg: 52, interests: ['acting'], position: 'Vocalist, Rapper, Maknae' },
    ],
  },
  {
    artistId: 'block-b',
    agency: 'Seven Seasons',
    debutDate: '2011-04-13',
    fandomName: 'BBC (Block B Club)',
    fandomColorName: 'Black & Yellow Stripes',
    members: [
      { memberId: 'zico', birthdate: '1992-09-14', zodiacSign: 'Virgo', heightCm: 181, weightKg: 65, interests: ['shopping', 'reading', 'watching comedies', 'freestyle rap'], position: 'Leader, Main Rapper, Vocalist, Face of the Group' },
      { memberId: 'taeil', birthdate: '1990-09-24', zodiacSign: 'Libra', heightCm: 166, weightKg: 54, interests: ['collecting hats', 'raising fish'], position: 'Main Vocalist' },
      { memberId: 'bbomb', birthdate: '1990-12-14', zodiacSign: 'Sagittarius', heightCm: 174.3, weightKg: 60, interests: ['playing piano', 'collecting fashion photoshoots'], position: 'Main Dancer, Vocalist' },
      { memberId: 'jaehyo', birthdate: '1990-12-23', zodiacSign: 'Capricorn', heightCm: 182, weightKg: 60, interests: ['basketball', 'baseball', 'collecting electronics'], position: 'Lead Vocalist, Visual' },
      { memberId: 'ukwon', birthdate: '1992-04-09', zodiacSign: 'Aries', heightCm: 176, weightKg: 70, interests: ['watching movies', 'listening to music', 'reading'], favoriteAnimal: 'cat', position: 'Lead Dancer, Vocalist' },
      { memberId: 'kyung', birthdate: '1992-07-08', zodiacSign: 'Cancer', heightCm: 170, weightKg: 52, interests: ['web surfing'], position: 'Lead Rapper, Vocalist' },
      { memberId: 'pyo-jihoon', birthdate: '1993-02-02', zodiacSign: 'Aquarius', heightCm: 179.7, weightKg: 78, interests: ['acting', 'soccer'], position: 'Lead Rapper, Vocalist, Maknae' },
    ],
  },
  {
    artistId: 'btob',
    agency: 'Cube Entertainment',
    debutDate: '2012-03-21',
    fandomName: 'MELODY',
    fandomColorName: 'Slow Blue',
    fandomColorHex: '#42B4E6',
    members: [
      { memberId: 'eunkwang', birthdate: '1990-11-22', zodiacSign: 'Sagittarius', heightCm: 173, weightKg: 62, interests: ['playing piano'], favoriteAnimal: 'cat', position: 'Leader, Main Vocalist' },
      { memberId: 'minhyuk', birthdate: '1990-11-29', zodiacSign: 'Sagittarius', heightCm: 173, weightKg: 61, interests: ['writing lyrics', 'composing music', 'exercising', 'acrobatics'], position: 'Lead Rapper, Lead Dancer, Vocalist, Visual' },
      { memberId: 'changsub', birthdate: '1991-02-26', zodiacSign: 'Pisces', heightCm: 178, weightKg: 64, interests: ['cooking', 'skateboarding'], position: 'Lead Vocalist' },
      { memberId: 'hyunsik', birthdate: '1992-03-07', zodiacSign: 'Pisces', heightCm: 177, weightKg: 66, interests: ['singing', 'writing and composing music'], position: 'Main Dancer, Lead Vocalist' },
      { memberId: 'peniel', birthdate: '1993-03-10', zodiacSign: 'Pisces', heightCm: 175, weightKg: 63, interests: ['acting', 'guitar'], position: 'Lead Rapper, Vocalist' },
      { memberId: 'ilhoon', birthdate: '1994-10-04', zodiacSign: 'Libra', heightCm: 176, weightKg: 64, interests: ['rapping', 'writing lyrics', 'composing'], position: 'Main Rapper, Vocalist' },
      { memberId: 'sungjae', birthdate: '1995-05-02', zodiacSign: 'Taurus', heightCm: 180, weightKg: 68, interests: ['snowboarding', 'fishing', 'shopping'], position: 'Vocalist, Face of the Group, Maknae' },
    ],
  },
  {
    artistId: 'wjsn',
    agency: 'Starship Entertainment',
    debutDate: '2016-02-25',
    fandomName: 'Ujung',
    fandomColorName: 'Vivid Tangerine, Airforce Blue & Timberwolf',
    members: [
      { memberId: 'seola', birthdate: '1994-12-24', zodiacSign: 'Capricorn', heightCm: 164.6, weightKg: 45, position: 'Lead Vocalist' },
      { memberId: 'bona', birthdate: '1995-08-19', zodiacSign: 'Leo', heightCm: 163, weightKg: 47, interests: ['playing piano'], position: 'Lead Dancer, Vocalist, Rapper, Visual' },
      { memberId: 'exy', birthdate: '1995-11-06', zodiacSign: 'Scorpio', heightCm: 166, weightKg: 49, interests: ['composing rap'], position: 'Leader, Main Rapper, Vocalist' },
      { memberId: 'soobin-wjsn', birthdate: '1996-09-14', zodiacSign: 'Virgo', heightCm: 157, interests: ['playing piano', 'violin', 'flute'], position: 'Main Vocalist' },
      { memberId: 'luda', birthdate: '1997-03-06', zodiacSign: 'Pisces', heightCm: 156.7, weightKg: 43.4, position: 'Vocalist, Rapper' },
      { memberId: 'dawon', birthdate: '1997-04-16', zodiacSign: 'Aries', heightCm: 167, weightKg: 48, interests: ['playing piano', 'guitar', 'swimming', 'pilates'], position: 'Main Vocalist' },
      { memberId: 'yeoreum', birthdate: '1999-01-10', zodiacSign: 'Capricorn', heightCm: 162, weightKg: 45, interests: ['playing piano', 'scuba diving'], position: 'Main Dancer, Vocalist, Rapper' },
      { memberId: 'eunseo', birthdate: '1998-05-27', zodiacSign: 'Gemini', heightCm: 170, interests: ['playing piano', 'guitar', 'drums'], position: 'Vocalist, Rapper' },
      { memberId: 'xuan-yi', birthdate: '1995-01-26', zodiacSign: 'Aquarius', heightCm: 166, weightKg: 42.9, interests: ['playing piano'], position: 'Lead Dancer, Vocalist' },
      { memberId: 'cheng-xiao', birthdate: '1998-07-15', zodiacSign: 'Cancer', heightCm: 166, weightKg: 51.2, interests: ['playing guzheng', 'Chinese dance', 'rhythmic gymnastics'], position: 'Main Dancer, Vocalist, Visual, Face of the Group' },
    ],
  },
  {
    artistId: 'dreamcatcher',
    agency: 'Dreamcatcher Company',
    debutDate: '2017-01-13',
    fandomName: 'InSomnia',
    fandomColorName: 'Eerie Black, Burnt Umber & Cream Can',
    members: [
      { memberId: 'jiu', birthdate: '1994-05-17', zodiacSign: 'Taurus', heightCm: 167, weightKg: 49, interests: ['long baths', 'aerobics'], position: 'Leader, Lead Vocalist, Lead Dancer, Visual' },
      { memberId: 'sua', birthdate: '1994-08-10', zodiacSign: 'Leo', heightCm: 162, weightKg: 42, interests: ['drawing', 'watching dramas', 'dance choreography'], favoriteFoods: ['meat', 'hamburgers'], favoriteAnimal: 'elephant', position: 'Main Dancer, Lead Rapper, Sub-Vocalist' },
      { memberId: 'siyeon', birthdate: '1995-10-01', zodiacSign: 'Libra', heightCm: 166, weightKg: 49, interests: ['playing games', 'piano'], position: 'Main Vocalist' },
      { memberId: 'handong', birthdate: '1996-03-26', zodiacSign: 'Aries', heightCm: 165, weightKg: 46, favoriteFoods: ['chocolate'], position: 'Sub-Vocalist' },
      { memberId: 'yoohyeon', birthdate: '1997-01-07', zodiacSign: 'Capricorn', heightCm: 168, weightKg: 49, interests: ['video games', 'guitar'], position: 'Lead Vocalist' },
      { memberId: 'dami', birthdate: '1997-03-07', zodiacSign: 'Pisces', heightCm: 163, weightKg: 44, interests: ['reading', 'kendo'], favoriteAnimal: 'animals', position: 'Main Rapper, Lead Dancer, Sub-Vocalist' },
      { memberId: 'gahyeon', birthdate: '1999-02-03', zodiacSign: 'Aquarius', heightCm: 160, weightKg: 57, interests: ['math', 'cooking'], position: 'Lead Rapper, Sub-Vocalist, Maknae' },
    ],
  },
  {
    artistId: 'exid',
    agency: 'Banana Culture',
    debutDate: '2012-02-16',
    fandomName: 'LEGGO',
    fandomColorName: 'Eclipse (Purple, Cream, Pink)',
    fandomColorHex: '#7373C1, #F1E6B1, #E06287',
    members: [
      { memberId: 'solji', birthdate: '1989-01-10', zodiacSign: 'Capricorn', heightCm: 170, weightKg: 50, interests: ['hiking'], favoriteAnimal: 'dog', position: 'Leader, Main Vocalist' },
      { memberId: 'leggo', birthdate: '1991-12-10', zodiacSign: 'Sagittarius', heightCm: 168, weightKg: 53, interests: ['composing', 'playing with Lego'], position: 'Main Rapper, Lead Dancer' },
      { memberId: 'hani', birthdate: '1992-05-01', zodiacSign: 'Taurus', heightCm: 168.8, weightKg: 55, favoriteAnimal: 'cat', position: 'Lead Vocalist, Lead Dancer, Visual, Face of the Group' },
      { memberId: 'jeonghwa', birthdate: '1995-05-08', zodiacSign: 'Taurus', heightCm: 169, weightKg: 50, interests: ['playing piano'], position: 'Main Dancer, Lead Rapper, Sub Vocalist, Visual, Maknae' },
      { memberId: 'hyelin', birthdate: '1993-08-23', zodiacSign: 'Virgo', heightCm: 167, weightKg: 47, interests: ['playing violin'], position: 'Lead Vocalist' },
    ],
  },
  {
    artistId: 'girls-day',
    agency: 'Dream T Entertainment',
    debutDate: '2010-07-09',
    fandomName: 'DAI5Y',
    members: [
      { memberId: 'sojin', birthdate: '1986-05-21', zodiacSign: 'Gemini', heightCm: 166, weightKg: 49.5, interests: ['cleaning', 'shopping'], position: 'Leader, Lead Vocalist' },
      { memberId: 'yura', birthdate: '1992-11-06', zodiacSign: 'Scorpio', heightCm: 170, weightKg: 52, interests: ['dancing', 'listening to music', 'painting'], position: 'Main Rapper, Lead Dancer, Vocalist, Visual' },
      { memberId: 'minah', birthdate: '1993-05-13', zodiacSign: 'Taurus', heightCm: 164, weightKg: 47, interests: ['playing piano', 'impersonation'], position: 'Main Vocalist' },
      { memberId: 'hyeri', birthdate: '1994-06-09', zodiacSign: 'Gemini', heightCm: 167, weightKg: 54, interests: ['watching movies', 'reading', 'running'], position: 'Main Dancer, Lead Rapper, Vocalist, Face of the Group, Maknae' },
    ],
  },
]
