import type { ArtistBio } from './types'

export const batch4Bios: ArtistBio[] = [
  {
    artistId: 'mayday',
    agency: "B'in Music",
    influences: ['The Beatles', 'U2', 'Oasis', 'Mr. Children'],
    members: [
      { memberId: 'ashin', birthdate: '1975-12-06', zodiacSign: 'Sagittarius', heightCm: 180, weightKg: 74 },
      { memberId: 'monster', birthdate: '1976-11-28', zodiacSign: 'Sagittarius', heightCm: 168, weightKg: 62 },
      { memberId: 'stone', birthdate: '1975-12-11', zodiacSign: 'Sagittarius', heightCm: 172, weightKg: 67 },
      { memberId: 'masa', birthdate: '1977-04-25', zodiacSign: 'Taurus', heightCm: 172, weightKg: 66, interests: ['collecting records and books', 'coffee'] },
      { memberId: 'guanyou', birthdate: '1973-07-28', zodiacSign: 'Leo', heightCm: 178, weightKg: 60, interests: ['jazz piano', 'entrepreneurship'] },
    ],
  },
  {
    artistId: 'tfboys',
    agency: 'Time Fengjun Entertainment',
    members: [
      {
        memberId: 'wang-junkai',
        birthdate: '1999-09-21',
        zodiacSign: 'Virgo',
        heightCm: 182,
        weightKg: 51,
        interests: ['One Piece anime', 'travel'],
        favoriteFoods: ['Chongqing noodles', 'watermelon'],
        favoriteAnimal: 'panda',
      },
      {
        memberId: 'wang-yuan',
        birthdate: '2000-11-08',
        zodiacSign: 'Scorpio',
        interests: ['singing', 'piano', 'cycling', 'fishing'],
        favoriteFoods: ['snacks', 'meat dishes', 'noodles'],
      },
      {
        memberId: 'jackson-yee',
        birthdate: '2000-11-28',
        zodiacSign: 'Sagittarius',
        interests: ['dance', 'taekwondo', 'magic', 'calligraphy', 'musical instruments'],
      },
    ],
  },
  {
    artistId: 'finkl',
    agency: 'DSP Media',
    members: [
      {
        memberId: 'lee-hyori',
        birthdate: '1979-05-10',
        zodiacSign: 'Taurus',
        heightCm: 167,
        weightKg: 49,
        interests: ['drawing', 'acting'],
        favoriteFoods: ['chocolate covered cookies'],
      },
      {
        memberId: 'ok-joohyun',
        birthdate: '1980-03-20',
        zodiacSign: 'Pisces',
        heightCm: 173,
        weightKg: 54,
        interests: ['listening to music', 'photography'],
        favoriteFoods: ['pizza', 'spaghetti'],
      },
      {
        memberId: 'sung-yuri',
        birthdate: '1981-03-03',
        zodiacSign: 'Pisces',
        heightCm: 168,
        weightKg: 45,
        interests: ['music', 'piano', 'sleeping'],
        favoriteFoods: ['pizza'],
      },
      {
        memberId: 'lee-jiyeon',
        birthdate: '1980-03-21',
        zodiacSign: 'Pisces',
        heightCm: 167,
        weightKg: 46,
        interests: ['music', 'films'],
        favoriteFoods: ['jjajangmyeon'],
      },
    ],
  },
  {
    artistId: 'god',
    agency: 'SidusHQ',
    members: [
      { memberId: 'park-joonhyung', birthdate: '1969-07-20', zodiacSign: 'Cancer', heightCm: 181, weightKg: 68, interests: ['surfing', 'skateboarding', 'snowboarding', 'martial arts'] },
      { memberId: 'yoon-kyesang', birthdate: '1978-12-20', zodiacSign: 'Sagittarius', heightCm: 183, weightKg: 62, interests: ['computer games', 'music', 'movies', 'repairing items'] },
      { memberId: 'son-hoyoung', birthdate: '1980-03-26', zodiacSign: 'Aries', heightCm: 175, weightKg: 74, interests: ['skiing', 'basketball', 'movies'] },
      { memberId: 'kim-taewoo', birthdate: '1981-05-12', zodiacSign: 'Taurus', heightCm: 190, weightKg: 85, interests: ['music', 'movies', 'dancing'] },
      { memberId: 'danny-ahn', birthdate: '1978-12-22', zodiacSign: 'Capricorn', heightCm: 181, weightKg: 73, interests: ['music', 'skiing', 'car tuning', 'driving', 'reading comics'] },
    ],
  },
  {
    artistId: 'babyvox',
    agency: 'DR Music',
    members: [
      { memberId: 'yoon-eunhye', birthdate: '1984-10-03', zodiacSign: 'Libra', heightCm: 168, weightKg: 50 },
      { memberId: 'kan-miyeon', birthdate: '1982-02-02', zodiacSign: 'Aquarius', heightCm: 169, weightKg: 47 },
      { memberId: 'sim-eunjin', birthdate: '1981-02-06', zodiacSign: 'Aquarius', heightCm: 168, weightKg: 48, interests: ['fashion', 'art'] },
    ],
  },
  {
    artistId: '2pm',
    agency: 'JYP Entertainment',
    members: [
      { memberId: 'jang-wooyoung', birthdate: '1989-04-30', zodiacSign: 'Taurus', heightCm: 178, weightKg: 65, interests: ['appreciating music', 'browsing the web'], favoriteFoods: ['chicken'] },
      { memberId: 'lee-junho', birthdate: '1990-01-25', zodiacSign: 'Aquarius', heightCm: 178, weightKg: 67, interests: ['animal rights activism'] },
      { memberId: 'nichkhun', birthdate: '1988-06-24', zodiacSign: 'Cancer', heightCm: 181, weightKg: 64, interests: ['playing piano', 'playing guitar'] },
      { memberId: 'ok-taecyeon', birthdate: '1988-12-27', zodiacSign: 'Capricorn', heightCm: 186, weightKg: 76, interests: ['sleeping'] },
      { memberId: 'hwang-chansung', birthdate: '1990-02-11', zodiacSign: 'Aquarius', heightCm: 184, weightKg: 75, interests: ['listening to music', 'gaming', 'working out', 'reading books'] },
    ],
  },
  {
    artistId: '4minute',
    agency: 'Cube Entertainment',
    members: [
      { memberId: 'nam-jihyun', birthdate: '1990-01-09', zodiacSign: 'Capricorn', heightCm: 167, weightKg: 49, interests: ['perfumes', 'collecting Hello Kitty and Mickey Mouse items'] },
      { memberId: 'heo-gayoon', birthdate: '1990-05-18', zodiacSign: 'Taurus', heightCm: 165, weightKg: 47, interests: ['writing', 'watching movies', 'singing', 'shopping'] },
      { memberId: 'jeon-jiyoon', birthdate: '1990-10-15', zodiacSign: 'Libra', heightCm: 165, weightKg: 47, interests: ['singing', 'dancing', 'cooking', 'writing lyrics'], favoriteFoods: ['Pocky'], favoriteAnimal: 'harp seal' },
      { memberId: 'kim-hyuna', birthdate: '1992-06-06', zodiacSign: 'Gemini', heightCm: 164, interests: ['cooking', 'watching movies', 'photography', 'taking selfies'], favoriteAnimal: 'harp seal' },
      { memberId: 'gwon-sohyun', birthdate: '1994-08-30', zodiacSign: 'Virgo', heightCm: 162, weightKg: 45, interests: ['swimming', 'shopping', 'interior design', 'piano'] },
    ],
  },
  {
    artistId: 'after-school',
    agency: 'Pledis Entertainment',
    influences: ['The Pussycat Dolls'],
    members: [
      { memberId: 'kahi', birthdate: '1980-12-25', zodiacSign: 'Capricorn', heightCm: 168, weightKg: 50 },
      { memberId: 'kim-jungah', birthdate: '1983-08-02', zodiacSign: 'Leo', heightCm: 167, weightKg: 49 },
      { memberId: 'uee', birthdate: '1988-04-09', zodiacSign: 'Aries', heightCm: 173, weightKg: 50 },
      { memberId: 'lizzy', birthdate: '1992-07-31', zodiacSign: 'Leo', heightCm: 168, weightKg: 46, interests: ['listening to music', 'playing Nintendo DS games', 'arts and crafts'] },
      { memberId: 'nana', birthdate: '1991-09-14', zodiacSign: 'Virgo', heightCm: 171, weightKg: 48, interests: ['singing', 'dancing'] },
    ],
  },
  {
    artistId: 'brown-eyed-girls',
    agency: 'Mystic Entertainment',
    members: [
      { memberId: 'jea', birthdate: '1981-09-18', zodiacSign: 'Virgo', heightCm: 158.9, weightKg: 46, interests: ['watching movies', 'playing piano'], favoriteFoods: ['Mexican food'] },
      { memberId: 'miryo', birthdate: '1981-11-02', zodiacSign: 'Scorpio', heightCm: 163, weightKg: 45, interests: ['listening to music', 'playing guitar', 'video games'] },
      { memberId: 'narsha', birthdate: '1981-12-28', zodiacSign: 'Capricorn', heightCm: 158, weightKg: 48, interests: ['collecting CDs', 'playing drums', 'playing piano'] },
      { memberId: 'gain', birthdate: '1987-09-20', zodiacSign: 'Virgo', heightCm: 163, weightKg: 43, interests: ['interior design', 'watching movies and TV', 'playing games'] },
    ],
  },
  {
    artistId: 'fx',
    agency: 'SM Entertainment',
    members: [
      { memberId: 'victoria', birthdate: '1987-02-02', zodiacSign: 'Aquarius', heightCm: 168.5, weightKg: 45, interests: ['traditional dance', 'jazz dance', 'coffee', 'cooking'] },
      { memberId: 'amber', birthdate: '1992-09-18', zodiacSign: 'Virgo', heightCm: 167, interests: ['basketball', 'taekwondo', 'rapping'], favoriteFoods: ['tteokbokki'] },
      { memberId: 'luna', birthdate: '1993-08-12', zodiacSign: 'Leo', heightCm: 161, weightKg: 44, interests: ['musicals', 'dance'], favoriteFoods: ['pizza'] },
      { memberId: 'krystal', birthdate: '1994-10-24', zodiacSign: 'Scorpio', heightCm: 165, weightKg: 45, interests: ['photography'] },
      { memberId: 'sulli', birthdate: '1994-03-29', zodiacSign: 'Aries', heightCm: 172, weightKg: 41, interests: ['perfume collecting', 'drawing', 'journaling'] },
    ],
  },
  {
    artistId: 'infinite',
    agency: 'Woollim Entertainment',
    influences: ['Epik High', 'Tablo'],
    members: [
      { memberId: 'kim-sunggyu', birthdate: '1989-04-28', zodiacSign: 'Taurus', heightCm: 176, weightKg: 60, interests: ['playing in a band'] },
      { memberId: 'jang-dongwoo', birthdate: '1990-11-22', zodiacSign: 'Sagittarius', heightCm: 172, interests: ['journaling'] },
      { memberId: 'lee-sungyeol', birthdate: '1991-08-27', zodiacSign: 'Virgo', heightCm: 183, weightKg: 70, interests: ['watching movies'] },
      { memberId: 'nam-woohyun', birthdate: '1991-02-08', zodiacSign: 'Aquarius', heightCm: 173, weightKg: 60, interests: ['doing impressions', 'cooking'] },
      { memberId: 'hoya', birthdate: '1991-03-28', zodiacSign: 'Aries', heightCm: 176 },
      { memberId: 'lee-sungjong', birthdate: '1993-09-03', zodiacSign: 'Virgo', heightCm: 179, interests: ['dancing'] },
      { memberId: 'dongwoo', birthdate: '1992-03-13', zodiacSign: 'Pisces', heightCm: 180, interests: ['photography', 'reading manga', 'playing guitar'], favoriteAnimal: 'cat' },
    ],
  },
  {
    artistId: 'mblaq',
    agency: 'J. Tune Camp',
    influences: ['Rain'],
    members: [
      { memberId: 'seungho', birthdate: '1987-10-16', zodiacSign: 'Libra', heightCm: 176, weightKg: 63, interests: ['listening to music', 'playing soccer', 'knitting', 'cooking'] },
      { memberId: 'gseven', birthdate: '1987-11-06', zodiacSign: 'Scorpio', heightCm: 177, weightKg: 65, interests: ['cooking', 'playing piano', 'playing guitar'] },
      { memberId: 'lee-joon', birthdate: '1988-02-07', zodiacSign: 'Aquarius', heightCm: 180, weightKg: 65, interests: ['exercising'] },
      { memberId: 'thunder', birthdate: '1990-10-07', zodiacSign: 'Libra', heightCm: 181, weightKg: 65, interests: ['listening to music', 'composing'] },
      { memberId: 'mir', birthdate: '1991-03-10', zodiacSign: 'Pisces', heightCm: 178, weightKg: 63, interests: ['comedy'] },
    ],
  },
  {
    artistId: 'rainbow',
    agency: 'DSP Media',
    members: [
      { memberId: 'kim-jaekyung', birthdate: '1988-12-24', zodiacSign: 'Capricorn', heightCm: 168, weightKg: 51, interests: ['biking', 'horseback riding', 'playing flute', 'playing piano'] },
      { memberId: 'go-woori', birthdate: '1988-02-22', zodiacSign: 'Pisces', heightCm: 165, weightKg: 55, interests: ['watching dramas and movies', 'modern dance', 'ballet'] },
      { memberId: 'cho-hyunyoung', birthdate: '1991-08-11', zodiacSign: 'Leo', heightCm: 160, weightKg: 44, interests: ['voice impressions', 'speaking Chinese'] },
      { memberId: 'jung-yoonhye', birthdate: '1990-04-14', zodiacSign: 'Aries', heightCm: 163, weightKg: 47, interests: ['taking selfies', 'making facial expressions'] },
      { memberId: 'oh-seunga', birthdate: '1988-09-13', zodiacSign: 'Virgo', heightCm: 168, weightKg: 47, interests: ['reading', 'playing piano'] },
      { memberId: 'noeul', birthdate: '1989-05-10', zodiacSign: 'Taurus', heightCm: 162, weightKg: 45, interests: ['watching anime', 'voice impressions'] },
    ],
  },
]
