import type { ArtistBio } from './types'

export const batch6Bios: ArtistBio[] = [
  {
    artistId: 'ikon',
    agency: '143 Entertainment',
    debutDate: '2015-09-15',
    fandomName: 'iKONIC',
    fandomColorName: 'Orange-Red',
    members: [
      { memberId: 'jay', birthdate: '1994-02-07', zodiacSign: 'Aquarius', heightCm: 165, weightKg: 55, interests: ['swimming', 'playing guitar'], favoriteFoods: ['beef'], position: 'Leader, Main Vocalist, Lead Dancer' },
      { memberId: 'song-yunhyeong', birthdate: '1995-02-08', zodiacSign: 'Aquarius', heightCm: 175, weightKg: 58, interests: ['cycling', 'drawing', 'making scented candles', 'cooking', 'taking selfies'], position: 'Sub-Vocalist, Visual, Center' },
      { memberId: 'koo-junhoe', birthdate: '1997-03-31', zodiacSign: 'Aries', heightCm: 183, weightKg: 68, interests: ['writing poems', 'jiu-jitsu', 'impersonations'], position: 'Main Vocalist' },
      { memberId: 'kim-donghyuk', birthdate: '1997-01-03', zodiacSign: 'Capricorn', heightCm: 173, weightKg: 62, interests: ['reading and writing prose', 'basketball', 'ping pong', 'sneaker collecting', 'fashion'], favoriteFoods: ['Mexican food'], position: 'Main Dancer, Sub-Vocalist' },
      { memberId: 'chanwoo', birthdate: '1998-01-26', zodiacSign: 'Aquarius', heightCm: 181, weightKg: 65, interests: ['video games'], favoriteFoods: ['sushi', 'chicken steak'], position: 'Sub-Vocalist, Maknae' },
      { memberId: 'bobby', birthdate: '1995-12-21', zodiacSign: 'Sagittarius', heightCm: 175, weightKg: 68, interests: ['basketball', 'playing guitar', 'playing drums', 'playing piano', 'singing'], favoriteFoods: ['Mexican food', 'kimchi stew', 'hamburger', 'pizza'], position: 'Main Rapper, Sub-Vocalist, Face of the Group' },
    ],
  },
  {
    artistId: 'lovelyz',
    agency: 'Woollim Entertainment',
    debutDate: '2014-11-12',
    fandomName: 'Lovelinus',
    fandomColorName: 'Pinkish-Purple',
    members: [
      { memberId: 'yoo-jiae', birthdate: '1993-05-21', zodiacSign: 'Gemini', heightCm: 163, weightKg: 46, interests: ['watching movies', 'exercising', 'dancing', 'acting', 'playing piano'], favoriteFoods: ['ice cream', 'strawberries'], position: 'Vocalist, Rapper, Visual' },
      { memberId: 'seo-jisoo', birthdate: '1994-02-11', zodiacSign: 'Aquarius', heightCm: 163, weightKg: 46, interests: ['watching movies', 'listening to music', 'shopping', 'drawing', 'gaming'], favoriteFoods: ['chocolate', 'tart', 'pork ribs', 'jokbal'], position: 'Main Dancer, Vocalist, Rapper, Visual' },
      { memberId: 'mijoo', birthdate: '1994-09-23', zodiacSign: 'Libra', heightCm: 164, weightKg: 47, interests: ['watching movies', 'listening to music', 'jazz dance'], favoriteFoods: ['meat', 'tteokbokki'], position: 'Main Dancer, Vocalist' },
      { memberId: 'kei', birthdate: '1995-03-20', zodiacSign: 'Pisces', heightCm: 162, weightKg: 47, interests: ['cooking', 'acting'], favoriteFoods: ['meat', 'jokbal', 'samgyeopsal', 'chicken'], position: 'Main Vocalist, Lead Dancer' },
      { memberId: 'ryu-sujeong', birthdate: '1997-11-19', zodiacSign: 'Scorpio', heightCm: 168, weightKg: 48, interests: ['playing guitar', 'songwriting'], favoriteFoods: ['nachos', 'chicken feet', 'cheese', 'braised spicy chicken'], position: 'Lead Vocalist' },
      { memberId: 'jin', birthdate: '1996-06-12', zodiacSign: 'Gemini', heightCm: 164, weightKg: 47, interests: ['listening to music', 'singing'], favoriteFoods: ['spaghetti', 'seaweed soup', 'galbijjim', 'tteokbokki'], position: 'Main Vocalist' },
      { memberId: 'yein', birthdate: '1998-06-04', zodiacSign: 'Gemini', heightCm: 165, weightKg: 49, interests: ['shopping', 'listening to music'], favoriteFoods: ['chicken feet', 'cartilage'], position: 'Lead Dancer, Vocalist, Maknae' },
    ],
  },
  {
    artistId: 'monsta-x',
    agency: 'Starship Entertainment',
    influences: ['Big Bang', 'Michael Jackson', 'Chris Brown', 'Bruno Mars'],
    debutDate: '2015-05-14',
    fandomName: 'Monbebe',
    fandomColorName: 'Lost, Guilty & Beautiful',
    members: [
      { memberId: 'shownu', birthdate: '1992-06-18', zodiacSign: 'Gemini', heightCm: 181, weightKg: 77, interests: ['listening to music', 'video games', 'swimming', 'working out', 'creating choreography'], favoriteFoods: ['meat', 'beef', 'cereal'], favoriteAnimal: 'Bear', position: 'Leader, Main Dancer, Lead Vocalist' },
      { memberId: 'wonho', birthdate: '1993-03-01', zodiacSign: 'Pisces', heightCm: 178, weightKg: 86, interests: ['playing piano', 'video games', 'studying languages', 'working out', 'taekwondo', 'swimming', 'designing stage outfits', 'guitar'], favoriteFoods: ['ramyeon', 'chicken breast', 'cold noodles', 'pizza'], favoriteAnimal: 'Rabbit', position: 'Lead Vocalist, Lead Dancer, Visual' },
      { memberId: 'minhyuk-mx', birthdate: '1993-11-03', zodiacSign: 'Scorpio', heightCm: 179, weightKg: 65, interests: ['video games', 'going out with friends', 'watching movies'], favoriteFoods: ['sweet potato', 'pizza'], favoriteAnimal: 'Dog', position: 'Sub-Vocalist, Visual' },
      { memberId: 'kihyun', birthdate: '1993-11-22', zodiacSign: 'Sagittarius', heightCm: 175, weightKg: 62, interests: ['dancing', 'composing and songwriting', 'playing piano and guitar', 'spending time with friends'], favoriteFoods: ['chicken'], position: 'Main Vocalist' },
      { memberId: 'hyungwon', birthdate: '1994-01-15', zodiacSign: 'Capricorn', heightCm: 182, weightKg: 60, interests: ['modeling', 'shopping', 'traveling', 'DJing', 'acting'], favoriteFoods: ['seasoned pork ribs', 'sashimi', 'peaches'], position: 'Lead Dancer, Sub-Vocalist, Sub-Rapper, Visual, Center' },
      { memberId: 'joohoney', birthdate: '1994-10-06', zodiacSign: 'Libra', heightCm: 179, weightKg: 67, interests: ['video games', 'going out with friends', 'watching movies'], favoriteFoods: ['tteokbokki', 'dumplings'], favoriteAnimal: 'Bee', position: 'Main Rapper, Sub-Vocalist' },
      { memberId: 'im-changkyun', birthdate: '1996-01-26', zodiacSign: 'Aquarius', heightCm: 175, weightKg: 63, interests: ['writing songs', 'hanging out with groupmates'], favoriteFoods: ['curry', 'strawberries', 'chocolate'], favoriteAnimal: 'Jaguar', position: 'Lead Rapper, Sub-Vocalist, Maknae' },
    ],
  },
  {
    artistId: 'nct127',
    agency: 'SM Entertainment',
    debutDate: '2016-07-07',
    // NCTzen is the umbrella fandom for all of NCT; SM's own per-unit names come from the
    // fanclub memberships opened 2023-09-12 (NCTzen 127 / NCTzen DREAM / NCTzen WISH).
    fandomName: 'NCTzen 127',
    fandomColorName: 'Pearl Neo Champagne',
    members: [
      { memberId: 'taeyong', birthdate: '1995-07-01', zodiacSign: 'Cancer', heightCm: 175, weightKg: 58, interests: ['listening to music', 'watching movies', 'playing games', 'swimming', 'shopping'], favoriteFoods: ['melon', 'green tea ice cream'], position: 'Leader, Main Rapper, Main Dancer, Sub-Vocalist, Visual, Center' },
      { memberId: 'johnny', birthdate: '1995-02-09', zodiacSign: 'Aquarius', heightCm: 185, weightKg: 70, interests: ['reading', 'photography', 'watching movies'], favoriteFoods: ['chili soup', 'watermelon'], favoriteAnimal: 'Dog', position: 'Lead Dancer, Sub-Rapper, Sub-Vocalist' },
      { memberId: 'taeil-nct', birthdate: '1994-06-14', zodiacSign: 'Gemini', heightCm: 171, weightKg: 60, interests: ['listening to music', 'watching movies', 'playing piano and guitar'], favoriteFoods: ['pork belly', 'ice cream', 'pizza'], position: 'Main Vocalist' },
      { memberId: 'yuta', birthdate: '1995-10-26', zodiacSign: 'Scorpio', heightCm: 176, weightKg: 60, interests: ['traditional dance', 'football'], favoriteFoods: ['watermelon', 'takoyaki', 'bento'], favoriteAnimal: 'Dog', position: 'Lead Dancer, Sub-Vocalist, Sub-Rapper' },
      { memberId: 'doyoung', birthdate: '1996-02-01', zodiacSign: 'Aquarius', heightCm: 178, weightKg: 60, interests: ['playing flute and bass', 'singing trot songs'], favoriteFoods: ['cream cheese bread', 'watermelon', 'hot pot'], position: 'Main Vocalist' },
      { memberId: 'jaehyun', birthdate: '1997-02-14', zodiacSign: 'Aquarius', heightCm: 180, weightKg: 63, interests: ['playing piano', 'basketball'], favoriteFoods: ['meat', 'spicy pork', 'peach'], position: 'Main Vocalist, Lead Dancer, Sub-Rapper, Visual' },
      { memberId: 'winwin', birthdate: '1997-10-28', zodiacSign: 'Scorpio', heightCm: 179, weightKg: 60, interests: ['playing piano and guitar', 'watching movies', 'swimming'], favoriteFoods: ['hot pot', 'tiramisu', 'strawberries'], position: 'Lead Dancer, Sub-Vocalist' },
      { memberId: 'mark-nct', birthdate: '1999-08-02', zodiacSign: 'Leo', heightCm: 176, weightKg: 61, interests: ['playing guitar', 'badminton', 'ice skating'], favoriteFoods: ['bagels', 'chicken', 'kimchi'], position: 'Main Rapper, Main Dancer, Sub-Vocalist' },
      { memberId: 'haechan', birthdate: '2000-06-06', zodiacSign: 'Gemini', heightCm: 174, weightKg: 58, interests: ['playing piano', 'listening to music', 'singing', 'watching dramas', 'gaming'], favoriteFoods: ['samgyeopsal', 'kimchi jjigae'], position: 'Main Vocalist, Lead Dancer, Maknae' },
    ],
  },
  {
    artistId: 'nct-dream',
    agency: 'SM Entertainment',
    debutDate: '2016-08-25',
    // See nct127 — "Dreamies" names the MEMBERS, not the fans, and is never a fandom name.
    fandomName: 'NCTzen DREAM',
    fandomColorName: 'Pearl Neo Champagne',
    members: [
      { memberId: 'mark-dream', birthdate: '1999-08-02', zodiacSign: 'Leo', heightCm: 176, weightKg: 61, interests: ['rapping', 'guitar', 'badminton', 'ice skating'], favoriteFoods: ['bagels', 'cookies and cream ice cream', 'chicken', 'kimchi'], position: 'Leader, Main Rapper, Main Dancer, Sub-Vocalist, Face of the Group' },
      { memberId: 'renjun', birthdate: '2000-03-23', zodiacSign: 'Aries', heightCm: 170, weightKg: 52, interests: ['drawing', 'hula-hooping', 'fashion', 'ballet and contemporary dance', 'sci-fi movies'], favoriteFoods: ['hot pot with beef'], favoriteAnimal: 'Fox', position: 'Main Vocalist, Lead Dancer' },
      { memberId: 'jeno', birthdate: '2000-04-23', zodiacSign: 'Taurus', heightCm: 177, weightKg: 58, interests: ['photography', 'mobile games', 'working out', 'ping-pong', 'violin', 'guitar'], favoriteAnimal: 'Horse', position: 'Main Rapper, Lead Dancer, Sub-Vocalist, Visual' },
      { memberId: 'haechan-dream', birthdate: '2000-06-06', zodiacSign: 'Gemini', heightCm: 174, weightKg: 57, interests: ['piano', 'listening to music', 'singing', 'dance', 'football'], favoriteFoods: ['samgyeopsal'], position: 'Main Vocalist' },
      { memberId: 'jaemin', birthdate: '2000-08-13', zodiacSign: 'Leo', heightCm: 177, weightKg: 60, interests: ['piano', 'dancing', 'badminton'], favoriteFoods: ['ramen', 'potato pizza', 'fried chicken', 'chocolate', 'peaches'], favoriteAnimal: 'Dog', position: 'Lead Dancer, Lead Rapper, Sub-Vocalist, Visual, Center' },
      { memberId: 'chenle', birthdate: '2001-11-22', zodiacSign: 'Sagittarius', heightCm: 176, weightKg: 58, interests: ['cooking', 'football', 'basketball', 'music', 'piano'], favoriteFoods: ['chocolate', 'kimchi', 'fried eggs'], position: 'Main Vocalist' },
      { memberId: 'jisung', birthdate: '2002-02-05', zodiacSign: 'Aquarius', heightCm: 180, weightKg: 61, interests: ['rapping', 'dancing', 'singing', 'popping and locking', 'video games', 'soccer'], favoriteFoods: ['pork belly', 'melon'], favoriteAnimal: 'Hamster', position: 'Main Dancer, Sub-Vocalist, Sub-Rapper, Maknae' },
    ],
  },
  {
    artistId: 'oh-my-girl',
    agency: 'WM Entertainment',
    debutDate: '2015-04-20',
    fandomName: 'Miracle',
    fandomColorName: 'Pantone 230C, 304C & 461U',
    members: [
      { memberId: 'hyojung', birthdate: '1994-07-28', zodiacSign: 'Leo', heightCm: 158, weightKg: 42, interests: ['singing', 'watching dramas and variety shows', 'piano'], favoriteFoods: ['bread', 'egg sandwiches'], favoriteAnimal: 'Squirrel', position: 'Leader, Main Vocalist' },
      { memberId: 'mimi', birthdate: '1995-05-01', zodiacSign: 'Taurus', heightCm: 163, weightKg: 47, interests: ['listening to music', 'reading', 'walking', 'shopping', 'drawing'], favoriteFoods: ['eggs', 'chocolate snacks'], favoriteAnimal: 'Bear', position: 'Main Rapper, Main Dancer, Sub-Vocalist' },
      { memberId: 'yooa', birthdate: '1995-09-17', zodiacSign: 'Virgo', heightCm: 161, weightKg: 44, interests: ['being alone', 'listening to music'], favoriteAnimal: 'Kitten', position: 'Main Dancer, Lead Vocalist, Face of the Group' },
      { memberId: 'seunghee', birthdate: '1996-01-25', zodiacSign: 'Aquarius', heightCm: 160, weightKg: 44, interests: ['watching movies', 'listening to music', 'drawing', 'stretching', 'guitar'], position: 'Main Vocalist' },
      { memberId: 'binnie', birthdate: '1997-09-09', zodiacSign: 'Virgo', heightCm: 161, weightKg: 44, interests: ['solving problems', 'discovering new music', 'walks along the Han River'], position: 'Sub-Vocalist' },
      { memberId: 'jiho', birthdate: '1997-04-04', zodiacSign: 'Aries', heightCm: 165, weightKg: 48, interests: ['listening to music in the car', 'watching movies', 'guitar'], favoriteFoods: ['meat'], favoriteAnimal: 'Koala', position: 'Lead Vocalist, Lead Dancer, Visual' },
      { memberId: 'arin', birthdate: '1999-06-18', zodiacSign: 'Gemini', heightCm: 165, weightKg: 48, interests: ['watching movies with caramel popcorn', 'coordinating outfits'], favoriteFoods: ['rice', 'chicken'], favoriteAnimal: 'Rabbit', position: 'Lead Dancer, Sub-Vocalist, Maknae' },
    ],
  },
  {
    artistId: 'pentagon',
    agency: 'Cube Entertainment',
    debutDate: '2016-10-10',
    fandomName: 'Universe',
    fandomColorName: 'UniNavy',
    fandomColorHex: '#253562',
    members: [
      { memberId: 'jinho', birthdate: '1992-04-17', zodiacSign: 'Aries', heightCm: 168, weightKg: 52, interests: ['playing piano', 'playing guitar'], position: 'Main Vocalist' },
      { memberId: 'hui', birthdate: '1993-08-28', zodiacSign: 'Virgo', heightCm: 171, weightKg: 57, interests: ['playing piano', 'tumbling'], position: 'Leader, Main Vocalist, Lead Dancer, Producer' },
      { memberId: 'hongseok', birthdate: '1994-04-17', zodiacSign: 'Aries', heightCm: 180, weightKg: 68, interests: ['reading books', 'studying languages', 'working out'], position: 'Lead Vocalist' },
      { memberId: 'shinwon', birthdate: '1995-12-11', zodiacSign: 'Sagittarius', heightCm: 184, weightKg: 68, interests: ['lying down'], favoriteFoods: ['hamburgers', 'fries'], position: 'Vocalist' },
      { memberId: 'yeoone', birthdate: '1996-03-27', zodiacSign: 'Aries', heightCm: 179, weightKg: 60, interests: ['swimming'], position: 'Lead Vocalist' },
      { memberId: 'yanan', birthdate: '1996-10-25', zodiacSign: 'Scorpio', heightCm: 187, weightKg: 70, interests: ['playing erhu'], position: 'Vocalist, Visual' },
      { memberId: 'yuto', birthdate: '1998-01-23', zodiacSign: 'Aquarius', heightCm: 185, weightKg: 63, interests: ['baseball', 'watching anime'], favoriteFoods: ['mayonnaise'], position: 'Lead Rapper, Lead Dancer, Sub-Vocalist' },
      { memberId: 'kino', birthdate: '1998-01-27', zodiacSign: 'Aquarius', heightCm: 177, weightKg: 59, interests: ['dancing', 'choreography'], position: 'Main Dancer, Vocalist, Sub-Rapper, Face of the Group' },
      { memberId: 'wooseok', birthdate: '1998-01-31', zodiacSign: 'Aquarius', heightCm: 191, weightKg: 72, interests: ['playing violin', 'watching anime'], favoriteFoods: ['spicy food'], position: 'Main Rapper, Sub-Vocalist, Maknae' },
    ],
  },
  {
    artistId: 'vixx',
    agency: 'Jellyfish Entertainment',
    debutDate: '2012-05-24',
    fandomName: 'Starlight',
    fandomColorName: 'Navy & Shining Gold',
    members: [
      { memberId: 'n', birthdate: '1990-06-30', zodiacSign: 'Cancer', heightCm: 180, weightKg: 67, interests: ['dancing', 'performing', 'reading', 'choreography'], favoriteFoods: ['meat', 'galbi'], position: 'Leader, Main Dancer, Lead Vocalist, Center' },
      { memberId: 'leo', birthdate: '1990-11-10', zodiacSign: 'Scorpio', heightCm: 182, weightKg: 64, interests: ['reading fashion magazines', 'watching Japanese romance films', 'piano', 'fencing', 'taekwondo', 'swimming', 'boxing'], favoriteFoods: ['chicken', 'coffee'], position: 'Main Vocalist' },
      { memberId: 'ken', birthdate: '1992-04-06', zodiacSign: 'Aries', heightCm: 181, weightKg: 65, interests: ['drawing', 'studying gag shows', 'beatboxing', 'dancing'], favoriteFoods: ['instant foods', 'chocolate'], position: 'Main Vocalist' },
      { memberId: 'ravi', birthdate: '1993-02-15', zodiacSign: 'Aquarius', heightCm: 183, weightKg: 65, interests: ['working out', 'graffiti', 'drinking coffee at night'], position: 'Main Rapper, Lead Dancer, Vocalist' },
      { memberId: 'hongbin', birthdate: '1993-09-29', zodiacSign: 'Libra', heightCm: 181, weightKg: 65, interests: ['taking photos', 'playing basketball', 'gaming'], favoriteFoods: ['spaghetti', 'curry', 'sweet and sour pork'], position: 'Lead Rapper, Vocalist, Visual, Face of the Group' },
      { memberId: 'hyuk', birthdate: '1995-07-05', zodiacSign: 'Cancer', heightCm: 184, weightKg: 62, interests: ['reading'], favoriteFoods: ['gopchang', 'pizza', 'spaghetti'], position: 'Main Dancer, Vocalist, Maknae' },
    ],
  },
  {
    artistId: 'winner',
    agency: 'YG Entertainment',
    debutDate: '2014-08-12',
    fandomName: 'INNER CIRCLE',
    fandomColorName: 'Nebula Blue',
    members: [
      { memberId: 'kang-seungyoon', birthdate: '1994-01-21', zodiacSign: 'Aquarius', heightCm: 180, weightKg: 58, interests: ['composing music', 'writing lyrics', 'playing guitar', 'drawing', 'photography', 'billiards', 'reading'], favoriteFoods: ['fried rice'], favoriteAnimal: 'Dog', position: 'Leader, Main Vocalist, Maknae' },
      { memberId: 'lee-seunghoon', birthdate: '1992-01-11', zodiacSign: 'Capricorn', heightCm: 185, weightKg: 65, interests: ['writing lyrics', 'freestyle dancing', 'exploring restaurants', 'fashion'], favoriteAnimal: 'Dog', position: 'Main Dancer, Lead Rapper, Vocalist' },
      { memberId: 'song-mino', birthdate: '1993-03-30', zodiacSign: 'Aries', heightCm: 182, weightKg: 57, interests: ['composing music', 'writing lyrics', 'drawing', 'basketball', 'photography', 'tennis'], favoriteFoods: ['tteokbokki'], favoriteAnimal: 'Cat', position: 'Main Rapper, Vocalist, Face of the Group' },
      { memberId: 'kim-jinwoo', birthdate: '1991-09-26', zodiacSign: 'Libra', heightCm: 177, weightKg: 58, interests: ['swimming', 'watching dramas', 'video games'], favoriteAnimal: 'Cat', position: 'Lead Vocalist, Visual' },
    ],
  },
  {
    artistId: 'cravity',
    agency: 'Starship Entertainment',
    debutDate: '2020-04-14',
    fandomName: 'LUVITY',
    members: [
      { memberId: 'serim', birthdate: '1999-03-03', zodiacSign: 'Pisces', heightCm: 175, interests: ['shopping', 'watching movies', 'working out'], favoriteFoods: ['cheeseball', 'brown sugar cheese foam bubble tea'], position: 'Main Rapper, Visual' },
      { memberId: 'allen', birthdate: '1999-04-26', zodiacSign: 'Taurus', heightCm: 170, interests: ['singing', 'walking', 'choreography', 'songwriting'], position: 'Main Dancer, Lead Rapper' },
      { memberId: 'jungmo', birthdate: '2000-02-05', zodiacSign: 'Aquarius', heightCm: 182, weightKg: 68, interests: ['guitar', 'singing', 'reading manhwa'], favoriteFoods: ['cup noodles', 'hamburger'], position: 'Lead Vocalist, Visual' },
      { memberId: 'woobin', birthdate: '2000-10-16', zodiacSign: 'Libra', heightCm: 175, interests: ['cooking', 'gaming', 'karaoke', 'dancing'], favoriteFoods: ['tomato', 'pasta'], position: 'Main Vocalist' },
      { memberId: 'wonjin', birthdate: '2001-03-22', zodiacSign: 'Aries', heightCm: 174, weightKg: 57, interests: ['baseball'], favoriteFoods: ['jjajangmyeon'], position: 'Co-Leader, Lead Vocalist, Lead Dancer' },
      { memberId: 'minhee', birthdate: '2002-09-17', zodiacSign: 'Virgo', heightCm: 185, weightKg: 60, interests: ['going out'], favoriteFoods: ['ramen'], position: 'Lead Vocalist, Visual' },
      { memberId: 'hyeongjun', birthdate: '2002-11-30', zodiacSign: 'Sagittarius', heightCm: 173, weightKg: 60, interests: ['learning the Seoul dialect', 'soccer'], position: 'Co-Leader, Main Dancer, Sub-Vocalist' },
      { memberId: 'taeyoung', birthdate: '2003-01-27', zodiacSign: 'Aquarius', heightCm: 179, interests: ['gaming', 'doing laundry', 'dancing', 'singing'], position: 'Lead Dancer, Sub-Vocalist' },
      { memberId: 'seongmin', birthdate: '2003-08-01', zodiacSign: 'Leo', heightCm: 170, weightKg: 51, interests: ['watching movies and dramas', 'ASMR', 'bicycling', 'drawing', 'calligraphy'], favoriteFoods: ['yogurt', 'Haribo gummies'], position: 'Sub-Vocalist, Maknae' },
    ],
  },
  {
    artistId: 'everglow',
    agency: 'CHXXTA Company',
    debutDate: '2019-03-18',
    fandomName: 'FOREVER',
    fandomColorName: 'Purple Pink & Red',
    members: [
      { memberId: 'e-somi', birthdate: '1998-05-19', zodiacSign: 'Taurus', heightCm: 161, weightKg: 43, interests: ['watching mukbang videos', 'Korean variety shows', 'riding the subway', 'writing lyrics'], favoriteFoods: ['Americano', 'black bean noodles', 'fried foods', 'hamburgers', 'french fries'], favoriteAnimal: 'Dog', position: 'Main Rapper, Main Dancer' },
      { memberId: 'sihyeon', birthdate: '1999-08-05', zodiacSign: 'Leo', heightCm: 170, weightKg: 51, interests: ['cooking', 'collecting', 'nail art', 'watching TV'], favoriteFoods: ['tteokbokki', 'Americano', 'black bean noodles', 'corn dogs', 'cheese sticks'], position: 'Leader, Lead Vocalist, Face of the Group' },
      { memberId: 'mia', birthdate: '2000-01-13', zodiacSign: 'Capricorn', heightCm: 163, weightKg: 42, interests: ['dancing', 'taking selfies', 'sleeping', 'indie pop music'], favoriteFoods: ['chocolate', 'tangerine ice cream', 'sweet and spicy tteokbokki'], favoriteAnimal: 'Dog', position: 'Main Vocalist, Main Dancer' },
      { memberId: 'onda', birthdate: '2000-05-18', zodiacSign: 'Taurus', heightCm: 166, weightKg: 42, interests: ['playing piano', 'taking selfies', 'magic eye puzzles'], favoriteFoods: ['Buldak ramen'], position: 'Lead Dancer' },
      { memberId: 'aisha', birthdate: '2000-07-21', zodiacSign: 'Cancer', heightCm: 174, weightKg: 49, interests: ['dancing', 'listening to DAY6'], position: 'Lead Rapper, Lead Dancer, Visual, Face of the Group, Maknae' },
      { memberId: 'yiren', birthdate: '2000-12-29', zodiacSign: 'Capricorn', heightCm: 163, weightKg: 42, interests: ['shopping', 'cooking', 'Chinese traditional dance'], position: 'Lead Dancer, Sub-Vocalist, Sub-Rapper, Visual, Center, Face of the Group, Maknae' },
    ],
  },
  {
    artistId: 'fromis9',
    agency: 'ASND',
    debutDate: '2018-01-24',
    fandomName: 'Flover',
    fandomColorName: 'Purple & Blue',
    members: [
      { memberId: 'saerom', birthdate: '1997-01-07', zodiacSign: 'Capricorn', heightCm: 163, weightKg: 41, interests: ['reading', 'watching movies', 'tennis', 'badminton', 'swimming', 'bowling'], favoriteFoods: ['tuna', 'omija tea'], favoriteAnimal: 'Dog', position: 'Leader, Lead Dancer, Vocalist, Rapper, Visual' },
      { memberId: 'hayoung', birthdate: '1997-09-29', zodiacSign: 'Libra', heightCm: 164, weightKg: 46, interests: ['songwriting', 'guitar', 'cooking', 'yoga'], favoriteFoods: ['kimchi fried rice', 'soybean paste stew', 'beef'], position: 'Vice-Leader, Main Vocalist, Main Dancer' },
      { memberId: 'gyuri', birthdate: '1997-12-27', zodiacSign: 'Capricorn', heightCm: 168, weightKg: 50, interests: ['piano', 'guitar', 'violin', 'drums', 'traveling'], favoriteFoods: ['pork', 'peaches', 'plums'], position: 'Lead Vocalist, Face of the Group' },
      { memberId: 'jiwon', birthdate: '1998-03-20', zodiacSign: 'Pisces', heightCm: 158, weightKg: 44, interests: ['listening to music', 'shopping', 'gaming', 'figure skating', 'horseback riding'], favoriteFoods: ['cheese', 'sushi'], favoriteAnimal: 'Golden Retriever', position: 'Main Vocalist' },
      { memberId: 'seoyeon', birthdate: '2000-01-22', zodiacSign: 'Aquarius', heightCm: 158, weightKg: 47, interests: ['watching films', 'collecting BMO merchandise', 'collecting chokers'], favoriteFoods: ['gummy bears', 'milk tea'], favoriteAnimal: 'Panda', position: 'Main Rapper, Main Dancer, Vocalist' },
      { memberId: 'chaeyoung-fromis', birthdate: '2000-05-14', zodiacSign: 'Taurus', heightCm: 169, weightKg: 48, interests: ['listening to ballads', 'football', 'running', 'baseball'], favoriteFoods: ['apples', 'cherries', 'peaches'], position: 'Main Dancer, Lead Rapper, Vocalist' },
      { memberId: 'nagyung', birthdate: '2000-06-01', zodiacSign: 'Gemini', heightCm: 160, weightKg: 42, interests: ['gaming', 'listening to ballads', 'sleeping'], favoriteFoods: ['cheese tteokbokki', 'mangoes'], position: 'Lead Dancer, Vocalist, Rapper, Visual' },
      { memberId: 'jiheon', birthdate: '2003-04-17', zodiacSign: 'Aries', heightCm: 166, weightKg: 45, interests: ['dancing', 'guitar', 'acting', 'hapkido', 'reading'], position: 'Vocalist, Maknae' },
    ],
  },
  {
    artistId: 'kep1er',
    agency: 'WAKEONE Entertainment',
    debutDate: '2022-01-03',
    fandomName: 'Kep1ian',
    fandomColorName: 'Lavender & Yellow',
    members: [
      { memberId: 'choi-yujin', birthdate: '1996-08-12', zodiacSign: 'Leo', heightCm: 162, weightKg: 42, interests: ['pilates', 'movies', 'Japanese language'], favoriteFoods: ['mint chocolate', 'fried chicken', 'ramen', 'cake'], favoriteAnimal: 'Rabbit', position: 'Leader, Vocalist' },
      { memberId: 'mashiro', birthdate: '1999-12-16', zodiacSign: 'Sagittarius', heightCm: 158, interests: ['cooking', 'dancing'], favoriteFoods: ['omelets', 'fish cutlets', 'sandwiches'], favoriteAnimal: 'Cat', position: 'Co-Leader, Vocalist' },
      { memberId: 'shen-xiaoting', birthdate: '1999-11-12', zodiacSign: 'Scorpio', heightCm: 168, interests: ['ballroom dance', 'ballet'], favoriteFoods: ['ramen', 'stir-fried beef'], favoriteAnimal: 'Dog', position: 'Main Dancer, Vocalist, Visual' },
      { memberId: 'kim-chaehyun', birthdate: '2002-04-26', zodiacSign: 'Taurus', heightCm: 160, interests: ['photography', 'gaming', 'watching dramas', 'reading', 'dancing', 'shopping', 'guitar'], favoriteFoods: ['mint chocolate', 'bubble tea'], position: 'Main Vocalist, Center' },
      { memberId: 'huening-bahiyyih', birthdate: '2004-07-27', zodiacSign: 'Leo', heightCm: 167, interests: ['bullet journaling', 'shopping'], favoriteFoods: ['pasta', 'chicken', 'fruits'], favoriteAnimal: 'Dog', position: 'Vocalist, Maknae' },
      { memberId: 'kim-dayeon', birthdate: '2003-03-02', zodiacSign: 'Pisces', heightCm: 158, weightKg: 41, interests: ['freestyle dancing', 'leadership activities'], favoriteFoods: ['pork kimchi stew', 'sushi', 'samgyeopsal'], favoriteAnimal: 'Dog', position: 'Main Dancer, Main Rapper, Vocalist' },
      { memberId: 'seo-youngeun', birthdate: '2004-12-27', zodiacSign: 'Capricorn', heightCm: 159, interests: ['taekwondo', 'baseball', 'hip-hop choreography'], favoriteFoods: ['chicken feet', 'tripe'], favoriteAnimal: 'Dog', position: 'Main Vocalist, Dancer, Maknae' },
      { memberId: 'kang-yeseo', birthdate: '2005-08-22', zodiacSign: 'Leo', heightCm: 157, weightKg: 43, interests: ['drawing', 'reading webtoons', 'watching movies'], favoriteFoods: ['cold bean soup noodles', 'spicy seafood noodles'], favoriteAnimal: 'Dog', position: 'Vocalist, Maknae' },
    ],
  },
]
