import type { ArtistSeed } from '../types'

const m = (memberId: string, name: string) => ({ memberId, name })

/**
 * Curated starter roster. Not exhaustive — meant to seed a credible first
 * ranking board across regions/generations; the community grows it via
 * uploads. spotifyArtistId is left undefined where we're not fully certain
 * of the exact catalog match; the popularity provider marks those `stale`
 * until an admin/verified id is supplied.
 */
export const artistSeeds: ArtistSeed[] = [
  // --- K-pop, 1st gen ---
  { id: 'hot', name: 'H.O.T.', region: 'KR', type: 'group', generationId: 'kpop-gen1', members: [m('moon-heejun', 'Moon Hee-jun'), m('jang-woohyuk', 'Jang Woo-hyuk'), m('tony-ahn', 'Tony Ahn'), m('kangta', 'Kangta'), m('lee-jaewon', 'Lee Jae-won')] },
  { id: 'sechskies', name: 'Sechs Kies', region: 'KR', type: 'group', generationId: 'kpop-gen1', members: [m('eun-jiwon', 'Eun Ji-won'), m('kim-jaeduck', 'Kim Jae-duck'), m('lee-jaijin', 'Lee Jai-jin'), m('ko-jiyong', 'Ko Ji-yong'), m('jang-suwon', 'Jang Su-won'), m('kim-jiwon', 'Kang Sung-hoon')] },
  { id: 'ses', name: 'S.E.S.', region: 'KR', type: 'group', generationId: 'kpop-gen1', members: [m('bada', 'Bada'), m('eugene', 'Eugene'), m('shoo', 'Shoo')] },
  { id: 'shinhwa', name: 'Shinhwa', region: 'KR', type: 'group', generationId: 'kpop-gen1', members: [m('eric-mun', 'Eric Mun'), m('lee-minwoo', 'Lee Min-woo'), m('kim-dongwan', 'Kim Dong-wan'), m('shin-hyesung', 'Shin Hye-sung'), m('jun-jin', 'Jun Jin'), m('andy-lee', 'Andy Lee')] },

  // --- K-pop, 2nd gen ---
  { id: 'tvxq', name: 'TVXQ!', region: 'KR', type: 'group', generationId: 'kpop-gen2', spotifyArtistId: '0BUqQnog9gGCVzTVQqBBrl', members: [m('u-know-yunho', 'U-Know Yunho'), m('max-changmin', 'Max Changmin')] },
  { id: 'super-junior', name: 'Super Junior', region: 'KR', type: 'group', generationId: 'kpop-gen2', spotifyArtistId: '3qFo8vLYAeRhutxYs1p0kW', members: [m('leeteuk', 'Leeteuk'), m('heechul', 'Heechul'), m('yesung', 'Yesung'), m('kangin', 'Kangin'), m('shindong', 'Shindong'), m('sungmin', 'Sungmin'), m('eunhyuk', 'Eunhyuk'), m('donghae', 'Donghae'), m('siwon', 'Siwon'), m('ryeowook', 'Ryeowook'), m('kyuhyun', 'Kyuhyun')] },
  { id: 'snsd', name: "Girls' Generation", region: 'KR', type: 'group', generationId: 'kpop-gen2', spotifyArtistId: '0Y3AwBFvSnV6D653N0FvNw', members: [m('taeyeon', 'Taeyeon'), m('sunny', 'Sunny'), m('tiffany', 'Tiffany'), m('hyoyeon', 'Hyoyeon'), m('yuri', 'Yuri'), m('sooyoung', 'Sooyoung'), m('yoona', 'Yoona'), m('seohyun', 'Seohyun')] },
  { id: 'bigbang', name: 'BIGBANG', region: 'KR', type: 'group', generationId: 'kpop-gen2', spotifyArtistId: '1oSPZhvZMIrWW5I41I9Ic1', members: [m('gdragon', 'G-Dragon'), m('taeyang', 'Taeyang'), m('daesung', 'Daesung'), m('seungri', 'Seungri')] },
  { id: 'shinee', name: 'SHINee', region: 'KR', type: 'group', generationId: 'kpop-gen2', spotifyArtistId: '2H2sjqzSb5AiSTFbxOcRA6', members: [m('onew', 'Onew'), m('key', 'Key'), m('minho', 'Minho'), m('taemin', 'Taemin')] },
  { id: '2ne1', name: '2NE1', region: 'KR', type: 'group', generationId: 'kpop-gen2', spotifyArtistId: '3IuAmBOSAo0EIZLDVEkkND', members: [m('cl', 'CL'), m('dara', 'Dara'), m('bom', 'Bom'), m('minzy', 'Minzy')] },
  { id: 'wonder-girls', name: 'Wonder Girls', region: 'KR', type: 'group', generationId: 'kpop-gen2', members: [m('yeeun', 'Yeeun'), m('sunmi', 'Sunmi'), m('yubin', 'Yubin'), m('hyerim', 'Hyerim'), m('sohee', 'Sohee')] },
  { id: 'kara', name: 'KARA', region: 'KR', type: 'group', generationId: 'kpop-gen2', members: [m('park-gyuri', 'Park Gyuri'), m('han-seungyeon', 'Han Seungyeon'), m('goo-hara', 'Goo Hara'), m('kang-jiyoung', 'Kang Jiyoung'), m('nicole', 'Nicole')] },

  // --- K-pop, 3rd gen ---
  { id: 'bts', name: 'BTS', region: 'KR', type: 'group', generationId: 'kpop-gen3', spotifyArtistId: '3Nrfpe0tUJi4K4DXYWgMUX', members: [m('rm', 'RM'), m('jin', 'Jin'), m('suga', 'Suga'), m('j-hope', 'j-hope'), m('jimin', 'Jimin'), m('v', 'V'), m('jungkook', 'Jungkook')] },
  { id: 'exo', name: 'EXO', region: 'KR', type: 'group', generationId: 'kpop-gen3', spotifyArtistId: '2P0KDlt2GhOFqfBVJHhZW9', members: [m('xiumin', 'Xiumin'), m('suho', 'Suho'), m('lay', 'Lay'), m('baekhyun', 'Baekhyun'), m('chen', 'Chen'), m('chanyeol', 'Chanyeol'), m('do', 'D.O.'), m('kai', 'Kai'), m('sehun', 'Sehun')] },
  { id: 'twice', name: 'TWICE', region: 'KR', type: 'group', generationId: 'kpop-gen3', spotifyArtistId: '7n2Ycct7Beij7Dj7meI4X0', members: [m('nayeon', 'Nayeon'), m('jeongyeon', 'Jeongyeon'), m('momo', 'Momo'), m('sana', 'Sana'), m('jihyo', 'Jihyo'), m('mina', 'Mina'), m('dahyun', 'Dahyun'), m('chaeyoung', 'Chaeyoung'), m('tzuyu', 'Tzuyu')] },
  { id: 'blackpink', name: 'BLACKPINK', region: 'KR', type: 'group', generationId: 'kpop-gen3', spotifyArtistId: '41MozSoPIsD1dJM0CLPjZF', members: [m('jisoo', 'Jisoo'), m('jennie', 'Jennie'), m('rose', 'Rosé'), m('lisa', 'Lisa')] },
  { id: 'red-velvet', name: 'Red Velvet', region: 'KR', type: 'group', generationId: 'kpop-gen3', spotifyArtistId: '1z4g3DjTBBZKhvAroFlhOM', members: [m('irene', 'Irene'), m('seulgi', 'Seulgi'), m('wendy', 'Wendy'), m('joy', 'Joy'), m('yeri', 'Yeri')] },
  { id: 'seventeen', name: 'SEVENTEEN', region: 'KR', type: 'group', generationId: 'kpop-gen3', spotifyArtistId: '3qm84nBOXaEQyeNGoWv0UD', members: [m('s-coups', 'S.Coups'), m('jeonghan', 'Jeonghan'), m('joshua', 'Joshua'), m('jun', 'Jun'), m('hoshi', 'Hoshi'), m('wonwoo', 'Wonwoo'), m('woozi', 'Woozi'), m('the8', 'The8'), m('mingyu', 'Mingyu'), m('dk', 'DK'), m('seungkwan', 'Seungkwan'), m('vernon', 'Vernon'), m('dino', 'Dino')] },
  { id: 'mamamoo', name: 'MAMAMOO', region: 'KR', type: 'group', generationId: 'kpop-gen3', spotifyArtistId: '0b1sIic4h9OyDPGxDwzYVT', members: [m('solar', 'Solar'), m('moonbyul', 'Moonbyul'), m('wheein', 'Wheein'), m('hwasa', 'Hwasa')] },
  { id: 'got7', name: 'GOT7', region: 'KR', type: 'group', generationId: 'kpop-gen3', spotifyArtistId: '5JQVQrmVaol9pV9dK2Rprr', members: [m('jb', 'JB'), m('mark', 'Mark'), m('jackson', 'Jackson'), m('jinyoung', 'Jinyoung'), m('youngjae', 'Youngjae'), m('bambam', 'BamBam'), m('yugyeom', 'Yugyeom')] },

  // --- K-pop, 4th gen ---
  { id: 'stray-kids', name: 'Stray Kids', region: 'KR', type: 'group', generationId: 'kpop-gen4', spotifyArtistId: '2dTAdgLJEbFRz0Wf3ZjkPT', members: [m('bang-chan', 'Bang Chan'), m('lee-know', 'Lee Know'), m('changbin', 'Changbin'), m('hyunjin', 'Hyunjin'), m('han', 'Han'), m('felix', 'Felix'), m('seungmin', 'Seungmin'), m('i-n', 'I.N')] },
  { id: 'itzy', name: 'ITZY', region: 'KR', type: 'group', generationId: 'kpop-gen4', spotifyArtistId: '2KjD07AVlDphOTHFqYFYb2', members: [m('yeji', 'Yeji'), m('lia', 'Lia'), m('ryujin', 'Ryujin'), m('chaeryeong', 'Chaeryeong'), m('yuna', 'Yuna')] },
  { id: 'ateez', name: 'ATEEZ', region: 'KR', type: 'group', generationId: 'kpop-gen4', spotifyArtistId: '6TIYQ3jFPwQSRmorSezPxX', members: [m('hongjoong', 'Hongjoong'), m('seonghwa', 'Seonghwa'), m('yunho', 'Yunho'), m('yeosang', 'Yeosang'), m('san', 'San'), m('mingi', 'Mingi'), m('wooyoung', 'Wooyoung'), m('jongho', 'Jongho')] },
  { id: 'txt', name: 'TOMORROW X TOGETHER', region: 'KR', type: 'group', generationId: 'kpop-gen4', spotifyArtistId: '0ghlgldX5Dd6720Q3qFyQB', members: [m('soobin', 'Soobin'), m('yeonjun', 'Yeonjun'), m('beomgyu', 'Beomgyu'), m('taehyun', 'Taehyun'), m('hueningkai', 'Hueningkai')] },
  { id: 'aespa', name: 'aespa', region: 'KR', type: 'group', generationId: 'kpop-gen4', spotifyArtistId: '6VvvXOWpNQyusiZctnDCoy', members: [m('karina', 'Karina'), m('giselle', 'Giselle'), m('winter', 'Winter'), m('ningning', 'Ningning')] },
  { id: 'enhypen', name: 'ENHYPEN', region: 'KR', type: 'group', generationId: 'kpop-gen4', spotifyArtistId: '5t6VW6koHK7HScLXqcSXCS', members: [m('jungwon', 'Jungwon'), m('heeseung', 'Heeseung'), m('jay', 'Jay'), m('jake', 'Jake'), m('sunghoon', 'Sunghoon'), m('sunoo', 'Sunoo'), m('ni-ki', 'Ni-ki')] },
  { id: 'ive', name: 'IVE', region: 'KR', type: 'group', generationId: 'kpop-gen4', spotifyArtistId: '6RHTUrRF63xao58xh9Qshm', members: [m('yujin', 'Yujin'), m('gaeul', 'Gaeul'), m('rei', 'Rei'), m('wonyoung', 'Wonyoung'), m('liz', 'Liz'), m('leeseo', 'Leeseo')] },
  { id: 'le-sserafim', name: 'LE SSERAFIM', region: 'KR', type: 'group', generationId: 'kpop-gen4', spotifyArtistId: '4KWTAlx2RvbpseOGMEmROQ', members: [m('sakura', 'Sakura'), m('kim-chaewon', 'Kim Chaewon'), m('huh-yunjin', 'Huh Yunjin'), m('kazuha', 'Kazuha'), m('hong-eunchae', 'Hong Eunchae')] },
  { id: 'newjeans', name: 'NewJeans', region: 'KR', type: 'group', generationId: 'kpop-gen4', spotifyArtistId: '6HvZYsbFfjnjFrWF950C9d', members: [m('minji', 'Minji'), m('hanni', 'Hanni'), m('danielle', 'Danielle'), m('haerin', 'Haerin'), m('hyein', 'Hyein')] },
  { id: 'gidle', name: '(G)I-DLE', region: 'KR', type: 'group', generationId: 'kpop-gen4', spotifyArtistId: '5MnFhw02EqiwWAAKX4YFrs', members: [m('miyeon', 'Miyeon'), m('minnie', 'Minnie'), m('soyeon', 'Soyeon'), m('yuqi', 'Yuqi'), m('shuhua', 'Shuhua')] },

  // --- K-pop, 5th gen ---
  { id: 'riize', name: 'RIIZE', region: 'KR', type: 'group', generationId: 'kpop-gen5', spotifyArtistId: '2y8Jo9CKhJvtfeKl3T3xrf', members: [m('shotaro', 'Shotaro'), m('eunseok', 'Eunseok'), m('sungchan', 'Sungchan'), m('wonbin', 'Wonbin'), m('soobin-riize', 'Sohee'), m('anton', 'Anton')] },
  { id: 'babymonster', name: 'BABYMONSTER', region: 'KR', type: 'group', generationId: 'kpop-gen5', spotifyArtistId: '3XenIptt0ZChb71GgOA5vy', members: [m('ruka', 'Ruka'), m('asa', 'Asa'), m('pharita', 'Pharita'), m('ahyeon', 'Ahyeon'), m('rora', 'Rora'), m('rami', 'Rami'), m('chiquita', 'Chiquita')] },
  { id: 'illit', name: 'ILLIT', region: 'KR', type: 'group', generationId: 'kpop-gen5', members: [m('yunah', 'Yunah'), m('minju', 'Minju'), m('moka', 'Moka'), m('wonhee', 'Wonhee'), m('iroha', 'Iroha')] },

  // --- J-pop ---
  { id: 'arashi', name: 'Arashi', region: 'JP', type: 'group', generationId: 'jpop-classic', spotifyArtistId: '3zN9BiKQwq0KJRWDh0mCsz', members: [m('satoshi-ohno', 'Satoshi Ohno'), m('sho-sakurai', 'Sho Sakurai'), m('masaki-aiba', 'Masaki Aiba'), m('kazunari-ninomiya', 'Kazunari Ninomiya'), m('jun-matsumoto', 'Jun Matsumoto')] },
  { id: 'akb48', name: 'AKB48', region: 'JP', type: 'group', generationId: 'jpop-classic', spotifyArtistId: '7JpCsQtd6HWJvfXAaeFuvW', members: [m('rotating-lineup', 'Rotating lineup')] },
  { id: 'perfume', name: 'Perfume', region: 'JP', type: 'group', generationId: 'jpop-classic', spotifyArtistId: '52iwsT98xCoGgiGntTiWEc', members: [m('a-chan', 'A-chan'), m('kashiyuka', 'Kashiyuka'), m('nocchi', 'Nocchi')] },
  { id: 'babymetal', name: 'BABYMETAL', region: 'JP', type: 'group', generationId: 'jpop-modern', spotifyArtistId: '2CmyKp0BAzooaOtybkwe33', members: [m('su-metal', 'Su-metal'), m('moametal', 'Moametal')] },
  { id: 'yoasobi', name: 'YOASOBI', region: 'JP', type: 'group', generationId: 'jpop-modern', spotifyArtistId: '2G0ADgvTLU4Ns3PA9jPmZk', members: [m('ayase', 'Ayase'), m('ikura', 'Ikura')] },

  // --- C-pop ---
  { id: 'jay-chou', name: 'Jay Chou', region: 'CN', type: 'solo', generationId: 'cpop-classic', spotifyArtistId: '2ncn9wGmFvFxVzFcO88f7B', members: [m('jay-chou', 'Jay Chou')] },
  { id: 'faye-wong', name: 'Faye Wong', region: 'CN', type: 'solo', generationId: 'cpop-classic', members: [m('faye-wong', 'Faye Wong')] },
  { id: 'gem', name: 'G.E.M.', region: 'CN', type: 'solo', generationId: 'cpop-modern', spotifyArtistId: '3qQvraTVUR3sqCNBHSp5t9', members: [m('gem', 'G.E.M.')] },
  { id: 'mayday', name: 'Mayday', region: 'CN', type: 'group', generationId: 'cpop-classic', spotifyArtistId: '2gosLxsBIndzeIYNMSAgtd', members: [m('ashin', 'Ashin'), m('monster', 'Monster'), m('stone', 'Stone'), m('masa', 'Masa'), m('guanyou', 'Guan You')] },
  { id: 'tfboys', name: 'TFBOYS', region: 'CN', type: 'group', generationId: 'cpop-modern', members: [m('wang-junkai', 'Wang Junkai'), m('wang-yuan', 'Wang Yuan'), m('jackson-yee', 'Jackson Yee')] },

  // --- K-pop, 1st gen (additions) ---
  { id: 'finkl', name: 'Fin.K.L', region: 'KR', type: 'group', generationId: 'kpop-gen1', members: [m('lee-hyori', 'Lee Hyori'), m('ok-joohyun', 'Ok Joo-hyun'), m('sung-yuri', 'Sung Yu-ri'), m('lee-jiyeon', 'Lee Ji-yeon')] },
  { id: 'god', name: 'g.o.d', region: 'KR', type: 'group', generationId: 'kpop-gen1', members: [m('park-joonhyung', 'Park Joon-hyung'), m('yoon-kyesang', 'Yoon Kye-sang'), m('son-hoyoung', 'Son Ho-young'), m('kim-taewoo', 'Kim Tae-woo'), m('danny-ahn', 'Danny Ahn')] },
  { id: 'babyvox', name: 'Baby V.O.X', region: 'KR', type: 'group', generationId: 'kpop-gen1', members: [m('yoon-eunhye', 'Yoon Eun-hye'), m('lee-yiyoung', 'Lee Yi-young'), m('kan-miyeon', 'Kan Mi-yeon'), m('sim-eunjin', 'Sim Eun-jin'), m('ahn-jiyoung', 'Ahn Ji-young')] },

  // --- K-pop, 2nd gen (additions) ---
  { id: '2pm', name: '2PM', region: 'KR', type: 'group', generationId: 'kpop-gen2', spotifyArtistId: '0MliOMKAgcgigy2LcymRxV', members: [m('jang-wooyoung', 'Jang Woo-young'), m('lee-junho', 'Lee Jun-ho'), m('nichkhun', 'Nichkhun'), m('ok-taecyeon', 'Ok Taec-yeon'), m('hwang-chansung', 'Hwang Chan-sung')] },
  { id: '4minute', name: '4Minute', region: 'KR', type: 'group', generationId: 'kpop-gen2', members: [m('nam-jihyun', 'Nam Ji-hyun'), m('heo-gayoon', 'Heo Ga-yoon'), m('jeon-jiyoon', 'Jeon Ji-yoon'), m('kim-hyuna', 'Kim Hyuna'), m('gwon-sohyun', 'Gwon So-hyun')] },
  { id: 'after-school', name: 'After School', region: 'KR', type: 'group', generationId: 'kpop-gen2', members: [m('kahi', 'Kahi'), m('kim-jungah', 'Kim Jung-ah'), m('uee', 'UEE'), m('lizzy', 'Lizzy'), m('nana', 'Nana')] },
  { id: 'brown-eyed-girls', name: 'Brown Eyed Girls', region: 'KR', type: 'group', generationId: 'kpop-gen2', members: [m('jea', 'JeA'), m('miryo', 'Miryo'), m('narsha', 'Narsha'), m('gain', 'Ga-in')] },
  { id: 'fx', name: 'f(x)', region: 'KR', type: 'group', generationId: 'kpop-gen2', spotifyArtistId: '6nWCnRgTvsGCq95tKq5RKr', members: [m('victoria', 'Victoria'), m('amber', 'Amber'), m('luna', 'Luna'), m('krystal', 'Krystal'), m('sulli', 'Sulli')] },
  { id: 'infinite', name: 'Infinite', region: 'KR', type: 'group', generationId: 'kpop-gen2', spotifyArtistId: '2R4Jvvvj9ctdQuLnbo2ISH', members: [m('kim-sunggyu', 'Kim Sung-gyu'), m('jang-dongwoo', 'Jang Dong-woo'), m('lee-sungyeol', 'Lee Sung-yeol'), m('nam-woohyun', 'Nam Woo-hyun'), m('hoya', 'Hoya'), m('lee-sungjong', 'Lee Sung-jong'), m('dongwoo', 'L (Kim Myung-soo)')] },
  { id: 'mblaq', name: 'MBLAQ', region: 'KR', type: 'group', generationId: 'kpop-gen2', members: [m('seungho', 'Seung-ho'), m('gseven', 'G.O'), m('lee-joon', 'Lee Joon'), m('thunder', 'Thunder'), m('mir', 'Mir')] },
  { id: 'rainbow', name: 'Rainbow', region: 'KR', type: 'group', generationId: 'kpop-gen2', members: [m('kim-jaekyung', 'Kim Jae-kyung'), m('go-woori', 'Go Woo-ri'), m('cho-hyunyoung', 'Cho Hyun-young'), m('jung-yoonhye', 'Jung Yoon-hye'), m('oh-seunga', 'Oh Seung-a'), m('noeul', 'No-eul')] },
  { id: 'secret', name: 'Secret', region: 'KR', type: 'group', generationId: 'kpop-gen2', members: [m('song-jieun', 'Song Ji-eun'), m('jun-hyosung', 'Jun Hyo-sung'), m('han-sunhwa', 'Han Sun-hwa'), m('zinger', 'Zinger')] },
  { id: 'sistar', name: 'SISTAR', region: 'KR', type: 'group', generationId: 'kpop-gen2', spotifyArtistId: '2caU1RSVIVLXAoOqRZqucA', members: [m('hyorin', 'Hyorin'), m('bora', 'Bora'), m('soyou', 'Soyou'), m('dasom', 'Dasom')] },
  { id: 'ttara', name: 'T-ara', region: 'KR', type: 'group', generationId: 'kpop-gen2', spotifyArtistId: '2fN6ovhAiC7Cp23zdVEcOB', members: [m('boram', 'Boram'), m('qri', 'Qri'), m('soyeon-tara', 'Soyeon'), m('hyomin', 'Hyomin'), m('eunjung', 'Eunjung'), m('jiyeon', 'Jiyeon')] },
  { id: 'teen-top', name: 'Teen Top', region: 'KR', type: 'group', generationId: 'kpop-gen2', members: [m('cap', 'C.A.P'), m('niel', 'Niel'), m('changjo', 'Chang-jo'), m('lhan', 'L.Joe'), m('ricky', 'Ricky')] },
  { id: 'ukiss', name: 'U-KISS', region: 'KR', type: 'group', generationId: 'kpop-gen2', members: [m('soohyun', 'Soo-hyun'), m('eli', 'Eli'), m('kevin', 'Kevin'), m('jun', 'Jun'), m('hoon', 'Hoon')] },

  // --- K-pop, 3rd gen (additions) ---
  { id: 'aoa', name: 'AOA', region: 'KR', type: 'group', generationId: 'kpop-gen3', members: [m('jimin-aoa', 'Jimin'), m('yuna-aoa', 'Yuna'), m('hyejeong', 'Hyejeong'), m('choa', 'Choa'), m('mina-aoa', 'Mina'), m('seolhyun', 'Seolhyun')] },
  { id: 'apink', name: 'Apink', region: 'KR', type: 'group', generationId: 'kpop-gen3', spotifyArtistId: '2sGZ5F5R4AaX5m5S9c65pV', members: [m('park-chorong', 'Park Cho-rong'), m('yoon-bomi', 'Yoon Bo-mi'), m('son-naeun', 'Son Na-eun'), m('jung-eunji', 'Jung Eun-ji'), m('kim-namjoo', 'Kim Nam-joo'), m('oh-hayoung', 'Oh Ha-young')] },
  { id: 'block-b', name: 'Block B', region: 'KR', type: 'group', generationId: 'kpop-gen3', spotifyArtistId: '4NCigDoV7QXTHHqbFCXm2X', members: [m('zico', 'Zico'), m('taeil', 'Tae-il'), m('bbomb', 'B-Bomb'), m('jaehyo', 'Jae-hyo'), m('ukwon', 'U-Kwon'), m('pyo-jihoon', 'P.O'), m('kyung', 'Kyung')] },
  { id: 'btob', name: 'BTOB', region: 'KR', type: 'group', generationId: 'kpop-gen3', spotifyArtistId: '2yzHYpvSy7ONdinIYSg1cD', members: [m('eunkwang', 'Eun-kwang'), m('minhyuk', 'Min-hyuk'), m('changsub', 'Chang-sub'), m('hyunsik', 'Hyun-sik'), m('peniel', 'Peniel'), m('ilhoon', 'Il-hoon'), m('sungjae', 'Sung-jae')] },
  { id: 'wjsn', name: 'WJSN (Cosmic Girls)', region: 'KR', type: 'group', generationId: 'kpop-gen3', spotifyArtistId: '6Ff5Jff5xzHntq2mF5U6Hh', members: [m('seola', 'Seola'), m('bona', 'Bona'), m('exy', 'Exy'), m('soobin-wjsn', 'Soobin'), m('luda', 'Luda'), m('dawon', 'Dawon'), m('yeoreum', 'Yeoreum'), m('eunseo', 'Eunseo'), m('xuan-yi', 'XuanYi'), m('cheng-xiao', 'Cheng Xiao')] },
  { id: 'dreamcatcher', name: 'Dreamcatcher', region: 'KR', type: 'group', generationId: 'kpop-gen3', spotifyArtistId: '6M2wZ9GZAOTHfGdxSJdmDh', members: [m('jiu', 'JiU'), m('sua', 'SuA'), m('siyeon', 'Siyeon'), m('handong', 'Handong'), m('yoohyeon', 'YooHyeon'), m('dami', 'Dami'), m('gahyeon', 'Gahyeon')] },
  { id: 'exid', name: 'EXID', region: 'KR', type: 'group', generationId: 'kpop-gen3', members: [m('solji', 'Solji'), m('leggo', 'LE'), m('hani', 'Hani'), m('jeonghwa', 'Jeong-hwa'), m('hyelin', 'Hye-lin')] },
  { id: 'girls-day', name: "Girl's Day", region: 'KR', type: 'group', generationId: 'kpop-gen3', members: [m('sojin', 'So-jin'), m('yura', 'Yu-ra'), m('minah', 'Mi-na'), m('hyeri', 'Hye-ri')] },
  { id: 'ikon', name: 'iKON', region: 'KR', type: 'group', generationId: 'kpop-gen3', spotifyArtistId: '2r00K1prIfSzvUdKQpfBGV', members: [m('jay', 'Jay (Kim Jin-hwan)'), m('bobby', 'Bobby'), m('song-yunhyeong', 'Song Yun-hyeong'), m('koo-junhoe', 'Koo Jun-hoe'), m('kim-donghyuk', 'Kim Dong-hyuk'), m('chanwoo', 'Chan-woo')] },
  { id: 'lovelyz', name: 'Lovelyz', region: 'KR', type: 'group', generationId: 'kpop-gen3', members: [m('yoo-jiae', 'Yoo Ji-ae'), m('seo-jisoo', 'Seo Ji-soo'), m('mijoo', 'Mi-joo'), m('kei', 'Kei'), m('ryu-sujeong', 'Ryu Su-jeong'), m('jin', 'Jin'), m('yein', 'Ye-in')] },
  { id: 'monsta-x', name: 'Monsta X', region: 'KR', type: 'group', generationId: 'kpop-gen3', spotifyArtistId: '2Cx8xdz506x0jN3myYcYYJ', members: [m('shownu', 'Shownu'), m('wonho', 'Wonho'), m('minhyuk-mx', 'Min-hyuk'), m('kihyun', 'Ki-hyun'), m('hyungwon', 'Hyung-won'), m('joohoney', 'Joo-heon'), m('im-changkyun', 'I.M')] },
  { id: 'nct127', name: 'NCT 127', region: 'KR', type: 'group', generationId: 'kpop-gen3', spotifyArtistId: '7f4ihTNEWGN0Vgsz9CFXXO', members: [m('taeyong', 'Taeyong'), m('johnny', 'Johnny'), m('taeil-nct', 'Taeil'), m('yuta', 'Yuta'), m('doyoung', 'Doyoung'), m('jaehyun', 'Jaehyun'), m('winwin', 'WinWin'), m('mark-nct', 'Mark'), m('haechan', 'Haechan')] },
  { id: 'nct-dream', name: 'NCT Dream', region: 'KR', type: 'group', generationId: 'kpop-gen3', spotifyArtistId: '2NyzBdE5G0PDS8kW1LbcCn', members: [m('mark-dream', 'Mark'), m('renjun', 'Renjun'), m('jeno', 'Jeno'), m('haechan-dream', 'Haechan'), m('jaemin', 'Jaemin'), m('chenle', 'Chenle'), m('jisung', 'Jisung')] },
  { id: 'oh-my-girl', name: 'Oh My Girl', region: 'KR', type: 'group', generationId: 'kpop-gen3', spotifyArtistId: '5Ecm93SbGF6NoEBLtQCLYD', members: [m('hyojung', 'Hyo-jung'), m('mimi', 'Mi-mi'), m('yooa', 'Yoo-a'), m('seunghee', 'Seung-hee'), m('binnie', 'Bin-nie'), m('jiho', 'Ji-ho'), m('arin', 'A-rin')] },
  { id: 'pentagon', name: 'Pentagon', region: 'KR', type: 'group', generationId: 'kpop-gen3', spotifyArtistId: '4vHOUwyGjnGxXymfImrpQU', members: [m('jinho', 'Jin-ho'), m('hui', 'Hui'), m('hongseok', 'Hong-seok'), m('shinwon', 'Shin-won'), m('yeoone', 'Yeo-one'), m('yanan', 'Yan An'), m('yuto', 'Yuto'), m('kino', 'Kino'), m('wooseok', 'Woo-seok')] },
  { id: 'vixx', name: 'VIXX', region: 'KR', type: 'group', generationId: 'kpop-gen3', spotifyArtistId: '2FvvFF39dW6L8QqIvdcYFU', members: [m('n', 'N'), m('leo', 'Leo'), m('ken', 'Ken'), m('ravi', 'Ravi'), m('hongbin', 'Hong-bin'), m('hyuk', 'Hyuk')] },
  { id: 'winner', name: 'WINNER', region: 'KR', type: 'group', generationId: 'kpop-gen3', spotifyArtistId: '46tGdhBaKf4T2ZaMvj0M2R', members: [m('kang-seungyoon', 'Kang Seung-yoon'), m('lee-seunghoon', 'Lee Seung-hoon'), m('song-mino', 'Song Min-ho'), m('kim-jinwoo', 'Kim Jin-woo')] },

  // --- K-pop, 4th gen (additions) ---
  { id: 'cravity', name: 'CRAVITY', region: 'KR', type: 'group', generationId: 'kpop-gen4', spotifyArtistId: '3Ov6qOsn7SJ1JCq6HLDgTb', members: [m('serim', 'Serim'), m('allen', 'Allen'), m('jungmo', 'Jung-mo'), m('woobin', 'Woo-bin'), m('wonjin', 'Won-jin'), m('minhee', 'Min-hee'), m('hyeongjun', 'Hyeong-jun'), m('taeyoung', 'Tae-young'), m('seongmin', 'Seong-min')] },
  { id: 'everglow', name: 'EVERGLOW', region: 'KR', type: 'group', generationId: 'kpop-gen4', spotifyArtistId: '6TzMHm3sfHUKamqXfvHzTA', members: [m('e-somi', 'E:U'), m('sihyeon', 'Si-hyeon'), m('mia', 'Mia'), m('onda', 'On-da'), m('aisha', 'Aisha'), m('yiren', 'Yiren')] },
  { id: 'fromis9', name: 'fromis_9', region: 'KR', type: 'group', generationId: 'kpop-gen4', spotifyArtistId: '2eS3yrjQeBP3jYlyIvsFhb', members: [m('saerom', 'Sae-rom'), m('hayoung', 'Ha-young'), m('gyuri', 'Gyu-ri'), m('jiwon', 'Ji-won'), m('seoyeon', 'Seo-yeon'), m('chaeyoung-fromis', 'Chae-young'), m('nagyung', 'Na-gyung'), m('jiheon', 'Ji-heon')] },
  { id: 'kep1er', name: 'Kep1er', region: 'KR', type: 'group', generationId: 'kpop-gen4', spotifyArtistId: '0h9L0Yq9lIVdpq5EOFYq2A', members: [m('choi-yujin', 'Choi Yu-jin'), m('mashiro', 'Mashiro'), m('shen-xiaoting', 'Xiaoting'), m('kim-chaehyun', 'Chae-hyun'), m('huening-bahiyyih', 'Bahiyyih'), m('kim-dayeon', 'Da-yeon'), m('seo-youngeun', 'Young-eun'), m('kang-yeseo', 'Ye-seo')] },
  { id: 'nmixx', name: 'NMIXX', region: 'KR', type: 'group', generationId: 'kpop-gen4', spotifyArtistId: '4b0PfHQTot9YctIu0MOaJi', members: [m('lily', 'Lily'), m('haewon', 'Hae-won'), m('sullyoon', 'Sul-lyoon'), m('bae', 'Bae'), m('jiwoo-nmixx', 'Ji-woo'), m('kyujin', 'Kyu-jin')] },
  { id: 'oneus', name: 'ONEUS', region: 'KR', type: 'group', generationId: 'kpop-gen4', spotifyArtistId: '0EX9Vfxm3AB5FnbwzPRw6O', members: [m('seoho', 'Seo-ho'), m('leedo', 'Lee-do'), m('keonhee', 'Keon-hee'), m('hwanwoong', 'Hwan-woong'), m('xion', 'Xion')] },
  { id: 'p1harmony', name: 'P1Harmony', region: 'KR', type: 'group', generationId: 'kpop-gen4', spotifyArtistId: '0v1XpBHnsbkCn7iRkP0aic', members: [m('keeho', 'Kee-ho'), m('theo', 'Theo'), m('jiung', 'Ji-ung'), m('intak', 'In-tak'), m('soul', 'Soul'), m('jongseob', 'Jong-seob')] },
  { id: 'staych', name: 'STAYC', region: 'KR', type: 'group', generationId: 'kpop-gen4', spotifyArtistId: '4e0FnabDNDce87Q0Ejt5jS', members: [m('sumin', 'Su-min'), m('sieun', 'Si-eun'), m('isa', 'Isa'), m('seeun', 'Se-eun'), m('yoon', 'Yoon'), m('j-staych', 'J')] },
  { id: 'treasure', name: 'TREASURE', region: 'KR', type: 'group', generationId: 'kpop-gen4', spotifyArtistId: '4KfDG9SgnBnwEo0YOh2Ni9', members: [m('choi-hyunsuk', 'Choi Hyun-suk'), m('jihoon', 'Ji-hoon'), m('yoshi', 'Yoshi'), m('junkyu', 'Jun-kyu'), m('mashiho', 'Mashiho'), m('jaehyuk', 'Jae-hyuk'), m('yedam', 'Ye-dam'), m('doyoung-treasure', 'Do-young'), m('haruto', 'Haruto'), m('asahi', 'Asahi')] },

  // --- K-pop, 5th gen (additions) ---
  { id: 'kissoflife', name: 'KISS OF LIFE', region: 'KR', type: 'group', generationId: 'kpop-gen5', spotifyArtistId: '4rvJ2p2QaEfDzLwR5RCPnn', members: [m('julie', 'Julie'), m('natty', 'Natty'), m('belle', 'Belle'), m('haneul', 'Hane-ul')] },
  { id: 'hearts2hearts', name: 'Hearts2Hearts', region: 'KR', type: 'group', generationId: 'kpop-gen5', members: [m('jiwoo-h2h', 'Jiwoo'), m('carmen', 'Carmen'), m('yuha', 'Yuha'), m('stella', 'Stella'), m('juun', 'Juun'), m('a-na', 'A-na'), m('ian', 'Ian'), m('ye-on', 'Ye-on')] },

  // --- J-pop (additions) ---
  { id: 'nogizaka46', name: 'Nogizaka46', region: 'JP', type: 'group', generationId: 'jpop-modern', members: [m('rotating-lineup-n46', 'Rotating lineup')] },
  { id: 'sakurazaka46', name: 'Sakurazaka46', region: 'JP', type: 'group', generationId: 'jpop-modern', members: [m('rotating-lineup-s46', 'Rotating lineup')] },
  { id: 'momoiro-clover-z', name: 'Momoiro Clover Z', region: 'JP', type: 'group', generationId: 'jpop-modern', spotifyArtistId: '0sMDBGSfN4a2GinRQ4Q1Qi', members: [m('kanako', 'Kanako Momota'), m('shiori', 'Shiori Tamai'), m('ayaka', 'Ayaka Sasaki'), m('momoka', 'Momoka Ariyasu')] },
  { id: 'sixtones', name: 'SixTONES', region: 'JP', type: 'group', generationId: 'jpop-modern', spotifyArtistId: '3XvcHTFtA7WIRAcOwbP0DL', members: [m('jesse', 'Jesse'), m('shintaro', 'Shintaro Morimoto'), m('juri', 'Juri Tanaka'), m('taiga', 'Taiga Kyomoto'), m('koki', 'Yugo Kochi'), m('hokuto', 'Hokuto Matsumura')] },
  { id: 'snowman', name: 'Snow Man', region: 'JP', type: 'group', generationId: 'jpop-modern', spotifyArtistId: '4qXpqfeZ5b3jAoLNCz7Q4o', members: [m('iwamoto', 'Hikaru Iwamoto'), m('fukazawa', 'Tatsuya Fukazawa'), m('abe', 'Ryusei Abe'), m('sakuma', 'Daisuke Sakuma'), m('watanabe', 'Shota Watanabe'), m('muto', 'Koji Mukai'), m('raul', 'Raul'), m('meguro', 'Ren Meguro'), m('ozeki', 'Ryota Miyadate')] },
  { id: 'kanjani8', name: "Kanjani Eight", region: 'JP', type: 'group', generationId: 'jpop-classic', members: [m('murakami', 'Shingo Murakami'), m('maruyama', 'Ryuhei Maruyama'), m('yokoyama', 'Yu Yokoyama'), m('shibutani', 'Subaru Shibutani'), m('yasuda', 'Shota Yasuda'), m('nishikawa', 'Takanori Nishikawa')] },
  { id: 'kingandprince', name: 'King & Prince', region: 'JP', type: 'group', generationId: 'jpop-modern', spotifyArtistId: '4qk9GMTNmCwGSTLnCbfWfw', members: [m('hirano', 'Sho Hirano'), m('kishi', 'Yuta Kishi'), m('nagase', 'Ren Nagase'), m('takahashi', 'Kaito Takahashi')] },
  { id: 'jo1', name: 'JO1', region: 'JP', type: 'group', generationId: 'jpop-modern', spotifyArtistId: '4LG9ZKG9EGOd7iy1DsVJXn', members: [m('shion', 'Shion Tsurubo'), m('issei', 'Issei Yoshinaga'), m('ren', 'Ren Kawashiri'), m('sho', 'Sho Ohkubo'), m('syoya', 'Syoya Kimata'), m('keito', 'Keito Okamoto'), m('junki', 'Junki Kono'), m('ruki', 'Ruki Kawanishi'), m('mame', 'Mame Shirahama'), m('takumi', 'Takumi Kagiya'), m('yu', 'Yu Shirahama')] },
  { id: 'ado', name: 'Ado', region: 'JP', type: 'solo', generationId: 'jpop-modern', spotifyArtistId: '5xYYCJXaXWDwsWvNyErpM7', members: [m('ado', 'Ado')] },
  { id: 'kenshi-yonezu', name: 'Kenshi Yonezu', region: 'JP', type: 'solo', generationId: 'jpop-modern', spotifyArtistId: '4tOgWXoZ4wJ3nWSVbHKcS9', members: [m('kenshi-yonezu', 'Kenshi Yonezu')] },
  { id: 'lisa', name: 'LiSA', region: 'JP', type: 'solo', generationId: 'jpop-modern', spotifyArtistId: '2NxfADvBiSXHK6VGV6MO2r', members: [m('lisa', 'LiSA')] },

  // --- C-pop (additions) ---
  { id: 'she', name: 'S.H.E', region: 'CN', type: 'group', generationId: 'cpop-classic', members: [m('selina', 'Selina Ren'), m('hebe', 'Hebe Tien'), m('ella', 'Ella Chen')] },
  { id: 'fahrenheit', name: 'Fahrenheit', region: 'CN', type: 'group', generationId: 'cpop-classic', members: [m('wu-chun', 'Wu Chun'), m('aaron-yan', 'Aaron Yan'), m('calvin-chen', 'Calvin Chen'), m('jiro-wang', 'Jiro Wang')] },
  { id: 'jolin-tsai', name: 'Jolin Tsai', region: 'CN', type: 'solo', generationId: 'cpop-modern', spotifyArtistId: '2QsWZmpRnR8n3rHVQF3Rp6', members: [m('jolin-tsai', 'Jolin Tsai')] },
  { id: 'jj-lin', name: 'JJ Lin', region: 'CN', type: 'solo', generationId: 'cpop-modern', spotifyArtistId: '2SGWoifhkFkNJtP83DfHFy', members: [m('jj-lin', 'JJ Lin')] },
  { id: 'wang-leehom', name: 'Wang Leehom', region: 'CN', type: 'solo', generationId: 'cpop-classic', members: [m('wang-leehom', 'Wang Leehom')] },
  { id: 'eric-chou', name: 'Eric Chou', region: 'CN', type: 'solo', generationId: 'cpop-modern', spotifyArtistId: '6uY4hn7oFR3wpJ1M9EqBH8', members: [m('eric-chou', 'Eric Chou')] },
  { id: 'into1', name: 'INTO1', region: 'CN', type: 'group', generationId: 'cpop-modern', members: [m('liu-yu', 'Liu Yu'), m('zhou-keyu', 'Zhou Keyu'), m('mika', 'Mika'), m('zhang-jing', 'Zhang Jing'), m('liu-zhang', 'Liu Zhang'), m('r1se', 'Zhao Lei')] },
  { id: 'snh48', name: 'SNH48', region: 'CN', type: 'group', generationId: 'cpop-modern', members: [m('rotating-lineup-snh48', 'Rotating lineup')] },
  { id: 'zhou-shen', name: 'Zhou Shen', region: 'CN', type: 'solo', generationId: 'cpop-modern', members: [m('zhou-shen', 'Zhou Shen')] },
]
